CREATE TABLE [sis].[Part] (
    [Part_ID]     INT          NOT NULL,
    [Part_Number] VARCHAR (50) NOT NULL,
    [Org_Code]    VARCHAR (12) NOT NULL DEFAULT 'CAT',
    CONSTRAINT [PK_Part] PRIMARY KEY CLUSTERED ([Part_ID] ASC) WITH (FILLFACTOR = 100)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [NCI_PartPart_Number_Part_Org_Code] ON [sis].[Part]
(
	[Part_Number] ASC,
	[Org_Code] ASC
)
INCLUDE([Part_ID]) WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO

