CREATE Procedure [SISSEARCH].[PARTHISTORYIEPART_FULL_RELOAD] as
Begin

EXEC SISSEARCH.WriteLog @NAMEOFSPROC = 'SISSEARCH.PARTHISTORYIEPART_FULL_RELOAD', @LOGMESSAGE = 'Execution started';

Truncate table [SISSEARCH].[PARTHISTORYIEPART]
EXEC [SISSEARCH].[PARTHISTORYIEPART_LOAD]

EXEC SISSEARCH.WriteLog @NAMEOFSPROC = 'SISSEARCH.PARTHISTORYIEPART_FULL_RELOAD', @LOGMESSAGE = 'Execution completed';

End