CREATE Procedure [SISSEARCH].[SMCS_2_FULL_RELOAD] as
Begin

--Start
DECLARE @PROCNAME         VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID);

EXEC SISSEARCH.WriteLog @NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started';

--Truncate table [SISSEARCH].[BASICPARTS]
--Truncate table [SISSEARCH].[CONSISTPARTS]
--Truncate table [SISSEARCH].[PRODUCTSTRUCTURE]
Truncate table [SISSEARCH].[SMCS_2]
--Truncate table [SISSEARCH].[SNP]

--Begin Try ALTER TABLE [SISSEARCH].[BASICPARTS] Disable CHANGE_TRACKING End Try Begin Catch End Catch;
--Begin Try ALTER TABLE [SISSEARCH].[CONSISTPARTS] Disable CHANGE_TRACKING end try Begin Catch End Catch;
--Begin Try ALTER TABLE [SISSEARCH].[PRODUCTSTRUCTURE] Disable CHANGE_TRACKING end try Begin Catch End Catch;
--Begin Try ALTER TABLE [SISSEARCH].[SMCS_2] Disable CHANGE_TRACKING end try Begin Catch End Catch;
--Begin Try ALTER TABLE [SISSEARCH].[SNP] Disable CHANGE_TRACKING end try Begin Catch End Catch;

--EXEC [SISSEARCH].[BASICPARTS_LOAD]
--EXEC [SISSEARCH].[CONSISTPARTS_LOAD]
--EXEC [SISSEARCH].[PRODUCTSTRUCTURE_LOAD]
EXEC [SISSEARCH].[SMCS_2_LOAD]
--EXEC [SISSEARCH].[SNP_LOAD]

--ALTER TABLE [SISSEARCH].[BASICPARTS] ENABLE CHANGE_TRACKING  WITH (TRACK_COLUMNS_UPDATED = OFF)  
--ALTER TABLE [SISSEARCH].[CONSISTPARTS] ENABLE CHANGE_TRACKING  WITH (TRACK_COLUMNS_UPDATED = OFF)  
--ALTER TABLE [SISSEARCH].[PRODUCTSTRUCTURE] ENABLE CHANGE_TRACKING  WITH (TRACK_COLUMNS_UPDATED = OFF)  
--ALTER TABLE [SISSEARCH].[SMCS_2] ENABLE CHANGE_TRACKING  WITH (TRACK_COLUMNS_UPDATED = OFF)  
--ALTER TABLE [SISSEARCH].[SNP] ENABLE CHANGE_TRACKING  WITH (TRACK_COLUMNS_UPDATED = OFF)  

--End
EXEC SISSEARCH.WriteLog @NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed';

End