CREATE VIEW [SISWEB_OWNER_STAGING].[FLASH_FILE_PROPERTIES]
AS
   SELECT [FILERID]
         ,[INFOTYPEID]
         ,[FILENAME]
         ,[AVAILABLEFLAG]
         ,[MIMETYPE]
         ,[FILESIZE]
         ,[UPDATEDDATE]
         ,[CREATEDDATE]
         ,[LASTMODIFIEDDATE]
   FROM [SISWEB_OWNER_STAGING].[MASFILEPROPERTIES] WHERE INFOTYPEID = 41;
GO

