
-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200113
-- Modify Date: 20200122	refactored LASTMODIFIEDDATE
-- Modify Date: 20200205	fixed deadlock error
-- Description: Conditional load from STAGING LNKASSHIPPEDPRODUCTDETAILS
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKASSHIPPEDPRODUCTDETAILS_Insert_Update_Delete (@FORCE_LOAD BIT = 'FALSE'
																					  ,@DEBUG      BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY
		DECLARE @SCHEMANAME sysname = 'SISWEB_OWNER_STAGING'
			   ,@TABLENAME  sysname = 'LNKASSHIPPEDPRODUCTDETAILS';

		DECLARE @FULLTABLENAME   sysname = @SCHEMANAME + '.' + @TABLENAME
			   ,@CURRENT_VERSION BIGINT  = CHANGE_TRACKING_CURRENT_VERSION();

		DECLARE @LAST_SYNCHRONIZATION_VERSION BIGINT           = SISWEB_OWNER_STAGING._getLastSynchVersion (@FULLTABLENAME)
			   ,@RESULT                       BIT
			   ,@ROWCOUNT                     BIGINT
			   ,@MERGED_ROWS                  BIGINT           = 0
			   ,@SYSUTCDATETIME               DATETIME2(6)     = SYSUTCDATETIME()
			   ,@PROCNAME                     VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID                    UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE                   VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE             NVARCHAR(10)
									 ,SERIALNUMBER           VARCHAR(8) NOT NULL
									 ,PARTSEQUENCENUMBER     NUMERIC(10,0) NOT NULL
									 ,PARTNUMBER             VARCHAR(20) NOT NULL
									 ,PARTNAME               VARCHAR(512) NOT NULL
									 ,PARENTPARTNUMBER       VARCHAR(20) NULL
									 ,ATTACHMENTSERIALNUMBER VARCHAR(20) NULL
									 ,SOURCELOCATION         VARCHAR(1) NOT NULL
									 ,EMDPROCESSEDDATE       DATETIME2(0) NOT NULL
									 ,ID                     NUMERIC(38,10) NOT NULL
									 ,PARTORDER              NUMERIC(10,0) NULL
									 ,PARTLEVEL              NUMERIC(1,0) NULL
									 ,PARENTAGE              NUMERIC(38,10) NULL
									 ,LASTMODIFIEDDATE       DATETIME2(6) NULL);

/* 
	Davide 20200205 
	in order to avoid deadlocks errors like: "Transaction (Process ID 246) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.",
	we move the creation of temp table outside the TRANSACTION block, even if it is not extremely elegant
*/
		DROP TABLE IF EXISTS #DIFF_PRIMARY_KEYS;
		SELECT CT.SYS_CHANGE_OPERATION AS OPERATION,CT.ID AS ID,CT.SYS_CHANGE_VERSION AS SYS_CHANGE_VERSION,CT.SYS_CHANGE_COLUMNS AS SYS_CHANGE_COLUMNS
		INTO #DIFF_PRIMARY_KEYS
		FROM CHANGETABLE(CHANGES SISWEB_OWNER_STAGING.LNKASSHIPPEDPRODUCTDETAILS,@LAST_SYNCHRONIZATION_VERSION) AS CT;

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		IF @FORCE_LOAD = 'FALSE'
		BEGIN
			EXEC SISWEB_OWNER_STAGING._getFullOrDiff @SCHEMANAME = @SCHEMANAME,@TABLENAME = @TABLENAME,@CURRENT_VERSION = @CURRENT_VERSION,@DEBUG = @DEBUG,@RESULT = @RESULT OUTPUT
			;

			IF @DEBUG = 'TRUE'
				PRINT FORMATMESSAGE('@RESULT=%s',IIF(@RESULT = 1,'TRUE','FALSE'));

			IF @RESULT = 'TRUE'
			BEGIN
				-- 6. Obtain the changes

				IF @DEBUG = 'TRUE'
					SELECT * FROM #DIFF_PRIMARY_KEYS AS DK;

				-- 7.a Delete if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'D';
				IF @ROWCOUNT > 0
				BEGIN
					DELETE FROM SISWEB_OWNER.LNKASSHIPPEDPRODUCTDETAILS
					OUTPUT 'DELETE' ACTIONTYPE,DELETED.SERIALNUMBER,DELETED.PARTSEQUENCENUMBER,DELETED.PARTNUMBER,DELETED.PARTNAME,DELETED.PARENTPARTNUMBER,DELETED.
					ATTACHMENTSERIALNUMBER,DELETED.SOURCELOCATION,DELETED.EMDPROCESSEDDATE,DELETED.ID,DELETED.PARTORDER,DELETED.PARTLEVEL,DELETED.PARENTAGE,DELETED.
					LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.ID = LNKASSHIPPEDPRODUCTDETAILS.ID AND 
							  DK.OPERATION = 'D'
					);

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Deleted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.b Insert if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'I';
				IF @ROWCOUNT > 0
				BEGIN
					INSERT INTO SISWEB_OWNER.LNKASSHIPPEDPRODUCTDETAILS (SERIALNUMBER,PARTSEQUENCENUMBER,PARTNUMBER,PARTNAME,PARENTPARTNUMBER,ATTACHMENTSERIALNUMBER,SOURCELOCATION,
					EMDPROCESSEDDATE,ID,PARTORDER,PARTLEVEL,PARENTAGE,LASTMODIFIEDDATE) 
					OUTPUT 'INSERT' ACTIONTYPE,INSERTED.SERIALNUMBER,INSERTED.PARTSEQUENCENUMBER,INSERTED.PARTNUMBER,INSERTED.PARTNAME,INSERTED.PARENTPARTNUMBER,INSERTED.
					ATTACHMENTSERIALNUMBER,INSERTED.SOURCELOCATION,INSERTED.EMDPROCESSEDDATE,INSERTED.ID,INSERTED.PARTORDER,INSERTED.PARTLEVEL,INSERTED.PARENTAGE,INSERTED.
					LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
						   SELECT SERIALNUMBER,PARTSEQUENCENUMBER,PARTNUMBER,PARTNAME,PARENTPARTNUMBER,ATTACHMENTSERIALNUMBER,SOURCELOCATION,EMDPROCESSEDDATE,ID,PARTORDER,
						   PARTLEVEL,PARENTAGE,@SYSUTCDATETIME
						   FROM SISWEB_OWNER_STAGING.LNKASSHIPPEDPRODUCTDETAILS AS DT
						   WHERE EXISTS
						   (
							   SELECT * FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.ID = DT.ID AND 
																			DK.OPERATION = 'I'
						   );

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Inserted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.c Update if needed
				SELECT @ROWCOUNT = COUNT(*)
				FROM #DIFF_PRIMARY_KEYS AS DK
				WHERE DK.OPERATION = 'U' AND 
					  (-- if the modified column is LASTMODIFIEDDATE ignore the update 
					  DK.SYS_CHANGE_COLUMNS <> 0x000000000D000000 OR 
					  DK.SYS_CHANGE_COLUMNS IS NULL
					  );
				IF @ROWCOUNT > 0
				BEGIN
					UPDATE SISWEB_OWNER.LNKASSHIPPEDPRODUCTDETAILS
					  SET SERIALNUMBER = ST.SERIALNUMBER,PARTSEQUENCENUMBER = ST.PARTSEQUENCENUMBER,PARTNUMBER = ST.PARTNUMBER,PARTNAME = ST.PARTNAME,PARENTPARTNUMBER = ST.
					  PARENTPARTNUMBER,ATTACHMENTSERIALNUMBER = ST.ATTACHMENTSERIALNUMBER,SOURCELOCATION = ST.SOURCELOCATION,EMDPROCESSEDDATE = ST.EMDPROCESSEDDATE,PARTORDER = ST.
					  PARTORDER,PARTLEVEL = ST.PARTLEVEL,PARENTAGE = ST.PARENTAGE,LASTMODIFIEDDATE = @SYSUTCDATETIME
					OUTPUT 'UPDATE' ACTIONTYPE,INSERTED.SERIALNUMBER,INSERTED.PARTSEQUENCENUMBER,INSERTED.PARTNUMBER,INSERTED.PARTNAME,INSERTED.PARENTPARTNUMBER,INSERTED.
					ATTACHMENTSERIALNUMBER,INSERTED.SOURCELOCATION,INSERTED.EMDPROCESSEDDATE,INSERTED.ID,INSERTED.PARTORDER,INSERTED.PARTLEVEL,INSERTED.PARENTAGE,INSERTED.
					LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					FROM SISWEB_OWNER_STAGING.LNKASSHIPPEDPRODUCTDETAILS AS ST
						 JOIN SISWEB_OWNER.LNKASSHIPPEDPRODUCTDETAILS AS TT ON ST.ID = TT.ID
					WHERE EXISTS
					(
						SELECT * FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.ID = ST.ID AND 
																	 DK.OPERATION = 'U'
					);
					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Updated %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 8. Store current version to be used the next time
				IF @DEBUG = 'TRUE'
					SELECT * FROM @MERGE_RESULTS AS MR;

				SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
				(
					SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
					'UPDATE'
					) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
					(
						SELECT MR.ACTIONTYPE,MR.SERIALNUMBER,MR.PARTSEQUENCENUMBER,MR.PARTNUMBER,MR.PARTNAME,MR.PARENTPARTNUMBER,MR.ATTACHMENTSERIALNUMBER,MR.SOURCELOCATION,MR.
						EMDPROCESSEDDATE,MR.ID,MR.PARTORDER,MR.PARTLEVEL,MR.PARENTAGE,MR.LASTMODIFIEDDATE
						FROM @MERGE_RESULTS AS MR FOR JSON AUTO
					) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
				),'Modified Rows');
				EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
			END;
		END;

		/* to be done: handle full load with MERGE */
		IF @FORCE_LOAD = 'TRUE'
		--   OR @MODIFIED_ROWS_PERCENTAGE BETWEEN-0.10 AND 0.10
		BEGIN
			SET @LOGMESSAGE = 'Executing load: Force Load = TRUE';
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @FORCE_LOAD;

			/* MERGE command */
			MERGE INTO SISWEB_OWNER.LNKASSHIPPEDPRODUCTDETAILS tgt
			USING SISWEB_OWNER_STAGING.LNKASSHIPPEDPRODUCTDETAILS src
			ON src.ID = tgt.ID
			WHEN MATCHED AND EXISTS
			(
				SELECT src.SERIALNUMBER,src.PARTSEQUENCENUMBER,src.PARTNUMBER,src.PARTNAME,src.PARENTPARTNUMBER,src.ATTACHMENTSERIALNUMBER,src.SOURCELOCATION,src.EMDPROCESSEDDATE,
				src.PARTORDER,src.PARTLEVEL,src.PARENTAGE
				EXCEPT
				SELECT tgt.SERIALNUMBER,tgt.PARTSEQUENCENUMBER,tgt.PARTNUMBER,tgt.PARTNAME,tgt.PARENTPARTNUMBER,tgt.ATTACHMENTSERIALNUMBER,tgt.SOURCELOCATION,tgt.EMDPROCESSEDDATE,
				tgt.PARTORDER,tgt.PARTLEVEL,tgt.PARENTAGE
			)
				  THEN UPDATE SET tgt.SERIALNUMBER = src.SERIALNUMBER,tgt.PARTSEQUENCENUMBER = src.PARTSEQUENCENUMBER,tgt.PARTNUMBER = src.PARTNUMBER,tgt.PARTNAME = src.PARTNAME,
				  tgt.PARENTPARTNUMBER = src.PARENTPARTNUMBER,tgt.ATTACHMENTSERIALNUMBER = src.ATTACHMENTSERIALNUMBER,tgt.SOURCELOCATION = src.SOURCELOCATION,tgt.EMDPROCESSEDDATE
				  = src.EMDPROCESSEDDATE,tgt.PARTORDER = src.PARTORDER,tgt.PARTLEVEL = src.PARTLEVEL,tgt.PARENTAGE = src.PARENTAGE,tgt.LASTMODIFIEDDATE = @SYSUTCDATETIME
			WHEN NOT MATCHED BY TARGET
				  THEN
				  INSERT(SERIALNUMBER,PARTSEQUENCENUMBER,PARTNUMBER,PARTNAME,PARENTPARTNUMBER,ATTACHMENTSERIALNUMBER,SOURCELOCATION,EMDPROCESSEDDATE,ID,PARTORDER,PARTLEVEL,
				  PARENTAGE,LASTMODIFIEDDATE)
				  VALUES (src.SERIALNUMBER,src.PARTSEQUENCENUMBER,src.PARTNUMBER,src.PARTNAME,src.PARENTPARTNUMBER,src.ATTACHMENTSERIALNUMBER,src.SOURCELOCATION,src.
				  EMDPROCESSEDDATE,src.ID,src.PARTORDER,src.PARTLEVEL,src.PARENTAGE,@SYSUTCDATETIME) 
			WHEN NOT MATCHED BY SOURCE
				  THEN DELETE
			OUTPUT $ACTION,COALESCE(inserted.SERIALNUMBER,deleted.SERIALNUMBER) SERIALNUMBER,COALESCE(inserted.PARTSEQUENCENUMBER,deleted.PARTSEQUENCENUMBER) PARTSEQUENCENUMBER,
			COALESCE(inserted.PARTNUMBER,deleted.PARTNUMBER) PARTNUMBER,COALESCE(inserted.PARTNAME,deleted.PARTNAME) PARTNAME,COALESCE(inserted.PARENTPARTNUMBER,deleted.
			PARENTPARTNUMBER) PARENTPARTNUMBER,COALESCE(inserted.ATTACHMENTSERIALNUMBER,deleted.ATTACHMENTSERIALNUMBER) ATTACHMENTSERIALNUMBER,COALESCE(inserted.SOURCELOCATION,
			deleted.SOURCELOCATION) SOURCELOCATION,COALESCE(inserted.EMDPROCESSEDDATE,deleted.EMDPROCESSEDDATE) EMDPROCESSEDDATE,COALESCE(inserted.ID,deleted.ID) ID,COALESCE(
			inserted.PARTORDER,deleted.PARTORDER) PARTORDER,COALESCE(inserted.PARTLEVEL,deleted.PARTLEVEL) PARTLEVEL,COALESCE(inserted.PARENTAGE,deleted.PARENTAGE) PARENTAGE,
			COALESCE(inserted.LASTMODIFIEDDATE,deleted.LASTMODIFIEDDATE) LASTMODIFIEDDATE
				   INTO @MERGE_RESULTS;

			/* MERGE command */
			SELECT @MERGED_ROWS = @@ROWCOUNT;

			SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
			(
				SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
				'UPDATE'
				) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
				(
					SELECT MR.ACTIONTYPE,MR.SERIALNUMBER,MR.PARTSEQUENCENUMBER,MR.PARTNUMBER,MR.PARTNAME,MR.PARENTPARTNUMBER,MR.ATTACHMENTSERIALNUMBER,MR.SOURCELOCATION,MR.
					EMDPROCESSEDDATE,MR.ID,MR.PARTORDER,MR.PARTLEVEL,MR.PARENTAGE,MR.LASTMODIFIEDDATE
					FROM @MERGE_RESULTS AS MR FOR JSON AUTO
				) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
			),'Modified Rows');
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
		END;

        EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

        SET @LOGMESSAGE = FORMATMESSAGE('Version before running sproc: %s and after running sproc %s', CAST(@CURRENT_VERSION  as varchar(max)),  CAST(CHANGE_TRACKING_CURRENT_VERSION() as varchar(max)));
        EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = NULL;

		COMMIT;

		Update STATISTICS SISWEB_OWNER.LNKASSHIPPEDPRODUCTDETAILS with fullscan 

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;
GO

