-- =============================================
-- Author:      Nithish
-- Create Date: 20210802
-- Description: Truncates and reloads the table SISWEB_OWNER_SHADOW.LNKEMPPRODUCTINSTANCE_PSID & LNKEMPPRODUCTINSTANCE_LNKMEDIAIEPART
--				
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKEMPPRODUCTINSTANCE_PSID_repopulate (@DEBUG BIT = 'FALSE')
AS
BEGIN
	DECLARE @PROCNAME   VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
		   ,@PROCESSID  UNIQUEIDENTIFIER = NEWID()
		   ,@LOGMESSAGE VARCHAR(MAX)
		   ,@TABLENAME NVARCHAR (50)='LNKEMPPRODUCTINSTANCE_PSID'	
		   ,@dynsql_truncatetable NVARCHAR(256)	
		   ,@dynsql_dropindex NVARCHAR(256)	
		   ,@dynsql_addindex NVARCHAR(256)	
		   ,@CurrentShadowSchema NVARCHAR(256)	
		   ,@CurrentShadowTable NVARCHAR(256);
	DECLARE @ERRORMESSAGE NVARCHAR(4000)
		   ,@ERRORLINE    INT
		   ,@ERRORNUM     INT;

	BEGIN TRY -- Reloads table
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Truncating and Reloading LNKEMPPRODUCTINSTANCE_PSID',
		@DATAVALUE = NULL;

		BEGIN TRANSACTION;

		SELECT @CurrentShadowSchema = ltrim(rtrim(substring(base_object_name,2,charindex('].',base_object_name)-2))),	
		@CurrentShadowTable=ltrim(rtrim(substring(base_object_name,charindex('.',base_object_name)+2,len(base_object_name)-charindex('.',base_object_name)-2)))	
		FROM sys.synonyms 	
		WHERE Schema_id = schema_id('SISWEB_OWNER_SHADOW')	
		And [Name] = @TABLENAME	

		SET @dynsql_truncatetable='TRUNCATE TABLE '+QUOTENAME (@CurrentShadowSchema)+'.'+QUOTENAME(@CurrentShadowTable)	
		EXEC sp_executesql @dynsql_truncatetable	


		set @dynsql_dropindex='DROP INDEX IF EXISTS IX_LNKEMPPRODUCTINSTANCE_PSID_SNP_LANGUAGEINDICATOR_NUMBER ON '+QUOTENAME (@CurrentShadowSchema)+'.'+QUOTENAME(@CurrentShadowTable)+';'	
		EXEC sp_executesql @dynsql_dropindex


		INSERT INTO SISWEB_OWNER_SHADOW.LNKEMPPRODUCTINSTANCE_PSID WITH(TABLOCK)
            SELECT g.SNP, c.LANGUAGEINDICATOR, g.NUMBER, a.MEDIANUMBER, c.PARENTAGE, c.PARENTPRODUCTSTRUCTUREID, c.PRODUCTSTRUCTUREID, COUNT(f.IEPARTNUMBER) AS COUNT, COUNT(f.IEPARTNUMBER) AS PARTNUMBERCOUNT
            FROM SISWEB_OWNER_SHADOW.LNKIEPRODUCTINSTANCE a
                INNER JOIN SISWEB_OWNER_SHADOW.LNKIEPSID b ON a.IESYSTEMCONTROLNUMBER = b.IESYSTEMCONTROLNUMBER AND a.MEDIANUMBER = b.MEDIANUMBER
                INNER JOIN SISWEB_OWNER.MASPRODUCTSTRUCTURE c ON b.PSID = c.PRODUCTSTRUCTUREID
                INNER JOIN SISWEB_OWNER_SHADOW.EMPPRODUCTINSTANCE g ON a.EMPPRODUCTINSTANCE_ID = g.EMPPRODUCTINSTANCE_ID
                LEFT JOIN (
                    sis.vw_LNKIEINFOTYPE_Active d
                    INNER JOIN SISWEB_OWNER_SHADOW.LNKMEDIAIEPART_SNP_TOPLEVEL f ON d.IESYSTEMCONTROLNUMBER = f.IESYSTEMCONTROLNUMBER
                ) ON c.PRODUCTSTRUCTUREID = f.PSID AND a.MEDIANUMBER = f.MEDIANUMBER  AND a.IESYSTEMCONTROLNUMBER = d.IESYSTEMCONTROLNUMBER AND g.SNP = f.SNP
            GROUP BY g.SNP, c.LANGUAGEINDICATOR, g.NUMBER, a.MEDIANUMBER, c.PARENTAGE, c.PARENTPRODUCTSTRUCTUREID, c.PRODUCTSTRUCTUREID

            UNION

            SELECT b.SNP, e.LANGUAGEINDICATOR, b.NUMBER, c.MEDIANUMBER, e.PARENTAGE, e.PARENTPRODUCTSTRUCTUREID, e.PRODUCTSTRUCTUREID, CAST(0 AS INT) AS COUNT, CAST(0 AS INT) AS PARTNUMBERCOUNT
            FROM SISWEB_OWNER_SHADOW.LNKPDFPRODUCTINSTANCE a
                INNER JOIN SISWEB_OWNER_SHADOW.EMPPRODUCTINSTANCE b ON a.EMPPRODUCTINSTANCE_ID = b.EMPPRODUCTINSTANCE_ID
                INNER JOIN SISWEB_OWNER_SHADOW.PARTSPDF c ON a.PARTSPDF_ID = c.PARTSPDF_ID
                INNER JOIN SISWEB_OWNER_SHADOW.LNKPARTSPDFPSID d ON a.PARTSPDF_ID = d.PARTSPDF_ID
                INNER JOIN SISWEB_OWNER.MASPRODUCTSTRUCTURE e ON d.PSID = e.PRODUCTSTRUCTUREID
            GROUP BY b.SNP, e.LANGUAGEINDICATOR, b.NUMBER, c.MEDIANUMBER, e.PARENTAGE, e.PARENTPRODUCTSTRUCTUREID, e.PRODUCTSTRUCTUREID;

			SET @dynsql_addindex='CREATE CLUSTERED INDEX IX_LNKEMPPRODUCTINSTANCE_PSID_SNP_LANGUAGEINDICATOR_NUMBER ON '+QUOTENAME (@CurrentShadowSchema)+'.'+QUOTENAME(@CurrentShadowTable)+' (SNP ASC, LANGUAGEINDICATOR ASC, NUMBER ASC);'	
			EXEC sp_executesql @dynsql_addindex			
		

		COMMIT;

		/* STATS command */
        -- If MS does fix the stats when the table swap then uncomment the below line

        -- EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Updating Statistics',@DATAVALUE = NULL;
		-- UPDATE STATISTICS SISWEB_OWNER_SHADOW.LNKEMPPRODUCTINSTANCE_PSID WITH FULLSCAN;

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		SET @ERRORMESSAGE = ERROR_MESSAGE();
		SET @ERRORLINE = ERROR_LINE();
		SET @ERRORNUM = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
		THROW; --@ERRORNUM,@LOGMESSAGE,1;
	END CATCH;
END;