-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200109
-- Modify Date: 20200123	refactored LASTMODIFIEDDATE
-- Modify Date: 20200205	fixed deadlock error
-- Modify Date: 20201120 - Davide: added UPDATE STATS see: https://dev.azure.com/sis-cat-com/devops-infra/_workitems/edit/86007
-- Description: Conditional load from STAGING LNKIESNP
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKIESNP_Insert_Update_Delete (@FORCE_LOAD BIT = 'FALSE'
																   ,@DEBUG      BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY
		DECLARE @SCHEMANAME sysname = 'SISWEB_OWNER_STAGING'
			   ,@TABLENAME  sysname = 'LNKIESNP';

		DECLARE @FULLTABLENAME   sysname = @SCHEMANAME + '.' + @TABLENAME
			   ,@CURRENT_VERSION BIGINT  = CHANGE_TRACKING_CURRENT_VERSION();

		DECLARE @LAST_SYNCHRONIZATION_VERSION BIGINT           = SISWEB_OWNER_STAGING._getLastSynchVersion (@FULLTABLENAME)
			   ,@RESULT                       BIT
			   ,@ROWCOUNT                     BIGINT
			   ,@MERGED_ROWS                  BIGINT           = 0
			   ,@SYSUTCDATETIME               DATETIME2(6)     = SYSUTCDATETIME()
			   ,@PROCNAME                     VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID                    UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE                   VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE            NVARCHAR(10)
									 ,IESYSTEMCONTROLNUMBER VARCHAR(12) NOT NULL
									 ,SNP                   VARCHAR(10) NOT NULL
									 ,BEGINNINGRANGE        INT NOT NULL
									 ,ENDRANGE              INT NOT NULL
									 ,MEDIANUMBER           VARCHAR(8) NOT NULL
									 ,TYPEINDICATOR         VARCHAR(1) NOT NULL
									 ,PBINDICATOR           VARCHAR(1) NOT NULL
									 ,BASEIERID             NUMERIC(16,0) NULL
									 ,ID                    NUMERIC(38,10) NOT NULL
									 ,LASTMODIFIEDDATE      DATETIME2(6) NULL);

/* 
	Davide 20200205 
	in order to avoid deadlocks errors like: "Transaction (Process ID 246) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.",
	we move the creation of temp table outside the TRANSACTION block, even if it is not extremely elegant
*/
		DROP TABLE IF EXISTS #DIFF_PRIMARY_KEYS;
		SELECT CT.SYS_CHANGE_OPERATION AS OPERATION,CT.ID AS ID,CT.SYS_CHANGE_VERSION AS SYS_CHANGE_VERSION,CT.SYS_CHANGE_COLUMNS AS SYS_CHANGE_COLUMNS
		INTO #DIFF_PRIMARY_KEYS
		FROM CHANGETABLE(CHANGES SISWEB_OWNER_STAGING.LNKIESNP,@LAST_SYNCHRONIZATION_VERSION) AS CT;

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		IF @FORCE_LOAD = 'FALSE'
		BEGIN
			EXEC SISWEB_OWNER_STAGING._getFullOrDiff @SCHEMANAME = @SCHEMANAME,@TABLENAME = @TABLENAME,@CURRENT_VERSION = @CURRENT_VERSION,@DEBUG = @DEBUG,@RESULT = @RESULT OUTPUT
			;

			IF @DEBUG = 'TRUE'
				PRINT FORMATMESSAGE('@RESULT=%s',IIF(@RESULT = 1,'TRUE','FALSE'));

			IF @RESULT = 'TRUE'
			BEGIN
				-- 6. Obtain the changes

				IF @DEBUG = 'TRUE'
					SELECT * FROM #DIFF_PRIMARY_KEYS AS DK;

				-- 7.a Delete if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'D';
				IF @ROWCOUNT > 0
				BEGIN
					DELETE FROM SISWEB_OWNER.LNKIESNP
					OUTPUT 'DELETE' ACTIONTYPE,DELETED.IESYSTEMCONTROLNUMBER,DELETED.SNP,DELETED.BEGINNINGRANGE,DELETED.ENDRANGE,DELETED.MEDIANUMBER,DELETED.TYPEINDICATOR,DELETED.
					PBINDICATOR,DELETED.BASEIERID,DELETED.ID,DELETED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					WHERE EXISTS
					(
						SELECT * FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.ID = LNKIESNP.ID AND 
																	 DK.OPERATION = 'D'
					);

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Deleted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.b Insert if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'I';
				IF @ROWCOUNT > 0
				BEGIN
					INSERT INTO SISWEB_OWNER.LNKIESNP (IESYSTEMCONTROLNUMBER,SNP,BEGINNINGRANGE,ENDRANGE,MEDIANUMBER,TYPEINDICATOR,PBINDICATOR,BASEIERID,ID,LASTMODIFIEDDATE) 
					OUTPUT 'INSERT' ACTIONTYPE,INSERTED.IESYSTEMCONTROLNUMBER,INSERTED.SNP,INSERTED.BEGINNINGRANGE,INSERTED.ENDRANGE,INSERTED.MEDIANUMBER,INSERTED.TYPEINDICATOR,
					INSERTED.PBINDICATOR,INSERTED.BASEIERID,INSERTED.ID,INSERTED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
						   SELECT IESYSTEMCONTROLNUMBER,SNP,BEGINNINGRANGE,ENDRANGE,MEDIANUMBER,TYPEINDICATOR,PBINDICATOR,BASEIERID,ID,@SYSUTCDATETIME
						   FROM SISWEB_OWNER_STAGING.LNKIESNP AS DT
						   WHERE EXISTS
						   (
							   SELECT * FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.ID = DT.ID AND 
																			DK.OPERATION = 'I'
						   );

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Inserted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.c Update if needed
				SELECT @ROWCOUNT = COUNT(*)
				FROM #DIFF_PRIMARY_KEYS AS DK
				WHERE DK.OPERATION = 'U' AND 
					  (-- if the modified column is LASTMODIFIEDDATE ignore the update 
					  DK.SYS_CHANGE_COLUMNS <> 0x000000000A000000 OR 
					  DK.SYS_CHANGE_COLUMNS IS NULL
					  );
				IF @ROWCOUNT > 0
				BEGIN
					UPDATE SISWEB_OWNER.LNKIESNP
					  SET IESYSTEMCONTROLNUMBER = ST.IESYSTEMCONTROLNUMBER,SNP = ST.SNP,BEGINNINGRANGE = ST.BEGINNINGRANGE,ENDRANGE = ST.ENDRANGE,MEDIANUMBER = ST.MEDIANUMBER,
					  TYPEINDICATOR = ST.TYPEINDICATOR,PBINDICATOR = ST.PBINDICATOR,BASEIERID = ST.BASEIERID,LASTMODIFIEDDATE = @SYSUTCDATETIME
					OUTPUT 'UPDATE' ACTIONTYPE,INSERTED.IESYSTEMCONTROLNUMBER,INSERTED.SNP,INSERTED.BEGINNINGRANGE,INSERTED.ENDRANGE,INSERTED.MEDIANUMBER,INSERTED.TYPEINDICATOR,
					INSERTED.PBINDICATOR,INSERTED.BASEIERID,INSERTED.ID,INSERTED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					FROM SISWEB_OWNER_STAGING.LNKIESNP AS ST
						 JOIN SISWEB_OWNER.LNKIESNP AS TT ON ST.ID = TT.ID
					WHERE EXISTS
					(
						SELECT * FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.ID = ST.ID AND 
																	 DK.OPERATION = 'U'
					);
					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Updated %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 8. Store current version to be used the next time
				IF @DEBUG = 'TRUE'
					SELECT * FROM @MERGE_RESULTS AS MR;

				EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

				SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
				(
					SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
					'UPDATE'
					) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
					(
						SELECT MR.ACTIONTYPE,MR.IESYSTEMCONTROLNUMBER,MR.SNP,MR.BEGINNINGRANGE,MR.ENDRANGE,MR.MEDIANUMBER,MR.TYPEINDICATOR,MR.PBINDICATOR,MR.BASEIERID,MR.ID,MR.
						LASTMODIFIEDDATE
						FROM @MERGE_RESULTS AS MR FOR JSON AUTO
					) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
				),'Modified Rows');
				EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
			END;
		END;

		/* to be done: handle full load with MERGE */
		IF @FORCE_LOAD = 'TRUE'
		--   OR @MODIFIED_ROWS_PERCENTAGE BETWEEN-0.10 AND 0.10
		BEGIN
			SET @LOGMESSAGE = 'Executing load: Force Load = TRUE';
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @FORCE_LOAD;

			/* MERGE command */
			MERGE INTO SISWEB_OWNER.LNKIESNP tgt
			USING SISWEB_OWNER_STAGING.LNKIESNP src
			ON src.ID = tgt.ID
			WHEN MATCHED AND EXISTS
			(
				SELECT src.IESYSTEMCONTROLNUMBER,src.SNP,src.BEGINNINGRANGE,src.ENDRANGE,src.MEDIANUMBER,src.TYPEINDICATOR,src.PBINDICATOR,src.BASEIERID
				EXCEPT
				SELECT tgt.IESYSTEMCONTROLNUMBER,tgt.SNP,tgt.BEGINNINGRANGE,tgt.ENDRANGE,tgt.MEDIANUMBER,tgt.TYPEINDICATOR,tgt.PBINDICATOR,tgt.BASEIERID
			)
				  THEN UPDATE SET tgt.IESYSTEMCONTROLNUMBER = src.IESYSTEMCONTROLNUMBER,tgt.SNP = src.SNP,tgt.BEGINNINGRANGE = src.BEGINNINGRANGE,tgt.ENDRANGE = src.ENDRANGE,tgt.
				  MEDIANUMBER = src.MEDIANUMBER,tgt.TYPEINDICATOR = src.TYPEINDICATOR,tgt.PBINDICATOR = src.PBINDICATOR,tgt.BASEIERID = src.BASEIERID,tgt.LASTMODIFIEDDATE =
				  @SYSUTCDATETIME
			WHEN NOT MATCHED BY TARGET
				  THEN
				  INSERT(IESYSTEMCONTROLNUMBER,SNP,BEGINNINGRANGE,ENDRANGE,MEDIANUMBER,TYPEINDICATOR,PBINDICATOR,BASEIERID,ID,LASTMODIFIEDDATE)
				  VALUES (src.IESYSTEMCONTROLNUMBER,src.SNP,src.BEGINNINGRANGE,src.ENDRANGE,src.MEDIANUMBER,src.TYPEINDICATOR,src.PBINDICATOR,src.BASEIERID,src.ID,@SYSUTCDATETIME) 
			WHEN NOT MATCHED BY SOURCE
				  THEN DELETE
			OUTPUT $ACTION,COALESCE(inserted.IESYSTEMCONTROLNUMBER,deleted.IESYSTEMCONTROLNUMBER) IESYSTEMCONTROLNUMBER,COALESCE(inserted.SNP,deleted.SNP) SNP,COALESCE(inserted.
			BEGINNINGRANGE,deleted.BEGINNINGRANGE) BEGINNINGRANGE,COALESCE(inserted.ENDRANGE,deleted.ENDRANGE) ENDRANGE,COALESCE(inserted.MEDIANUMBER,deleted.MEDIANUMBER)
			MEDIANUMBER,COALESCE(inserted.TYPEINDICATOR,deleted.TYPEINDICATOR) TYPEINDICATOR,COALESCE(inserted.PBINDICATOR,deleted.PBINDICATOR) PBINDICATOR,COALESCE(inserted.
			BASEIERID,deleted.BASEIERID) BASEIERID,COALESCE(inserted.ID,deleted.ID) ID,COALESCE(inserted.LASTMODIFIEDDATE,deleted.LASTMODIFIEDDATE) LASTMODIFIEDDATE
				   INTO @MERGE_RESULTS;

			/* MERGE command */
			SELECT @MERGED_ROWS = @@ROWCOUNT;

			EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

			SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
			(
				SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
				'UPDATE'
				) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
				(
					SELECT MR.ACTIONTYPE,MR.IESYSTEMCONTROLNUMBER,MR.SNP,MR.BEGINNINGRANGE,MR.ENDRANGE,MR.MEDIANUMBER,MR.TYPEINDICATOR,MR.PBINDICATOR,MR.BASEIERID,MR.ID,MR.
					LASTMODIFIEDDATE
					FROM @MERGE_RESULTS AS MR FOR JSON AUTO
				) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
			),'Modified Rows');
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
		END;

		COMMIT;
						UPDATE STATISTICS SISWEB_OWNER.LNKIESNP WITH FULLSCAN;

		/* STATS command */
		SET @LOGMESSAGE = 'Updating Statistics';
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = NULL;
		UPDATE STATISTICS SISWEB_OWNER.LNKIESNP WITH FULLSCAN;

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;
GO

