
-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200109
-- Modify Date: 20200122	refactored LASTMODIFIEDDATE
-- Modify Date: 20200205	fixed deadlock error
-- Description: Conditional load from STAGING LNKIESMCS
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKIESMCS_Insert_Update_Delete (@FORCE_LOAD BIT = 'FALSE'
																	 ,@DEBUG      BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY
		DECLARE @SCHEMANAME sysname = 'SISWEB_OWNER_STAGING'
			   ,@TABLENAME  sysname = 'LNKIESMCS';

		DECLARE @FULLTABLENAME   sysname = @SCHEMANAME + '.' + @TABLENAME
			   ,@CURRENT_VERSION BIGINT  = CHANGE_TRACKING_CURRENT_VERSION();

		DECLARE @LAST_SYNCHRONIZATION_VERSION BIGINT           = SISWEB_OWNER_STAGING._getLastSynchVersion (@FULLTABLENAME)
			   ,@RESULT                       BIT
			   ,@ROWCOUNT                     BIGINT
			   ,@MERGED_ROWS                  BIGINT           = 0
			   ,@SYSUTCDATETIME               DATETIME2(6)     = SYSUTCDATETIME()
			   ,@PROCNAME                     VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID                    UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE                   VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE            NVARCHAR(10)
									 ,MEDIANUMBER           VARCHAR(8) NOT NULL
									 ,IESYSTEMCONTROLNUMBER VARCHAR(12) NOT NULL
									 ,SMCSCOMPCODE          VARCHAR(4) NOT NULL
									 ,SMCSJOBCODE           VARCHAR(3) NOT NULL
									 ,SMCSMODCODE           VARCHAR(3) NOT NULL
									 ,SMCSTOOLCODE          VARCHAR(4) NOT NULL
									 ,BASEIERID             NUMERIC(16,0) NULL
									 ,LASTMODIFIEDDATE      DATETIME2(6) NULL);

/* 
	Davide 20200205 
	in order to avoid deadlocks errors like: "Transaction (Process ID 246) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.",
	we move the creation of temp table outside the TRANSACTION block, even if it is not extremely elegant
*/
		DROP TABLE IF EXISTS #DIFF_PRIMARY_KEYS;
		SELECT CT.SYS_CHANGE_OPERATION AS OPERATION,CT.MEDIANUMBER AS MEDIANUMBER,CT.IESYSTEMCONTROLNUMBER AS IESYSTEMCONTROLNUMBER,CT.SMCSCOMPCODE AS SMCSCOMPCODE,CT.SMCSJOBCODE
		AS SMCSJOBCODE,CT.SMCSMODCODE AS SMCSMODCODE,CT.SMCSTOOLCODE AS SMCSTOOLCODE,CT.SYS_CHANGE_VERSION AS SYS_CHANGE_VERSION,CT.SYS_CHANGE_COLUMNS AS SYS_CHANGE_COLUMNS
		INTO #DIFF_PRIMARY_KEYS
		FROM CHANGETABLE(CHANGES SISWEB_OWNER_STAGING.LNKIESMCS,@LAST_SYNCHRONIZATION_VERSION) AS CT;

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		IF @FORCE_LOAD = 'FALSE'
		BEGIN
			EXEC SISWEB_OWNER_STAGING._getFullOrDiff @SCHEMANAME = @SCHEMANAME,@TABLENAME = @TABLENAME,@CURRENT_VERSION = @CURRENT_VERSION,@DEBUG = @DEBUG,@RESULT = @RESULT OUTPUT
			;

			IF @DEBUG = 'TRUE'
				PRINT FORMATMESSAGE('@RESULT=%s',IIF(@RESULT = 1,'TRUE','FALSE'));

			IF @RESULT = 'TRUE'
			BEGIN
				-- 6. Obtain the changes

				IF @DEBUG = 'TRUE'
					SELECT * FROM #DIFF_PRIMARY_KEYS AS DK;

				-- 7.a Delete if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'D';
				IF @ROWCOUNT > 0
				BEGIN
					DELETE FROM SISWEB_OWNER.LNKIESMCS
					OUTPUT 'DELETE' ACTIONTYPE,DELETED.MEDIANUMBER,DELETED.IESYSTEMCONTROLNUMBER,DELETED.SMCSCOMPCODE,DELETED.SMCSJOBCODE,DELETED.SMCSMODCODE,DELETED.SMCSTOOLCODE,
					DELETED.BASEIERID,DELETED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.MEDIANUMBER = LNKIESMCS.MEDIANUMBER AND 
							  DK.IESYSTEMCONTROLNUMBER = LNKIESMCS.IESYSTEMCONTROLNUMBER AND 
							  DK.SMCSCOMPCODE = LNKIESMCS.SMCSCOMPCODE AND 
							  DK.SMCSJOBCODE = LNKIESMCS.SMCSJOBCODE AND 
							  DK.SMCSMODCODE = LNKIESMCS.SMCSMODCODE AND 
							  DK.SMCSTOOLCODE = LNKIESMCS.SMCSTOOLCODE AND 
							  DK.OPERATION = 'D'
					);

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Deleted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.b Insert if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'I';
				IF @ROWCOUNT > 0
				BEGIN
					INSERT INTO SISWEB_OWNER.LNKIESMCS (MEDIANUMBER,IESYSTEMCONTROLNUMBER,SMCSCOMPCODE,SMCSJOBCODE,SMCSMODCODE,SMCSTOOLCODE,BASEIERID,LASTMODIFIEDDATE) 
					OUTPUT 'INSERT' ACTIONTYPE,INSERTED.MEDIANUMBER,INSERTED.IESYSTEMCONTROLNUMBER,INSERTED.SMCSCOMPCODE,INSERTED.SMCSJOBCODE,INSERTED.SMCSMODCODE,INSERTED.
					SMCSTOOLCODE,INSERTED.BASEIERID,INSERTED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
						   SELECT MEDIANUMBER,IESYSTEMCONTROLNUMBER,SMCSCOMPCODE,SMCSJOBCODE,SMCSMODCODE,SMCSTOOLCODE,BASEIERID,@SYSUTCDATETIME
						   FROM SISWEB_OWNER_STAGING.LNKIESMCS AS DT
						   WHERE EXISTS
						   (
							   SELECT *
							   FROM #DIFF_PRIMARY_KEYS AS DK
							   WHERE DK.MEDIANUMBER = DT.MEDIANUMBER AND 
									 DK.IESYSTEMCONTROLNUMBER = DT.IESYSTEMCONTROLNUMBER AND 
									 DK.SMCSCOMPCODE = DT.SMCSCOMPCODE AND 
									 DK.SMCSJOBCODE = DT.SMCSJOBCODE AND 
									 DK.SMCSMODCODE = DT.SMCSMODCODE AND 
									 DK.SMCSTOOLCODE = DT.SMCSTOOLCODE AND 
									 DK.OPERATION = 'I'
						   );

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Inserted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.c Update if needed
				SELECT @ROWCOUNT = COUNT(*)
				FROM #DIFF_PRIMARY_KEYS AS DK
				WHERE DK.OPERATION = 'U' AND 
					  (-- if the modified column is LASTMODIFIEDDATE ignore the update 
					  DK.SYS_CHANGE_COLUMNS <> 0x0000000007000000 OR 
					  DK.SYS_CHANGE_COLUMNS IS NULL
					  );
				IF @ROWCOUNT > 0
				BEGIN
					UPDATE SISWEB_OWNER.LNKIESMCS
					  SET BASEIERID = ST.BASEIERID,LASTMODIFIEDDATE = @SYSUTCDATETIME
					OUTPUT 'UPDATE' ACTIONTYPE,INSERTED.MEDIANUMBER,INSERTED.IESYSTEMCONTROLNUMBER,INSERTED.SMCSCOMPCODE,INSERTED.SMCSJOBCODE,INSERTED.SMCSMODCODE,INSERTED.
					SMCSTOOLCODE,INSERTED.BASEIERID,INSERTED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					FROM SISWEB_OWNER_STAGING.LNKIESMCS AS ST
						 JOIN SISWEB_OWNER.LNKIESMCS AS TT ON ST.MEDIANUMBER = TT.MEDIANUMBER AND 
															  ST.IESYSTEMCONTROLNUMBER = TT.IESYSTEMCONTROLNUMBER AND 
															  ST.SMCSCOMPCODE = TT.SMCSCOMPCODE AND 
															  ST.SMCSJOBCODE = TT.SMCSJOBCODE AND 
															  ST.SMCSMODCODE = TT.SMCSMODCODE AND 
															  ST.SMCSTOOLCODE = TT.SMCSTOOLCODE
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.MEDIANUMBER = ST.MEDIANUMBER AND 
							  DK.IESYSTEMCONTROLNUMBER = ST.IESYSTEMCONTROLNUMBER AND 
							  DK.SMCSCOMPCODE = ST.SMCSCOMPCODE AND 
							  DK.SMCSJOBCODE = ST.SMCSJOBCODE AND 
							  DK.SMCSMODCODE = ST.SMCSMODCODE AND 
							  DK.SMCSTOOLCODE = ST.SMCSTOOLCODE AND 
							  DK.OPERATION = 'U'
					);
					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Updated %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 8. Store current version to be used the next time
				IF @DEBUG = 'TRUE'
					SELECT * FROM @MERGE_RESULTS AS MR;

				EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

				SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
				(
					SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
					'UPDATE'
					) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
					(
						SELECT MR.ACTIONTYPE,MR.MEDIANUMBER,MR.IESYSTEMCONTROLNUMBER,MR.SMCSCOMPCODE,MR.SMCSJOBCODE,MR.SMCSMODCODE,MR.SMCSTOOLCODE,MR.BASEIERID,MR.LASTMODIFIEDDATE
						FROM @MERGE_RESULTS AS MR FOR JSON AUTO
					) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
				),'Modified Rows');
				EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
			END;
		END;

		/* to be done: handle full load with MERGE */
		IF @FORCE_LOAD = 'TRUE'
		--   OR @MODIFIED_ROWS_PERCENTAGE BETWEEN-0.10 AND 0.10
		BEGIN
			SET @LOGMESSAGE = 'Executing load: Force Load = TRUE';
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @FORCE_LOAD;

			/* MERGE command */
			MERGE INTO SISWEB_OWNER.LNKIESMCS tgt
			USING SISWEB_OWNER_STAGING.LNKIESMCS src
			ON src.MEDIANUMBER = tgt.MEDIANUMBER AND 
			   src.IESYSTEMCONTROLNUMBER = tgt.IESYSTEMCONTROLNUMBER AND 
			   src.SMCSCOMPCODE = tgt.SMCSCOMPCODE AND 
			   src.SMCSJOBCODE = tgt.SMCSJOBCODE AND 
			   src.SMCSMODCODE = tgt.SMCSMODCODE AND 
			   src.SMCSTOOLCODE = tgt.SMCSTOOLCODE
			WHEN MATCHED AND EXISTS
			(
				SELECT src.BASEIERID
				EXCEPT
				SELECT tgt.BASEIERID
			)
				  THEN UPDATE SET tgt.BASEIERID = src.BASEIERID,tgt.LASTMODIFIEDDATE = @SYSUTCDATETIME
			WHEN NOT MATCHED BY TARGET
				  THEN
				  INSERT(MEDIANUMBER,IESYSTEMCONTROLNUMBER,SMCSCOMPCODE,SMCSJOBCODE,SMCSMODCODE,SMCSTOOLCODE,BASEIERID,LASTMODIFIEDDATE)
				  VALUES (src.MEDIANUMBER,src.IESYSTEMCONTROLNUMBER,src.SMCSCOMPCODE,src.SMCSJOBCODE,src.SMCSMODCODE,src.SMCSTOOLCODE,src.BASEIERID,@SYSUTCDATETIME) 
			WHEN NOT MATCHED BY SOURCE
				  THEN DELETE
			OUTPUT $ACTION,COALESCE(inserted.MEDIANUMBER,deleted.MEDIANUMBER) MEDIANUMBER,COALESCE(inserted.IESYSTEMCONTROLNUMBER,deleted.IESYSTEMCONTROLNUMBER)
			IESYSTEMCONTROLNUMBER,COALESCE(inserted.SMCSCOMPCODE,deleted.SMCSCOMPCODE) SMCSCOMPCODE,COALESCE(inserted.SMCSJOBCODE,deleted.SMCSJOBCODE) SMCSJOBCODE,COALESCE(
			inserted.SMCSMODCODE,deleted.SMCSMODCODE) SMCSMODCODE,COALESCE(inserted.SMCSTOOLCODE,deleted.SMCSTOOLCODE) SMCSTOOLCODE,COALESCE(inserted.BASEIERID,deleted.BASEIERID)
			BASEIERID,COALESCE(inserted.LASTMODIFIEDDATE,deleted.LASTMODIFIEDDATE) LASTMODIFIEDDATE
				   INTO @MERGE_RESULTS;

			/* MERGE command */
			SELECT @MERGED_ROWS = @@ROWCOUNT;

			EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

			SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
			(
				SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
				'UPDATE'
				) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
				(
					SELECT MR.ACTIONTYPE,MR.MEDIANUMBER,MR.IESYSTEMCONTROLNUMBER,MR.SMCSCOMPCODE,MR.SMCSJOBCODE,MR.SMCSMODCODE,MR.SMCSTOOLCODE,MR.BASEIERID,MR.LASTMODIFIEDDATE
					FROM @MERGE_RESULTS AS MR FOR JSON AUTO
				) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
			),'Modified Rows');
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
		END;

		COMMIT;

								UPDATE STATISTICS SISWEB_OWNER.LNKIESMCS WITH FULLSCAN;

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;
GO

