
-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200109
-- Modify Date: 20200123
-- Modify Date: 20200205	fixed deadlock error
-- Description: Conditional load from STAGING LNKIETITLE
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKIETITLE_Insert_Update_Delete (@FORCE_LOAD BIT = 'FALSE'
																	  ,@DEBUG      BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY
		DECLARE @SCHEMANAME sysname = 'SISWEB_OWNER_STAGING'
			   ,@TABLENAME  sysname = 'LNKIETITLE';

		DECLARE @FULLTABLENAME   sysname = @SCHEMANAME + '.' + @TABLENAME
			   ,@CURRENT_VERSION BIGINT  = CHANGE_TRACKING_CURRENT_VERSION();

		DECLARE @LAST_SYNCHRONIZATION_VERSION BIGINT           = SISWEB_OWNER_STAGING._getLastSynchVersion (@FULLTABLENAME)
			   ,@RESULT                       BIT
			   ,@ROWCOUNT                     BIGINT
			   ,@MERGED_ROWS                  BIGINT           = 0
			   ,@SYSUTCDATETIME               DATETIME2(6)     = SYSUTCDATETIME()
			   ,@PROCNAME                     VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID                    UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE                   VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE            NVARCHAR(10)
									 ,IESYSTEMCONTROLNUMBER VARCHAR(12) NOT NULL
									 ,IELANGUAGEINDICATOR   VARCHAR(2) NOT NULL
									 ,IETITLE               NVARCHAR(3072) NOT NULL
									 ,IECONTROLNUMBER       VARCHAR(12) NULL
									 ,IERID                 NUMERIC(16,0) NULL
									 ,GROUPTITLEINDICATOR   VARCHAR(1) NULL
									 ,LASTMODIFIEDDATE      DATETIME2(6) NULL
									 ,ENGLISHCONTROLNUMBER VARCHAR(12) NULL);

/* 
	Davide 20200205 
	in order to avoid deadlocks errors like: "Transaction (Process ID 246) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.",
	we move the creation of temp table outside the TRANSACTION block, even if it is not extremely elegant
*/
		DROP TABLE IF EXISTS #DIFF_PRIMARY_KEYS;
		SELECT CT.SYS_CHANGE_OPERATION AS OPERATION,CT.IESYSTEMCONTROLNUMBER AS IESYSTEMCONTROLNUMBER,CT.IELANGUAGEINDICATOR AS IELANGUAGEINDICATOR,CT.SYS_CHANGE_VERSION AS
		SYS_CHANGE_VERSION,CT.SYS_CHANGE_COLUMNS AS SYS_CHANGE_COLUMNS
		INTO #DIFF_PRIMARY_KEYS
		FROM CHANGETABLE(CHANGES SISWEB_OWNER_STAGING.LNKIETITLE,@LAST_SYNCHRONIZATION_VERSION) AS CT;

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		IF @FORCE_LOAD = 'FALSE'
		BEGIN
			EXEC SISWEB_OWNER_STAGING._getFullOrDiff @SCHEMANAME = @SCHEMANAME,@TABLENAME = @TABLENAME,@CURRENT_VERSION = @CURRENT_VERSION,@DEBUG = @DEBUG,@RESULT = @RESULT OUTPUT
			;

			IF @DEBUG = 'TRUE'
				PRINT FORMATMESSAGE('@RESULT=%s',IIF(@RESULT = 1,'TRUE','FALSE'));

			IF @RESULT = 'TRUE'
			BEGIN
				-- 6. Obtain the changes

				IF @DEBUG = 'TRUE'
					SELECT * FROM #DIFF_PRIMARY_KEYS AS DK;

				-- 7.a Delete if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'D';
				IF @ROWCOUNT > 0
				BEGIN
					DELETE FROM SISWEB_OWNER.LNKIETITLE
					OUTPUT 'DELETE' ACTIONTYPE,DELETED.IESYSTEMCONTROLNUMBER,DELETED.IELANGUAGEINDICATOR,DELETED.IETITLE,DELETED.IECONTROLNUMBER,DELETED.IERID,DELETED.
					GROUPTITLEINDICATOR,DELETED.LASTMODIFIEDDATE,DELETED.ENGLISHCONTROLNUMBER
						   INTO @MERGE_RESULTS
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.IESYSTEMCONTROLNUMBER = LNKIETITLE.IESYSTEMCONTROLNUMBER AND 
							  DK.IELANGUAGEINDICATOR = LNKIETITLE.IELANGUAGEINDICATOR AND 
							  DK.OPERATION = 'D'
					);

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Deleted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.b Insert if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'I';
				IF @ROWCOUNT > 0
				BEGIN
					INSERT INTO SISWEB_OWNER.LNKIETITLE (IESYSTEMCONTROLNUMBER,IELANGUAGEINDICATOR,IETITLE,IECONTROLNUMBER,IERID,GROUPTITLEINDICATOR,LASTMODIFIEDDATE,ENGLISHCONTROLNUMBER) 
					OUTPUT 'INSERT' ACTIONTYPE,INSERTED.IESYSTEMCONTROLNUMBER,INSERTED.IELANGUAGEINDICATOR,INSERTED.IETITLE,INSERTED.IECONTROLNUMBER,INSERTED.IERID,INSERTED.
					GROUPTITLEINDICATOR,INSERTED.LASTMODIFIEDDATE,INSERTED.ENGLISHCONTROLNUMBER 
						   INTO @MERGE_RESULTS
						   SELECT IESYSTEMCONTROLNUMBER,IELANGUAGEINDICATOR,IETITLE,IECONTROLNUMBER,IERID,GROUPTITLEINDICATOR,@SYSUTCDATETIME,ENGLISHCONTROLNUMBER
						   FROM SISWEB_OWNER_STAGING.LNKIETITLE AS DT
						   WHERE EXISTS
						   (
							   SELECT *
							   FROM #DIFF_PRIMARY_KEYS AS DK
							   WHERE DK.IESYSTEMCONTROLNUMBER = DT.IESYSTEMCONTROLNUMBER AND 
									 DK.IELANGUAGEINDICATOR = DT.IELANGUAGEINDICATOR AND 
									 DK.OPERATION = 'I'
						   );

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Inserted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.c Update if needed
				SELECT @ROWCOUNT = COUNT(*)
				FROM #DIFF_PRIMARY_KEYS AS DK
				WHERE DK.OPERATION = 'U' AND 
					  (-- if the modified column is LASTMODIFIEDDATE ignore the update 
					  DK.SYS_CHANGE_COLUMNS <> 0x0000000007000000 OR 
					  DK.SYS_CHANGE_COLUMNS IS NULL
					  );
				IF @ROWCOUNT > 0
				BEGIN
					UPDATE SISWEB_OWNER.LNKIETITLE
					  SET IETITLE = ST.IETITLE,IECONTROLNUMBER = ST.IECONTROLNUMBER,IERID = ST.IERID,GROUPTITLEINDICATOR = ST.GROUPTITLEINDICATOR,LASTMODIFIEDDATE =
					  @SYSUTCDATETIME,ENGLISHCONTROLNUMBER = ST.ENGLISHCONTROLNUMBER
					OUTPUT 'UPDATE' ACTIONTYPE,INSERTED.IESYSTEMCONTROLNUMBER,INSERTED.IELANGUAGEINDICATOR,INSERTED.IETITLE,INSERTED.IECONTROLNUMBER,INSERTED.IERID,INSERTED.
					GROUPTITLEINDICATOR,INSERTED.LASTMODIFIEDDATE, INSERTED.ENGLISHCONTROLNUMBER
						   INTO @MERGE_RESULTS
					FROM SISWEB_OWNER_STAGING.LNKIETITLE AS ST
						 JOIN SISWEB_OWNER.LNKIETITLE AS TT ON ST.IESYSTEMCONTROLNUMBER = TT.IESYSTEMCONTROLNUMBER AND 
															   ST.IELANGUAGEINDICATOR = TT.IELANGUAGEINDICATOR
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.IESYSTEMCONTROLNUMBER = ST.IESYSTEMCONTROLNUMBER AND 
							  DK.IELANGUAGEINDICATOR = ST.IELANGUAGEINDICATOR AND 
							  DK.OPERATION = 'U'
					);
					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Updated %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 8. Store current version to be used the next time
				IF @DEBUG = 'TRUE'
					SELECT * FROM @MERGE_RESULTS AS MR;

				EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

				SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
				(
					SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
					'UPDATE'
					) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
					(
						SELECT MR.ACTIONTYPE,MR.IESYSTEMCONTROLNUMBER,MR.IELANGUAGEINDICATOR,MR.IETITLE,MR.IECONTROLNUMBER,MR.IERID,MR.GROUPTITLEINDICATOR,MR.LASTMODIFIEDDATE,MR.ENGLISHCONTROLNUMBER
						FROM @MERGE_RESULTS AS MR FOR JSON AUTO
					) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
				),'Modified Rows');
				EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
			END;
		END;

		/* to be done: handle full load with MERGE */
		IF @FORCE_LOAD = 'TRUE'
		--   OR @MODIFIED_ROWS_PERCENTAGE BETWEEN-0.10 AND 0.10
		BEGIN
			SET @LOGMESSAGE = 'Executing load: Force Load = TRUE';
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @FORCE_LOAD;

			/* MERGE command */
			MERGE INTO SISWEB_OWNER.LNKIETITLE tgt
			USING SISWEB_OWNER_STAGING.LNKIETITLE src
			ON src.IESYSTEMCONTROLNUMBER = tgt.IESYSTEMCONTROLNUMBER AND 
			   src.IELANGUAGEINDICATOR = tgt.IELANGUAGEINDICATOR
			WHEN MATCHED AND EXISTS
			(
				SELECT src.IETITLE,src.IECONTROLNUMBER,src.IERID,src.GROUPTITLEINDICATOR
				EXCEPT
				SELECT tgt.IETITLE,tgt.IECONTROLNUMBER,tgt.IERID,tgt.GROUPTITLEINDICATOR
			)
				  THEN UPDATE SET tgt.IETITLE = src.IETITLE,tgt.IECONTROLNUMBER = src.IECONTROLNUMBER,tgt.IERID = src.IERID,tgt.GROUPTITLEINDICATOR = src.GROUPTITLEINDICATOR,tgt.
				  LASTMODIFIEDDATE = @SYSUTCDATETIME,tgt.ENGLISHCONTROLNUMBER=src.ENGLISHCONTROLNUMBER
			WHEN NOT MATCHED BY TARGET
				  THEN
				  INSERT(IESYSTEMCONTROLNUMBER,IELANGUAGEINDICATOR,IETITLE,IECONTROLNUMBER,IERID,GROUPTITLEINDICATOR,LASTMODIFIEDDATE,ENGLISHCONTROLNUMBER)
				  VALUES (src.IESYSTEMCONTROLNUMBER,src.IELANGUAGEINDICATOR,src.IETITLE,src.IECONTROLNUMBER,src.IERID,src.GROUPTITLEINDICATOR,@SYSUTCDATETIME,src.ENGLISHCONTROLNUMBER) 
			WHEN NOT MATCHED BY SOURCE
				  THEN DELETE
			OUTPUT $ACTION,COALESCE(inserted.IESYSTEMCONTROLNUMBER,deleted.IESYSTEMCONTROLNUMBER) IESYSTEMCONTROLNUMBER,COALESCE(inserted.IELANGUAGEINDICATOR,deleted.
			IELANGUAGEINDICATOR) IELANGUAGEINDICATOR,COALESCE(inserted.IETITLE,deleted.IETITLE) IETITLE,COALESCE(inserted.IECONTROLNUMBER,deleted.IECONTROLNUMBER) IECONTROLNUMBER,
			COALESCE(inserted.IERID,deleted.IERID) IERID,COALESCE(inserted.GROUPTITLEINDICATOR,deleted.GROUPTITLEINDICATOR) GROUPTITLEINDICATOR,COALESCE(inserted.LASTMODIFIEDDATE,
			deleted.LASTMODIFIEDDATE) LASTMODIFIEDDATE,COALESCE(inserted.ENGLISHCONTROLNUMBER,deleted.ENGLISHCONTROLNUMBER) ENGLISHCONTROLNUMBER
				   INTO @MERGE_RESULTS;

			/* MERGE command */
			SELECT @MERGED_ROWS = @@ROWCOUNT;

			EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

			SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
			(
				SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
				'UPDATE'
				) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
				(
					SELECT MR.ACTIONTYPE,MR.IESYSTEMCONTROLNUMBER,MR.IELANGUAGEINDICATOR,MR.IETITLE,MR.IECONTROLNUMBER,MR.IERID,MR.GROUPTITLEINDICATOR,MR.LASTMODIFIEDDATE,MR.ENGLISHCONTROLNUMBER
					FROM @MERGE_RESULTS AS MR FOR JSON AUTO
				) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
			),'Modified Rows');
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
		END;

		COMMIT;

								UPDATE STATISTICS SISWEB_OWNER.LNKIETITLE WITH FULLSCAN;

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;
GO

