
-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200422
-- Description: Sync back data from SISWEB_OWNER to SHADOW LNKMEDIAIEPART
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKMEDIAIEPART_Refresh_SHADOW_Table (@DEBUG BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY

		DECLARE @MERGED_ROWS BIGINT           = 0
			   ,@PROCNAME    VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID   UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE  VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE              NVARCHAR(10)
									 ,MEDIANUMBER             VARCHAR(8) NOT NULL
									 ,IESYSTEMCONTROLNUMBER   VARCHAR(12) NOT NULL
									 ,IEPARTNUMBER            VARCHAR(40) NULL
									 ,ORGCODE                 VARCHAR(12) NULL
									 ,IEPARTNAME              NVARCHAR(128) NULL
									 ,IESEQUENCENUMBER        INT NOT NULL
									 ,BASEENGCONTROLNO        VARCHAR(12) NOT NULL
									 ,SECTIONNUMBER           INT NOT NULL
									 ,IEPARTMODIFIER          NVARCHAR(512) NULL
									 ,IECAPTION               NVARCHAR(2048) NOT NULL
									 ,IETYPE                  VARCHAR(1) NOT NULL
									 ,SERVICEABILITYINDICATOR VARCHAR(1) NOT NULL
									 ,IEUPDATEDATE            DATETIME2(0) NOT NULL
									 ,IECONTROLNUMBER         VARCHAR(25) NULL
									 ,PART                    VARCHAR(2) NULL
									 ,OFPARTS                 VARCHAR(2) NULL
									 ,ARRANGEMENTINDICATOR    VARCHAR(1) NOT NULL
									 ,CCRINDICATOR            VARCHAR(1) NOT NULL
									 ,FILTERPARTINDICATOR     VARCHAR(1) NOT NULL
									 ,MAINTPARTINDICATOR      VARCHAR(1) NOT NULL
									 ,NPRINDICATOR            VARCHAR(1) NULL
									 ,TYPECHANGEINDICATOR     VARCHAR(1) NULL
									 ,LASTMODIFIEDDATE        VARCHAR(50) NULL);

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		/* MERGE command */
		MERGE INTO SISWEB_OWNER_SHADOW.LNKMEDIAIEPART tgt
		USING SISWEB_OWNER.LNKMEDIAIEPART src
		ON src.MEDIANUMBER = tgt.MEDIANUMBER AND 
		   src.IESYSTEMCONTROLNUMBER = tgt.IESYSTEMCONTROLNUMBER
		WHEN MATCHED AND EXISTS
		(
			SELECT src.IEPARTNUMBER,src.ORGCODE,src.IEPARTNAME,src.IESEQUENCENUMBER,src.BASEENGCONTROLNO,src.SECTIONNUMBER,src.IEPARTMODIFIER,src.IECAPTION,src.IETYPE,src.
			SERVICEABILITYINDICATOR,src.IEUPDATEDATE,src.IECONTROLNUMBER,src.PART,src.OFPARTS,src.ARRANGEMENTINDICATOR,src.CCRINDICATOR,src.FILTERPARTINDICATOR,src.
			MAINTPARTINDICATOR,src.NPRINDICATOR,src.TYPECHANGEINDICATOR
			EXCEPT
			SELECT tgt.IEPARTNUMBER,tgt.ORGCODE,tgt.IEPARTNAME,tgt.IESEQUENCENUMBER,tgt.BASEENGCONTROLNO,tgt.SECTIONNUMBER,tgt.IEPARTMODIFIER,tgt.IECAPTION,tgt.IETYPE,tgt.
			SERVICEABILITYINDICATOR,tgt.IEUPDATEDATE,tgt.IECONTROLNUMBER,tgt.PART,tgt.OFPARTS,tgt.ARRANGEMENTINDICATOR,tgt.CCRINDICATOR,tgt.FILTERPARTINDICATOR,tgt.
			MAINTPARTINDICATOR,tgt.NPRINDICATOR,tgt.TYPECHANGEINDICATOR
		)
			  THEN UPDATE SET tgt.IEPARTNUMBER = src.IEPARTNUMBER,tgt.ORGCODE = src.ORGCODE,tgt.IEPARTNAME = src.IEPARTNAME,tgt.IESEQUENCENUMBER = src.IESEQUENCENUMBER,tgt.BASEENGCONTROLNO = src.
			  BASEENGCONTROLNO,tgt.SECTIONNUMBER = src.SECTIONNUMBER,tgt.IEPARTMODIFIER = src.IEPARTMODIFIER,tgt.IECAPTION = src.IECAPTION,tgt.IETYPE = src.IETYPE,tgt.
			  SERVICEABILITYINDICATOR = src.SERVICEABILITYINDICATOR,tgt.IEUPDATEDATE = src.IEUPDATEDATE,tgt.IECONTROLNUMBER = src.IECONTROLNUMBER,tgt.PART = src.PART,tgt.OFPARTS =
			  src.OFPARTS,tgt.ARRANGEMENTINDICATOR = src.ARRANGEMENTINDICATOR,tgt.CCRINDICATOR = src.CCRINDICATOR,tgt.FILTERPARTINDICATOR = src.FILTERPARTINDICATOR,tgt.
			  MAINTPARTINDICATOR = src.MAINTPARTINDICATOR,tgt.NPRINDICATOR = src.NPRINDICATOR,tgt.TYPECHANGEINDICATOR = src.TYPECHANGEINDICATOR,tgt.LASTMODIFIEDDATE = src.
			  LASTMODIFIEDDATE
		WHEN NOT MATCHED BY TARGET
			  THEN
			  INSERT(MEDIANUMBER,IESYSTEMCONTROLNUMBER,IEPARTNUMBER,ORGCODE,IEPARTNAME,IESEQUENCENUMBER,BASEENGCONTROLNO,SECTIONNUMBER,IEPARTMODIFIER,IECAPTION,IETYPE,
			  SERVICEABILITYINDICATOR,IEUPDATEDATE,IECONTROLNUMBER,PART,OFPARTS,ARRANGEMENTINDICATOR,CCRINDICATOR,FILTERPARTINDICATOR,MAINTPARTINDICATOR,NPRINDICATOR,
			  TYPECHANGEINDICATOR,LASTMODIFIEDDATE)
			  VALUES (src.MEDIANUMBER,src.IESYSTEMCONTROLNUMBER,src.IEPARTNUMBER,src.ORGCODE,src.IEPARTNAME,src.IESEQUENCENUMBER,src.BASEENGCONTROLNO,src.SECTIONNUMBER,src.IEPARTMODIFIER,src.
			  IECAPTION,src.IETYPE,src.SERVICEABILITYINDICATOR,src.IEUPDATEDATE,src.IECONTROLNUMBER,src.PART,src.OFPARTS,src.ARRANGEMENTINDICATOR,src.CCRINDICATOR,src.
			  FILTERPARTINDICATOR,src.MAINTPARTINDICATOR,src.NPRINDICATOR,src.TYPECHANGEINDICATOR,src.LASTMODIFIEDDATE) 
		WHEN NOT MATCHED BY SOURCE
			  THEN DELETE
		OUTPUT $ACTION,COALESCE(inserted.MEDIANUMBER,deleted.MEDIANUMBER) MEDIANUMBER,COALESCE(inserted.IESYSTEMCONTROLNUMBER,deleted.IESYSTEMCONTROLNUMBER) IESYSTEMCONTROLNUMBER,
		COALESCE(inserted.IEPARTNUMBER,deleted.IEPARTNUMBER) IEPARTNUMBER,COALESCE(inserted.ORGCODE,deleted.ORGCODE) ORGCODE,COALESCE(inserted.IEPARTNAME,deleted.IEPARTNAME) IEPARTNAME,
        COALESCE(inserted.IESEQUENCENUMBER,deleted.IESEQUENCENUMBER) IESEQUENCENUMBER,COALESCE(inserted.BASEENGCONTROLNO,deleted.BASEENGCONTROLNO) BASEENGCONTROLNO,
        COALESCE(inserted.SECTIONNUMBER,deleted.SECTIONNUMBER) SECTIONNUMBER,COALESCE(inserted.IEPARTMODIFIER,deleted.IEPARTMODIFIER) IEPARTMODIFIER,COALESCE(inserted.IECAPTION,
        deleted.IECAPTION) IECAPTION,COALESCE(inserted.IETYPE,deleted.IETYPE) IETYPE,COALESCE(inserted.SERVICEABILITYINDICATOR,deleted.SERVICEABILITYINDICATOR) SERVICEABILITYINDICATOR,
        COALESCE(inserted.IEUPDATEDATE,deleted.IEUPDATEDATE) IEUPDATEDATE,COALESCE(inserted.IECONTROLNUMBER,deleted.IECONTROLNUMBER) IECONTROLNUMBER,COALESCE(inserted.PART,deleted.PART)
        PART,COALESCE(inserted.OFPARTS,deleted.OFPARTS) OFPARTS,COALESCE(inserted.ARRANGEMENTINDICATOR,deleted.ARRANGEMENTINDICATOR) ARRANGEMENTINDICATOR,COALESCE(inserted.CCRINDICATOR,deleted.CCRINDICATOR)
		CCRINDICATOR,COALESCE(inserted.FILTERPARTINDICATOR,deleted.FILTERPARTINDICATOR) FILTERPARTINDICATOR,COALESCE(inserted.MAINTPARTINDICATOR,deleted.MAINTPARTINDICATOR)
		MAINTPARTINDICATOR,COALESCE(inserted.NPRINDICATOR,deleted.NPRINDICATOR) NPRINDICATOR,COALESCE(inserted.TYPECHANGEINDICATOR,deleted.TYPECHANGEINDICATOR) TYPECHANGEINDICATOR,
		COALESCE(inserted.LASTMODIFIEDDATE,deleted.LASTMODIFIEDDATE) LASTMODIFIEDDATE
			   INTO @MERGE_RESULTS;

		/* MERGE command */
		SELECT @MERGED_ROWS = @@ROWCOUNT;

		SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
		(
			SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'UPDATE')
			AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
			(
				SELECT MR.ACTIONTYPE,MR.MEDIANUMBER,MR.IESYSTEMCONTROLNUMBER,MR.IEPARTNUMBER,MR.ORGCODE,MR.IEPARTNAME,MR.IESEQUENCENUMBER,MR.BASEENGCONTROLNO,MR.SECTIONNUMBER,MR.
				IEPARTMODIFIER,MR.IECAPTION,MR.IETYPE,MR.SERVICEABILITYINDICATOR,MR.IEUPDATEDATE,MR.IECONTROLNUMBER,MR.PART,MR.OFPARTS,MR.ARRANGEMENTINDICATOR,MR.CCRINDICATOR,MR.
				FILTERPARTINDICATOR,MR.MAINTPARTINDICATOR,MR.NPRINDICATOR,MR.TYPECHANGEINDICATOR,MR.LASTMODIFIEDDATE
				FROM @MERGE_RESULTS AS MR FOR JSON AUTO
			) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
		),'Modified Rows');
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;

		COMMIT;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;