
-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200120
-- Modify Date: 2020205		fixed deadlock error
-- Modified by: Prashant S
-- Modify Date: 20230621	Added new column 'RELATION_TYPE'
-- Description: Conditional load from STAGING LNKRELATEDPARTINFO
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.LNKRELATEDPARTINFO_Insert_Update_Delete (@FORCE_LOAD BIT = 'FALSE'
																			  ,@DEBUG      BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY
		DECLARE @SCHEMANAME sysname = 'SISWEB_OWNER_STAGING'
			   ,@TABLENAME  sysname = 'LNKRELATEDPARTINFO';

		DECLARE @FULLTABLENAME   sysname = @SCHEMANAME + '.' + @TABLENAME
			   ,@CURRENT_VERSION BIGINT  = CHANGE_TRACKING_CURRENT_VERSION();

		DECLARE @LAST_SYNCHRONIZATION_VERSION BIGINT           = SISWEB_OWNER_STAGING._getLastSynchVersion (@FULLTABLENAME)
			   ,@RESULT                       BIT
			   ,@ROWCOUNT                     BIGINT
			   ,@MERGED_ROWS                  BIGINT           = 0
			   ,@SYSUTCDATETIME               DATETIME2(6)     = SYSUTCDATETIME()
			   ,@PROCNAME                     VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID                    UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE                   VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE        NVARCHAR(10)
									 ,PARTNUMBER        VARCHAR(20) NOT NULL
									 ,TYPEINDICATOR     VARCHAR(2) NOT NULL
									 ,RELATEDPARTNUMBER VARCHAR(20) NOT NULL
									 ,RELATEDPARTNAME   VARCHAR(256) NULL
									 ,NPRINDICATOR      VARCHAR(1) NULL
									 ,RELATION_TYPE		VARCHAR(50) NULL
									 ,LASTMODIFIEDDATE  VARCHAR(50) NULL);

/* 
	Davide 20200205 
	in order to avoid deadlocks errors like: "Transaction (Process ID 246) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.",
	we move the creation of temp table outside the TRANSACTION block, even if it is not extremely elegant
*/
		DROP TABLE IF EXISTS #DIFF_PRIMARY_KEYS;
		SELECT CT.SYS_CHANGE_OPERATION AS OPERATION,CT.PARTNUMBER AS PARTNUMBER,CT.TYPEINDICATOR AS TYPEINDICATOR,CT.RELATEDPARTNUMBER AS RELATEDPARTNUMBER,CT.SYS_CHANGE_VERSION
		AS SYS_CHANGE_VERSION,CT.SYS_CHANGE_COLUMNS AS SYS_CHANGE_COLUMNS
		INTO #DIFF_PRIMARY_KEYS
		FROM CHANGETABLE(CHANGES SISWEB_OWNER_STAGING.LNKRELATEDPARTINFO,@LAST_SYNCHRONIZATION_VERSION) AS CT;

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		IF @FORCE_LOAD = 'FALSE'
		BEGIN
			EXEC SISWEB_OWNER_STAGING._getFullOrDiff @SCHEMANAME = @SCHEMANAME,@TABLENAME = @TABLENAME,@CURRENT_VERSION = @CURRENT_VERSION,@DEBUG = @DEBUG,@RESULT = @RESULT OUTPUT
			;

			IF @DEBUG = 'TRUE'
				PRINT FORMATMESSAGE('@RESULT=%s',IIF(@RESULT = 1,'TRUE','FALSE'));

			IF @RESULT = 'TRUE'
			BEGIN
				-- 6. Obtain the changes

				IF @DEBUG = 'TRUE'
					SELECT * FROM #DIFF_PRIMARY_KEYS AS DK;

				-- 7.a Delete if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'D';
				IF @ROWCOUNT > 0
				BEGIN
					DELETE FROM SISWEB_OWNER.LNKRELATEDPARTINFO
					OUTPUT 'DELETE' ACTIONTYPE,DELETED.PARTNUMBER,DELETED.TYPEINDICATOR,DELETED.RELATEDPARTNUMBER,DELETED.RELATEDPARTNAME,DELETED.NPRINDICATOR,DELETED.RELATION_TYPE,DELETED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.PARTNUMBER = LNKRELATEDPARTINFO.PARTNUMBER AND 
							  DK.TYPEINDICATOR = LNKRELATEDPARTINFO.TYPEINDICATOR AND 
							  DK.RELATEDPARTNUMBER = LNKRELATEDPARTINFO.RELATEDPARTNUMBER AND 
							  DK.OPERATION = 'D'
					);

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Deleted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.b Insert if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'I';
				IF @ROWCOUNT > 0
				BEGIN
					INSERT INTO SISWEB_OWNER.LNKRELATEDPARTINFO (PARTNUMBER,TYPEINDICATOR,RELATEDPARTNUMBER,RELATEDPARTNAME,NPRINDICATOR,RELATION_TYPE,LASTMODIFIEDDATE) 
					OUTPUT 'INSERT' ACTIONTYPE,INSERTED.PARTNUMBER,INSERTED.TYPEINDICATOR,INSERTED.RELATEDPARTNUMBER,INSERTED.RELATEDPARTNAME,INSERTED.NPRINDICATOR,INSERTED.RELATION_TYPE,INSERTED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
						   SELECT PARTNUMBER,TYPEINDICATOR,RELATEDPARTNUMBER,RELATEDPARTNAME,NPRINDICATOR,RELATION_TYPE,@SYSUTCDATETIME
						   FROM SISWEB_OWNER_STAGING.LNKRELATEDPARTINFO AS DT
						   WHERE EXISTS
						   (
							   SELECT *
							   FROM #DIFF_PRIMARY_KEYS AS DK
							   WHERE DK.PARTNUMBER = DT.PARTNUMBER AND 
									 DK.TYPEINDICATOR = DT.TYPEINDICATOR AND 
									 DK.RELATEDPARTNUMBER = DT.RELATEDPARTNUMBER AND 
									 DK.OPERATION = 'I'
						   );

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Inserted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.c Update if needed
				SELECT @ROWCOUNT = COUNT(*)
				FROM #DIFF_PRIMARY_KEYS AS DK
				WHERE DK.OPERATION = 'U' AND 
					  (-- if the modified column is LASTMODIFIEDDATE ignore the update 
					  DK.SYS_CHANGE_COLUMNS <> 0x0000000006000000 OR 
					  DK.SYS_CHANGE_COLUMNS IS NULL
					  );
				IF @ROWCOUNT > 0
				BEGIN
					UPDATE SISWEB_OWNER.LNKRELATEDPARTINFO
					  SET RELATEDPARTNAME = ST.RELATEDPARTNAME,NPRINDICATOR = ST.NPRINDICATOR,RELATION_TYPE = ST.RELATION_TYPE,LASTMODIFIEDDATE = @SYSUTCDATETIME
					OUTPUT 'UPDATE' ACTIONTYPE,INSERTED.PARTNUMBER,INSERTED.TYPEINDICATOR,INSERTED.RELATEDPARTNUMBER,INSERTED.RELATEDPARTNAME,INSERTED.NPRINDICATOR,INSERTED.RELATION_TYPE,INSERTED.LASTMODIFIEDDATE
						   INTO @MERGE_RESULTS
					FROM SISWEB_OWNER_STAGING.LNKRELATEDPARTINFO AS ST
						 JOIN SISWEB_OWNER.LNKRELATEDPARTINFO AS TT ON ST.PARTNUMBER = TT.PARTNUMBER AND 
																	   ST.TYPEINDICATOR = TT.TYPEINDICATOR AND 
																	   ST.RELATEDPARTNUMBER = TT.RELATEDPARTNUMBER
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.PARTNUMBER = ST.PARTNUMBER AND 
							  DK.TYPEINDICATOR = ST.TYPEINDICATOR AND 
							  DK.RELATEDPARTNUMBER = ST.RELATEDPARTNUMBER AND 
							  DK.OPERATION = 'U'
					);
					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Updated %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 8. Store current version to be used the next time
				IF @DEBUG = 'TRUE'
					SELECT * FROM @MERGE_RESULTS AS MR;

				EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

				SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
				(
					SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
					'UPDATE'
					) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
					(
						SELECT MR.ACTIONTYPE,MR.PARTNUMBER,MR.TYPEINDICATOR,MR.RELATEDPARTNUMBER,MR.RELATEDPARTNAME,MR.NPRINDICATOR,MR.RELATION_TYPE,MR.LASTMODIFIEDDATE
						FROM @MERGE_RESULTS AS MR FOR JSON AUTO
					) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
				),'Modified Rows');
				EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
			END;
		END;

		/* to be done: handle full load with MERGE */
		IF @FORCE_LOAD = 'TRUE'
		--   OR @MODIFIED_ROWS_PERCENTAGE BETWEEN-0.10 AND 0.10
		BEGIN
			SET @LOGMESSAGE = 'Executing load: Force Load = TRUE';
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @FORCE_LOAD;

			/* MERGE command */
			MERGE INTO SISWEB_OWNER.LNKRELATEDPARTINFO tgt
			USING SISWEB_OWNER_STAGING.LNKRELATEDPARTINFO src
			ON src.PARTNUMBER = tgt.PARTNUMBER AND 
			   src.TYPEINDICATOR = tgt.TYPEINDICATOR AND 
			   src.RELATEDPARTNUMBER = tgt.RELATEDPARTNUMBER
			WHEN MATCHED AND EXISTS
			(
				SELECT src.RELATEDPARTNAME,src.NPRINDICATOR, src.RELATION_TYPE
				EXCEPT
				SELECT tgt.RELATEDPARTNAME,tgt.NPRINDICATOR, tgt.RELATION_TYPE
			)
				  THEN UPDATE SET tgt.RELATEDPARTNAME = src.RELATEDPARTNAME,tgt.NPRINDICATOR = src.NPRINDICATOR, tgt.RELATION_TYPE = src.RELATION_TYPE,tgt.LASTMODIFIEDDATE = @SYSUTCDATETIME
			WHEN NOT MATCHED BY TARGET
				  THEN
				  INSERT(PARTNUMBER,TYPEINDICATOR,RELATEDPARTNUMBER,RELATEDPARTNAME,NPRINDICATOR,RELATION_TYPE,LASTMODIFIEDDATE)
				  VALUES (src.PARTNUMBER,src.TYPEINDICATOR,src.RELATEDPARTNUMBER,src.RELATEDPARTNAME,src.NPRINDICATOR,src.RELATION_TYPE,@SYSUTCDATETIME) 
			WHEN NOT MATCHED BY SOURCE
				  THEN DELETE
			OUTPUT $ACTION,COALESCE(inserted.PARTNUMBER,deleted.PARTNUMBER) PARTNUMBER,COALESCE(inserted.TYPEINDICATOR,deleted.TYPEINDICATOR) TYPEINDICATOR,COALESCE(inserted.
			RELATEDPARTNUMBER,deleted.RELATEDPARTNUMBER) RELATEDPARTNUMBER,COALESCE(inserted.RELATEDPARTNAME,deleted.RELATEDPARTNAME) RELATEDPARTNAME,COALESCE(inserted.
			NPRINDICATOR,deleted.NPRINDICATOR) NPRINDICATOR,COALESCE(inserted.RELATION_TYPE,deleted.RELATION_TYPE) RELATION_TYPE,COALESCE(inserted.LASTMODIFIEDDATE,deleted.LASTMODIFIEDDATE) LASTMODIFIEDDATE
				   INTO @MERGE_RESULTS;

			/* MERGE command */
			SELECT @MERGED_ROWS = @@ROWCOUNT;

			EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

			SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
			(
				SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
				'UPDATE'
				) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
				(
					SELECT MR.ACTIONTYPE,MR.PARTNUMBER,MR.TYPEINDICATOR,MR.RELATEDPARTNUMBER,MR.RELATEDPARTNAME,MR.NPRINDICATOR, MR.RELATION_TYPE,MR.LASTMODIFIEDDATE
					FROM @MERGE_RESULTS AS MR FOR JSON AUTO
				) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
			),'Modified Rows');
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
		END;

		COMMIT;

								UPDATE STATISTICS SISWEB_OWNER.LNKRELATEDPARTINFO WITH FULLSCAN;

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;
GO

