
-- =============================================
-- Author:      Davide Moraschi
-- Create Date: 20200130
-- Modify Date: 20200205	fixed deadlock error
-- Description: Conditional load from STAGING MASEPSTESTCELLDATA
-- =============================================
CREATE PROCEDURE SISWEB_OWNER_STAGING.MASEPSTESTCELLDATA_Insert_Update_Delete (@FORCE_LOAD BIT = 'FALSE'
																			  ,@DEBUG      BIT = 'FALSE') 
AS
BEGIN
	SET TRANSACTION ISOLATION LEVEL SNAPSHOT;
	SET XACT_ABORT,NOCOUNT ON;
	BEGIN TRY
		DECLARE @SCHEMANAME sysname = 'SISWEB_OWNER_STAGING'
			   ,@TABLENAME  sysname = 'MASEPSTESTCELLDATA';

		DECLARE @FULLTABLENAME   sysname = @SCHEMANAME + '.' + @TABLENAME
			   ,@CURRENT_VERSION BIGINT  = CHANGE_TRACKING_CURRENT_VERSION();

		DECLARE @LAST_SYNCHRONIZATION_VERSION BIGINT           = SISWEB_OWNER_STAGING._getLastSynchVersion (@FULLTABLENAME)
			   ,@RESULT                       BIT
			   ,@ROWCOUNT                     BIGINT
			   ,@MERGED_ROWS                  BIGINT           = 0
			   ,@SYSUTCDATETIME               DATETIME2(6)     = SYSUTCDATETIME()
			   ,@PROCNAME                     VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
			   ,@PROCESSID                    UNIQUEIDENTIFIER = NEWID()
			   ,@LOGMESSAGE                   VARCHAR(MAX);

		DECLARE @MERGE_RESULTS TABLE (ACTIONTYPE   NVARCHAR(10)
									 ,SERIALNUMBER VARCHAR(8) NOT NULL
									 ,SALESMODEL   VARCHAR(10) NULL
									 ,VEHICLEMODEL VARCHAR(5) NULL
									 ,BUILT        DATETIME2(0) NULL
									 ,PLANT        VARCHAR(2) NULL
									 ,TESTDATE     DATETIME2(0) NULL
									 ,SHIPPED      DATETIME2(0) NULL
									 ,TESTED       VARCHAR(2) NULL
									 ,TESTNUMBER   VARCHAR(2) NULL
									 ,CELLNUMBER   VARCHAR(2) NULL
									 ,COMBUSTION   VARCHAR(2) NULL);

/* 
	Davide 20200205 
	in order to avoid deadlocks errors like: "Transaction (Process ID 246) was deadlocked on lock | communication buffer resources with another process and has been chosen as the deadlock victim. Rerun the transaction.",
	we move the creation of temp table outside the TRANSACTION block, even if it is not extremely elegant
*/
		DROP TABLE IF EXISTS #DIFF_PRIMARY_KEYS;
		SELECT CT.SYS_CHANGE_OPERATION AS OPERATION,CT.SERIALNUMBER AS SERIALNUMBER,CT.SYS_CHANGE_VERSION AS SYS_CHANGE_VERSION,CT.SYS_CHANGE_COLUMNS AS SYS_CHANGE_COLUMNS
		INTO #DIFF_PRIMARY_KEYS
		FROM CHANGETABLE(CHANGES SISWEB_OWNER_STAGING.MASEPSTESTCELLDATA,@LAST_SYNCHRONIZATION_VERSION) AS CT;

		BEGIN TRANSACTION;
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;

		IF @FORCE_LOAD = 'FALSE'
		BEGIN
			EXEC SISWEB_OWNER_STAGING._getFullOrDiff @SCHEMANAME = @SCHEMANAME,@TABLENAME = @TABLENAME,@CURRENT_VERSION = @CURRENT_VERSION,@DEBUG = @DEBUG,@RESULT = @RESULT OUTPUT
			;

			IF @DEBUG = 'TRUE'
				PRINT FORMATMESSAGE('@RESULT=%s',IIF(@RESULT = 1,'TRUE','FALSE'));

			IF @RESULT = 'TRUE'
			BEGIN
				-- 6. Obtain the changes

				IF @DEBUG = 'TRUE'
					SELECT * FROM #DIFF_PRIMARY_KEYS AS DK;

				-- 7.a Delete if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'D';
				IF @ROWCOUNT > 0
				BEGIN
					DELETE FROM SISWEB_OWNER.MASEPSTESTCELLDATA
					OUTPUT 'DELETE' ACTIONTYPE,DELETED.SERIALNUMBER,DELETED.SALESMODEL,DELETED.VEHICLEMODEL,DELETED.BUILT,DELETED.PLANT,DELETED.TESTDATE,DELETED.SHIPPED,DELETED.
					TESTED,DELETED.TESTNUMBER,DELETED.CELLNUMBER,DELETED.COMBUSTION
						   INTO @MERGE_RESULTS
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.SERIALNUMBER = MASEPSTESTCELLDATA.SERIALNUMBER AND 
							  DK.OPERATION = 'D'
					);

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Deleted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.b Insert if needed
				SELECT @ROWCOUNT = COUNT(*) FROM #DIFF_PRIMARY_KEYS AS DK WHERE DK.OPERATION = 'I';
				IF @ROWCOUNT > 0
				BEGIN
					INSERT INTO SISWEB_OWNER.MASEPSTESTCELLDATA (SERIALNUMBER,SALESMODEL,VEHICLEMODEL,BUILT,PLANT,TESTDATE,SHIPPED,TESTED,TESTNUMBER,CELLNUMBER,COMBUSTION) 
					OUTPUT 'INSERT' ACTIONTYPE,INSERTED.SERIALNUMBER,INSERTED.SALESMODEL,INSERTED.VEHICLEMODEL,INSERTED.BUILT,INSERTED.PLANT,INSERTED.TESTDATE,INSERTED.SHIPPED,
					INSERTED.TESTED,INSERTED.TESTNUMBER,INSERTED.CELLNUMBER,INSERTED.COMBUSTION
						   INTO @MERGE_RESULTS
						   SELECT SERIALNUMBER,SALESMODEL,VEHICLEMODEL,BUILT,PLANT,TESTDATE,SHIPPED,TESTED,TESTNUMBER,CELLNUMBER,COMBUSTION
						   FROM SISWEB_OWNER_STAGING.MASEPSTESTCELLDATA AS DT
						   WHERE EXISTS
						   (
							   SELECT *
							   FROM #DIFF_PRIMARY_KEYS AS DK
							   WHERE DK.SERIALNUMBER = DT.SERIALNUMBER AND 
									 DK.OPERATION = 'I'
						   );

					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Inserted %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 7.c Update if needed
				SELECT @ROWCOUNT = COUNT(*)
				FROM #DIFF_PRIMARY_KEYS AS DK
				WHERE DK.OPERATION = 'U' AND 
					  (-- if the modified column is LASTMODIFIEDDATE ignore the update 
					  DK.SYS_CHANGE_COLUMNS <> 0x000000000C000000 OR 
					  DK.SYS_CHANGE_COLUMNS IS NULL
					  );
				IF @ROWCOUNT > 0
				BEGIN
					UPDATE SISWEB_OWNER.MASEPSTESTCELLDATA
					  SET SALESMODEL = ST.SALESMODEL,VEHICLEMODEL = ST.VEHICLEMODEL,BUILT = ST.BUILT,PLANT = ST.PLANT,TESTDATE = ST.TESTDATE,SHIPPED = ST.SHIPPED,TESTED = ST.
					  TESTED,TESTNUMBER = ST.TESTNUMBER,CELLNUMBER = ST.CELLNUMBER,COMBUSTION = ST.COMBUSTION
					OUTPUT 'UPDATE' ACTIONTYPE,INSERTED.SERIALNUMBER,INSERTED.SALESMODEL,INSERTED.VEHICLEMODEL,INSERTED.BUILT,INSERTED.PLANT,INSERTED.TESTDATE,INSERTED.SHIPPED,
					INSERTED.TESTED,INSERTED.TESTNUMBER,INSERTED.CELLNUMBER,INSERTED.COMBUSTION
						   INTO @MERGE_RESULTS
					FROM SISWEB_OWNER_STAGING.MASEPSTESTCELLDATA AS ST
						 JOIN SISWEB_OWNER.MASEPSTESTCELLDATA AS TT ON ST.SERIALNUMBER = TT.SERIALNUMBER
					WHERE EXISTS
					(
						SELECT *
						FROM #DIFF_PRIMARY_KEYS AS DK
						WHERE DK.SERIALNUMBER = ST.SERIALNUMBER AND 
							  DK.OPERATION = 'U'
					);
					SELECT @MERGED_ROWS = @@ROWCOUNT;

					SET @LOGMESSAGE = FORMATMESSAGE('Updated %s rows',CAST(@MERGED_ROWS AS VARCHAR(9)));
					EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
				END;

				-- 8. Store current version to be used the next time
				IF @DEBUG = 'TRUE'
					SELECT * FROM @MERGE_RESULTS AS MR;

				EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

				SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
				(
					SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
					'UPDATE'
					) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
					(
						SELECT MR.ACTIONTYPE,MR.SERIALNUMBER,MR.SALESMODEL,MR.VEHICLEMODEL,MR.BUILT,MR.PLANT,MR.TESTDATE,MR.SHIPPED,MR.TESTED,MR.TESTNUMBER,MR.CELLNUMBER,MR.
						COMBUSTION
						FROM @MERGE_RESULTS AS MR FOR JSON AUTO
					) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
				),'Modified Rows');
				EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
			END;
		END;

		/* to be done: handle full load with MERGE */
		IF @FORCE_LOAD = 'TRUE'
		--   OR @MODIFIED_ROWS_PERCENTAGE BETWEEN-0.10 AND 0.10
		BEGIN
			SET @LOGMESSAGE = 'Executing load: Force Load = TRUE';
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @FORCE_LOAD;

			/* MERGE command */
			MERGE INTO SISWEB_OWNER.MASEPSTESTCELLDATA tgt
			USING SISWEB_OWNER_STAGING.MASEPSTESTCELLDATA src
			ON src.SERIALNUMBER = tgt.SERIALNUMBER
			WHEN MATCHED AND EXISTS
			(
				SELECT src.SALESMODEL,src.VEHICLEMODEL,src.BUILT,src.PLANT,src.TESTDATE,src.SHIPPED,src.TESTED,src.TESTNUMBER,src.CELLNUMBER,src.COMBUSTION
				EXCEPT
				SELECT tgt.SALESMODEL,tgt.VEHICLEMODEL,tgt.BUILT,tgt.PLANT,tgt.TESTDATE,tgt.SHIPPED,tgt.TESTED,tgt.TESTNUMBER,tgt.CELLNUMBER,tgt.COMBUSTION
			)
				  THEN UPDATE SET tgt.SALESMODEL = src.SALESMODEL,tgt.VEHICLEMODEL = src.VEHICLEMODEL,tgt.BUILT = src.BUILT,tgt.PLANT = src.PLANT,tgt.TESTDATE = src.TESTDATE,tgt.
				  SHIPPED = src.SHIPPED,tgt.TESTED = src.TESTED,tgt.TESTNUMBER = src.TESTNUMBER,tgt.CELLNUMBER = src.CELLNUMBER,tgt.COMBUSTION = src.COMBUSTION
			WHEN NOT MATCHED BY TARGET
				  THEN
				  INSERT(SERIALNUMBER,SALESMODEL,VEHICLEMODEL,BUILT,PLANT,TESTDATE,SHIPPED,TESTED,TESTNUMBER,CELLNUMBER,COMBUSTION)
				  VALUES (src.SERIALNUMBER,src.SALESMODEL,src.VEHICLEMODEL,src.BUILT,src.PLANT,src.TESTDATE,src.SHIPPED,src.TESTED,src.TESTNUMBER,src.CELLNUMBER,src.COMBUSTION) 
			WHEN NOT MATCHED BY SOURCE
				  THEN DELETE
			OUTPUT $ACTION,COALESCE(inserted.SERIALNUMBER,deleted.SERIALNUMBER) SERIALNUMBER,COALESCE(inserted.SALESMODEL,deleted.SALESMODEL) SALESMODEL,COALESCE(inserted.
			VEHICLEMODEL,deleted.VEHICLEMODEL) VEHICLEMODEL,COALESCE(inserted.BUILT,deleted.BUILT) BUILT,COALESCE(inserted.PLANT,deleted.PLANT) PLANT,COALESCE(inserted.TESTDATE,
			deleted.TESTDATE) TESTDATE,COALESCE(inserted.SHIPPED,deleted.SHIPPED) SHIPPED,COALESCE(inserted.TESTED,deleted.TESTED) TESTED,COALESCE(inserted.TESTNUMBER,deleted.
			TESTNUMBER) TESTNUMBER,COALESCE(inserted.CELLNUMBER,deleted.CELLNUMBER) CELLNUMBER,COALESCE(inserted.COMBUSTION,deleted.COMBUSTION) COMBUSTION
				   INTO @MERGE_RESULTS;

			/* MERGE command */
			SELECT @MERGED_ROWS = @@ROWCOUNT;

			EXEC SISWEB_OWNER_STAGING._setLastSynchVersion @FULLTABLENAME,@CURRENT_VERSION;

			SET @LOGMESSAGE = IIF(@DEBUG = 'TRUE',
			(
				SELECT(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'INSERT') AS Inserted,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE =
				'UPDATE'
				) AS Updated,(SELECT COUNT(*) FROM @MERGE_RESULTS AS MR WHERE MR.ACTIONTYPE = 'DELETE') AS Deleted,
				(
					SELECT MR.ACTIONTYPE,MR.SERIALNUMBER,MR.SALESMODEL,MR.VEHICLEMODEL,MR.BUILT,MR.PLANT,MR.TESTDATE,MR.SHIPPED,MR.TESTED,MR.TESTNUMBER,MR.CELLNUMBER,MR.COMBUSTION
					FROM @MERGE_RESULTS AS MR FOR JSON AUTO
				) AS Modified_Rows FOR JSON PATH,WITHOUT_ARRAY_WRAPPER
			),'Modified Rows');
			EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @MERGED_ROWS;
		END;

		COMMIT;

								UPDATE STATISTICS SISWEB_OWNER.MASEPSTESTCELLDATA WITH FULLSCAN;

		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
	END TRY
	BEGIN CATCH
		DECLARE @ERRORMESSAGE NVARCHAR(4000) = ERROR_MESSAGE()
			   ,@ERRORLINE    INT            = ERROR_LINE()
			   ,@ERRORNUM     INT            = ERROR_NUMBER();
		IF @@TRANCOUNT > 0
			ROLLBACK TRANSACTION;
		SET @LOGMESSAGE = FORMATMESSAGE('LINE %s: %s',CAST(@ERRORLINE AS VARCHAR(10)),CAST(@ERRORMESSAGE AS VARCHAR(4000)));
		EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Error',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = @ERRORNUM;
	END CATCH;
END;
GO

