CREATE PROCEDURE SISWEB_OWNER_STAGING.NPRINDICATOR_Update
AS
  BEGIN
  
  DECLARE @PROCNAME         VARCHAR(200)     = OBJECT_SCHEMA_NAME(@@PROCID) + '.' + OBJECT_NAME(@@PROCID)
    ,@PROCESSID             UNIQUEIDENTIFIER = NEWID()
    ,@LOGMESSAGE            VARCHAR(MAX);

  EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution started',@DATAVALUE = NULL;
    
  UPDATE X  
  SET X.NPRINDICATOR = 'N' FROM
  SISWEB_OWNER_STAGING.LNKMEDIAIEPART X  where IEPARTNUMBER in(
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO
  except 
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO_SWAP)

  SET @LOGMESSAGE = 'Updated records in LNKMEDIAIEPART with NPRINDICATOR:N';
  EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = NULL;

  UPDATE X  
  SET X.NPRINDICATOR = 'Y' FROM
  SISWEB_OWNER_STAGING.LNKMEDIAIEPART X  where IEPARTNUMBER in(
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO_SWAP
  except 
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO)

    SET @LOGMESSAGE = 'Updated records in LNKMEDIAIEPART with NPRINDICATOR:Y';
    EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = NULL;

  UPDATE X  
  SET X.NPRINDICATOR = 'N' FROM
  SISWEB_OWNER_STAGING.LNKCONSISTLIST X  where PARTNUMBER in(
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO
  except 
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO_SWAP)

    SET @LOGMESSAGE = 'Updated records in LNKCONSISTLIST with NPRINDICATOR:N';
    EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = NULL;

  UPDATE X  
  SET X.NPRINDICATOR = 'Y' FROM
  SISWEB_OWNER_STAGING.LNKCONSISTLIST X  where PARTNUMBER in(
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO_SWAP
  except 
  select PARTNUMBER from SISWEB_OWNER_STAGING.LNKNPRINFO)
 
  SET @LOGMESSAGE = 'Updated records in LNKCONSISTLIST with NPRINDICATOR:Y';
  EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = @LOGMESSAGE,@DATAVALUE = NULL;
  EXEC sis_stage.WriteLog @PROCESSID = @PROCESSID,@LOGTYPE = 'Information',@NAMEOFSPROC = @PROCNAME,@LOGMESSAGE = 'Execution completed',@DATAVALUE = NULL;
 
 END
