CREATE TABLE [SISSEARCH].[CONSISTPARTS_2] (
    [IESYSTEMCONTROLNUMBER]  VARCHAR (12)   NOT NULL,
    [ID]                     VARCHAR (50)   NOT NULL,
    [CONSISTPART]            NVARCHAR (MAX) NULL,
    [INSERTDATE]             DATETIME       NOT NULL,
    [ConsistPartNames_es-ES] NVARCHAR (MAX) NULL,
    [ConsistPartNames_zh-CN] NVARCHAR (MAX) NULL,
    [ConsistPartNames_fr-FR] NVARCHAR (MAX) NULL,
    [ConsistPartNames_it-IT] NVARCHAR (MAX) NULL,
    [ConsistPartNames_de-DE] NVARCHAR (MAX) NULL,
    [ConsistPartNames_pt-BR] NVARCHAR (MAX) NULL,
    [ConsistPartNames_id-ID] NVARCHAR (MAX) NULL,
    [ConsistPartNames_ja-JP] NVARCHAR (MAX) NULL,
    [ConsistPartNames_ru-RU] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_CONSISTPARTS_2] PRIMARY KEY CLUSTERED ([ID] ASC)
);
GO

CREATE NONCLUSTERED INDEX [IX_CONSISTPARTS_2_IESYSTEMCONTROLNUMBER]
    ON [SISSEARCH].[CONSISTPARTS_2]([IESYSTEMCONTROLNUMBER] ASC);
GO

CREATE NONCLUSTERED INDEX [IX_CONSISTPARTS_2_INSERTDATE]
    ON [SISSEARCH].[CONSISTPARTS_2]([INSERTDATE] ASC);
GO

