CREATE TABLE [SISWEB_OWNER_STAGING].[_LAST_SYNCHRONIZATION_VERSIONS] (
    [TABLENAME]                    [sysname] NOT NULL,
    [LAST_SYNCHRONIZATION_VERSION] BIGINT    NOT NULL,
    CONSTRAINT [PK_LAST_SYNCHRONIZATION_VERSIONS] PRIMARY KEY NONCLUSTERED ([TABLENAME] ASC)
);
GO

