CREATE TABLE [SISWEB_OWNER_STAGING].[AUTHORINGPARTNAMES]
(
	[PARTNUMBER]            VARCHAR(12)      NOT NULL,
    [PARTNAME]         VARCHAR(255)      NOT NULL
);

GO

CREATE INDEX IDX_AUTHORINGPARTNAMES_PNO ON [SISWEB_OWNER_STAGING].[AUTHORINGPARTNAMES] (PARTNUMBER)
GO