CREATE TABLE [SISWEB_OWNER_STAGING].[LNKCCRMEDIATITLE]
(
	[CCRMEDIARID]		NUMERIC(10)		NOT NULL, 
    [MEDIANUMBER]		CHAR(8)			NOT NULL,
	[LASTMODIFIEDDATE]  DATETIME2(6)    NULL, 
    CONSTRAINT [PK_LNKCCRMEDIATITLE] PRIMARY KEY ([CCRMEDIARID] ASC) 
);
