CREATE TABLE [SISWEB_OWNER_STAGING].[LNKCCRFRAGMENTEDPARTNAMES]
(
    [ID]                INT IDENTITY(1,1)       NOT NULL,
	[SNP]               VARCHAR(10)             NOT NULL,
    [PSID]              CHAR(8)                 NOT NULL,
    [PARENTLIKE]        NVARCHAR(288)           NULL,
    [PARENTEQUALTO]     NVARCHAR(288)           NULL,
    [PARENTNOTEQUALTO]  NVARCHAR(288)           NULL,
	[LASTMODIFIEDDATE]  DATETIME2(6)            NULL,
	CONSTRAINT [PK_LNKCCRFRAGMENTEDPARTNAMES] PRIMARY KEY ([ID] ASC)
);
 GO

CREATE NONCLUSTERED INDEX IX_LNKCCRFRAGPNAME_PL ON SISWEB_OWNER_STAGING.LNKCCRFRAGMENTEDPARTNAMES (PARENTLIKE ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKCCRFRAGPNAME_PETO ON SISWEB_OWNER_STAGING.LNKCCRFRAGMENTEDPARTNAMES (PARENTEQUALTO ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKCCRFRAGPNAME_PNETO ON SISWEB_OWNER_STAGING.LNKCCRFRAGMENTEDPARTNAMES (PARENTNOTEQUALTO ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKCCRFRGMTDPNAMES_SNP_PSID ON SISWEB_OWNER_STAGING.LNKCCRFRAGMENTEDPARTNAMES (SNP ASC, PSID ASC);
GO
