CREATE TABLE [SISWEB_OWNER_STAGING].[LNKCONSISTLIST] (
    [IESYSTEMCONTROLNUMBER]   VARCHAR (12)   NOT NULL,
    [PARTSEQUENCENUMBER]      SMALLINT       NOT NULL,
    [REFERENCENO]             VARCHAR (50)   NULL,
    [GRAPHNO]                 VARCHAR (50)   NULL,
    [PARTNUMBER]              VARCHAR (20)   NOT NULL,
    [PARTNAME]                NVARCHAR (64)  NULL,
    [PARTMODIFIER]            NVARCHAR (512) NULL,
    [QUANTITY]                VARCHAR (24)   NULL,
    [NOTE]                    VARCHAR (10)   NULL,
    [COMMENTS]                NVARCHAR (512) NULL,
    [SERVICEABILITYINDICATOR] VARCHAR (1)    NULL,
    [PARENTAGE]               SMALLINT       NULL,
    [CCRINDICATOR]            VARCHAR (1)    NULL,
    [FILTERPARTINDICATOR]     VARCHAR (1)    NULL,
    [MAINTPARTINDICATOR]      VARCHAR (1)    NULL,
    [NPRINDICATOR]            VARCHAR (1)    NULL,
    [LASTMODIFIEDDATE]        DATETIME2 (6)  NULL,
    CONSTRAINT [PKCI_LNKCONSISTLIST] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [PARTSEQUENCENUMBER] ASC) WITH (FILLFACTOR = 100)
);





GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKCONSISTLIST] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_LNKCONSISTLIST_IESCN ON SISWEB_OWNER_STAGING.LNKCONSISTLIST (IESYSTEMCONTROLNUMBER ASC) ;
GO

CREATE NONCLUSTERED INDEX IX_LNKCONSISTLIST_IESCNFPI ON SISWEB_OWNER_STAGING.LNKCONSISTLIST (IESYSTEMCONTROLNUMBER ASC, FILTERPARTINDICATOR ASC) ;
GO

CREATE NONCLUSTERED INDEX IX_LNKCONSISTLIST_PARTNUMBER ON SISWEB_OWNER_STAGING.LNKCONSISTLIST (PARTNUMBER ASC);
GO
