CREATE TABLE [SISWEB_OWNER_STAGING].[LNKCAPTIVETOPRIME](
	[MEDIANUMBER] [varchar](8) NOT NULL,
	[PRIMESERIALNUMBER] [varchar](8) NOT NULL,
	[CAPTIVESERIALNUMBER] [varchar](8) NOT NULL,
	[ATTACHMENTTYPE] [varchar](6) NOT NULL
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_SISWEB_OWNER_STAGING_LNKCAPTIVETOPRIME_MEDIANUMBER
ON [SISWEB_OWNER_STAGING].[LNKCAPTIVETOPRIME] ([MEDIANUMBER])
INCLUDE ([PRIMESERIALNUMBER]);
GO

CREATE NONCLUSTERED INDEX IX_SISWEB_OWNER_STAGING_LNKCAPTIVETOPRIME_CAPTIVESERIALNUMBER
ON [SISWEB_OWNER_STAGING].[LNKCAPTIVETOPRIME] ([CAPTIVESERIALNUMBER]);
GO