CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSTURBOASSEMBLYSPECS] (
    [SPECRID]                 NUMERIC(16,0) NOT NULL,  
    [PARTNUMBER]              VARCHAR(7) NOT NULL, 
    [TURBOHOUSINGNOZZELSIZE]          VARCHAR(30), 
    [TURBOMODELQUANTITY]              VARCHAR(2) 
);