CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSALTITUDESPECS] (
    [SPECRID]                   NUMERIC(16,0) NOT NULL,  
    [MAXALTITUDE]               NUMERIC(38,0) NOT NULL,   
    [ENGINEPOWERRATINGWOUTFAN]          NUMERIC(38,1), 
    [ENGINEPOWERRATINGWFAN]             NUMERIC(38,1), 
    [HIGHIDLEDYNO]                      NUMERIC(38,0),   
    [HIGHIDLESPEED]                     NUMERIC(38,0),   
    [FLSTATICFUELSETTING]               NUMERIC(38,2), 
    [FULLLOADBOOSTPRESSURE]             NUMERIC(38,1), 
    [CONVERTORSTALLBOOSTPRS]            NUMERIC(38,1), 
    [CONVERTORSTALLSPEED]               NUMERIC(38,0),   
    [FTSTATICFUELSETTING]               NUMERIC(38,2), 
    [CORRECTEDFUELRATE]                 NUMERIC(38,1), 
    CONSTRAINT [LNKEPSALTITUDESPECS_PK_LNKEPSALTITUDESPECS] PRIMARY KEY CLUSTERED ([SPECRID] ASC, [MAXALTITUDE] ASC),
    CONSTRAINT [FK_LNKEPSALTITUDESPECS_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);