CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSAPPLICATIONSPECS] (
    [SPECRID]                   NUMERIC (16,0) NOT NULL,  
    [APPLICATIONCODE]                    VARCHAR(3), 
    [ENGINEAPPLICATIONCODE]              VARCHAR(2), 
    [MODELAPPLICATIONDATA]               VARCHAR(11),
    [ENGINEAPPLICATION]                  VARCHAR(30),
    [ENGINESOURCEFACTORYREFNO]           VARCHAR(2), 
    [ENGINEPERFDATAREFNO]                VARCHAR(9), 
    [LOWIDLEINVEHICLESPEED]              NUMERIC(38,0),   
    [MULTIENGINERATING]                  VARCHAR(7), 
    [ELECTRENGINECONTROL]                VARCHAR(7), 
    [EMISSIONSFAMILY]                    VARCHAR(13),
    [EMISSIONSENGINECODE]                VARCHAR(2), 
    [GENERATORRATING]                    NUMERIC(38,1), 
    [GENERATORFREQUENCY]                 NUMERIC(38,0),   
    [CERTIFIEDENGINERATING]              NUMERIC(38,1), 
    [LLOYDCERTIFIEDGENERATORKW]          NUMERIC(38,0),   
    [LASTACTDATE]                        DATETIME2 (0),         
    [LASTACTTIME]                        VARCHAR(4), 
    [TORQUECHECKFUELRATEAVG]             NUMERIC(38,1), 
    [ENGINECOUNT]                        NUMERIC(38,0),   
    [RESPONSETESTFLAG]                   CHAR(1),     
    [MANUALFLAG]                         CHAR(1),     
    [TESTPROCFLAG]                       CHAR(1),
    CONSTRAINT [FK_LNKEPSAPPLICATIONSPECS_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);