CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSSPRINGSPACERSPECS] (
    [SPECRID]          NUMERIC(16,0) NOT NULL,  
    [SPRINGSPACERIND]  CHAR(1)     NOT NULL,     
    [PARTNUMBER]       VARCHAR(7) NOT NULL, 
    [THICKNESS]                   NUMERIC(38,2), 
    [QUANTITY]                    NUMERIC(38,0),
    CONSTRAINT [LNKEPSSPRINGSPACERSPECS_PK_LNKEPSSPRINGSPACERSPECS] PRIMARY KEY CLUSTERED ([SPECRID] ASC, [PARTNUMBER] ASC),
    CONSTRAINT [FK_LNKEPSSPRINGSPACERSPECS_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);