CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSREFERENCESPECS1] (
    [SPECRID]                  NUMERIC(16,0)  NOT NULL,
    [DYNAMICAFCONTROLSET]               NUMERIC(38,2), 
    [AIRFUELNOTE]                       VARCHAR(2), 
    [STATICAFLEVERSET]                  NUMERIC(38,2), 
    [FUELVALVEPARTNO]                   VARCHAR(7), 
    [STATTIMINGBTDC]                    NUMERIC(38,2), 
    [ADVANCE]                           NUMERIC(38,1), 
    [UNITINJECTORPARTNO]                VARCHAR(7), 
    [TIMINGDIMENSION]                   NUMERIC(38,2), 
    [TORQUECONTROLPARTNO]               VARCHAR(7), 
    [TORQUECONTROLGROUPCHANGE]          VARCHAR(4), 
    [FILLER]                            VARCHAR(3), 
    [MECHANICALADVANCEPARTNO]           VARCHAR(7), 
    [MECHANICALADVANCEOCC]              VARCHAR(4), 
    [PEECPERSONALITYPARTNO]             VARCHAR(7), 
    [PEECPERSONALITYOCC]                VARCHAR(4), 
    [ADVANCESTART]                      NUMERIC(5),   
    [ADVANCEINTERMEDIATE]               NUMERIC(5),   
    [ADVANCEINTERDEGREES]               NUMERIC(38,1), 
    [ADVANCESTOP]                       NUMERIC(5),   
    [DEGREESOFADVANCE]                  NUMERIC(38,1), 
    [FUELPUMPGOVGROUPPARTNO]            VARCHAR(7), 
    [FUELPUMPTYPE]                      VARCHAR(7), 
    [FUELSYSSETNOTE]                    VARCHAR(2), 
    [GOVERNORTYPE]                      VARCHAR(5), 
    [GOVSPRINGGROUPNO]                  VARCHAR(7), 
    [FLYWEIGHTPARTNUMBER]               VARCHAR(7), 
    [FLYWEIGHTATTITUDE]                 VARCHAR(3),
    CONSTRAINT [FK_LNKEPSREFERENCESPECS1_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);