CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSCOLORSPECS] (
    [SPECRID]            NUMERIC(16,0)      NOT NULL,
    [PARTNUMBER]         VARCHAR(7)      NOT NULL,
    [LANGUAGEINDICATOR]  VARCHAR(2)      NOT NULL,
    -- [COLOR]              NVARCHAR(112.5) NOT NULL, 
    [COLOR]              NVARCHAR(113) NOT NULL, 
    [QUANTITY]                         VARCHAR(2),  
    CONSTRAINT [LNKEPSCOLORSPECS_PK_LNKEPSCOLORSPECS] PRIMARY KEY CLUSTERED ([SPECRID] ASC, [PARTNUMBER] ASC, [COLOR] ASC),
    CONSTRAINT [FK_LNKEPSCOLORSPECS_SR_PN] FOREIGN KEY ([SPECRID], [PARTNUMBER]) REFERENCES [SISWEB_OWNER_STAGING].[LNKEPSSPRINGSPECS] ([SPECRID], [PARTNUMBER])
);