CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSTESTDATASPECS2] (
    [SPECRID]                   NUMERIC(16,0) NOT NULL,  
    [TYPEINDICATOR]             CHAR(1) NOT NULL,     
    [FUELPRESSURE]                      NUMERIC(38,0), 
    [OILPRESSURE]                       NUMERIC(38,0), 
    [OILPRESSURENOTE]                   VARCHAR(2), 
    [OILPRESSURELOWIDLE]                NUMERIC(38,0), 
    [INLETFUELPRESSURE]                 NUMERIC(38,0), 
    [INLETFUELTEMP]                     NUMERIC(38,0), 
    [INLETAIRPRESSURE]                  NUMERIC(38,0), 
    [INLETAIRRESTRICTION]               NUMERIC(38,2), 
    [INLETAIRTEMPERATURE]               NUMERIC(38,1), 
    [FUELDENSITY]                       NUMERIC(38,1), 
    [BOOSTCONSTANT]                     NUMERIC(38,4), 
    [GOVSETTINGCONSTANT]                NUMERIC(38,0), 
    [GOVSETTINGTORQUE]                  NUMERIC(38,0), 
    [THROTTLEANGLE]                     NUMERIC(38,0), 
    [NOX]                               NUMERIC(38,0), 
    [ELECCONTROLFLRPM]                  NUMERIC(38,0), 
    [ELECCONTROLFLPT]                   NUMERIC(38,0), 
    [ELECCONTROLFTORQUERPM]             NUMERIC(38,0), 
    [ELECCONTROLFTORQUEPT]              NUMERIC(38,2), 
    [OILTEMPTOBRGC]                     NUMERIC(38,0), 
    [LOADSCREWSET]                      NUMERIC(38,1), 
    [OBSTORQUEAFSET]                    NUMERIC(38,0), 
    [TORQUEDIFFBRAKESAVER]              NUMERIC(38,0), 
    [TSTAIRPRBRAKESAVER]                NUMERIC(38,0), 
    [TSTOILTEMPBRAKESAVER]              NUMERIC(38,0), 
    [RESPONSECHECKIDLERPM]              NUMERIC(38,0), 
    [RESPONSECHECKIDLETM]               NUMERIC(38,0), 
    [RESPONSECHECKRPM]                  NUMERIC(38,0), 
    [RESPONSECHECKTM]                   NUMERIC(38,0), 
    [RESPONSECHECKPCTTCTORQUE]          NUMERIC(38,1), 
    [TIMINGBTDC]                        NUMERIC(38,2), 
    [FUELOUTTEMP]                       NUMERIC(38,0), 
    [HIGHIDLESTABILITY]                 NUMERIC(38,0), 
    [LOWIDLESTABILITY]                  NUMERIC(38,0), 
    [BLOWBY]                            NUMERIC(38,1), 
    [CFUELRATEATTCSI]                   NUMERIC(38,1), 
    [CORRFUELRATESI]                    NUMERIC(38,1), 
    CONSTRAINT [LNKEPSTESTDATASPECS2_PK_LNKEPSTESTDATASPECS2] PRIMARY KEY CLUSTERED ([SPECRID] ASC, [TYPEINDICATOR] ASC),
    CONSTRAINT [FK_LNKEPSTESTDATASPECS2_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);