CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSPOWERSETPLPPSPECS] (
    [SPECRID]                NUMERIC(16,0) NOT NULL,  
    [POWERSETTINGPLPPREFNO]  VARCHAR(7) NOT NULL, 
    CONSTRAINT [LNKEPSPOWERSETPLPPSPECS_PK_LNKEPSPOWERSETPLPPSPECS] PRIMARY KEY CLUSTERED ([SPECRID] ASC, [POWERSETTINGPLPPREFNO] ASC),
    CONSTRAINT [FK_LNKEPSPOWERSETPLPPSPECS_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);