CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSCERTIFICATIONSPECS] (
    [SPECRID]        NUMERIC(16,0) NOT NULL,  
    [CERTIFICATION]  VARCHAR(4) NOT NULL, 
    CONSTRAINT [LNKEPSCERTIFICATIONSPECS_PK_LNKEPSCERTIFICATIONSPECS] PRIMARY KEY CLUSTERED ([SPECRID] ASC, [CERTIFICATION] ASC),
    CONSTRAINT [FK_LNKEPSCERTIFICATIONSPECS_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);
