CREATE TABLE [SISWEB_OWNER_STAGING].[LNKEPSREFERENCESPECS2] (
    [SPECRID]              NUMERIC(16,0) NOT NULL,    
    [CERTIFICATIONYEAR]             VARCHAR(4),
    [ADVERTISEDPOWER]               NUMERIC(38,1),
    [GOVERNSPEED]                   NUMERIC(38,0),
    [COMPRESSIONRATIO]              NUMERIC(38,1),
    [TORQUERISECAMPARTNO]           VARCHAR(7),
    [TORQRISEATTCNOM]               NUMERIC(38,1),
    [TORQGROUPCHGDATE]              DATETIME2 (0),         
    [TORQCONTROLDESC]               VARCHAR(10), 
    [MANIFOLDTYPE]                  VARCHAR(3),
    [OMITTORQUECHECK]               CHAR(1),    
    [BRAKESAVERTEST]                CHAR(1),    
    [ROTCLKWS]                      CHAR(1),    
    [ENGINESYSVOLT]                 NUMERIC(38,0),
    [FUELPUMPPLUNGER]               NUMERIC(38,0),
    [CONTACTPARTNO]                 VARCHAR(7),
    [USAGEFLAG]                     VARCHAR(7),
    [STATUSCD]                      CHAR(1),    
    [DOGLEGRPMDIFF]                 NUMERIC(38,0),
    [DOGLEGPOWERDIFF]               NUMERIC(38,0),
    [SERVPUBIND]                    CHAR(1),    
    [CURRENTNONCURRENTIND]          CHAR(1),    
    [ENGRMODELNO]                   VARCHAR(10), 
    [ENGRMODELSUBCD]                VARCHAR(2),
    [FACUSAGE]                      VARCHAR(4),
    [TRANSMISSIONTYPE]              VARCHAR(2),
    [VEHICLEDESC]                   VARCHAR(2),
    CONSTRAINT [FK_LNKEPSREFERENCESPECS2_SR] FOREIGN KEY ([SPECRID]) REFERENCES [SISWEB_OWNER_STAGING].[MASEPSSPECS] ([SPECRID])
);

