Create Table [SISWEB_OWNER_STAGING].[LNKFILEDISPLAYTERMS] (
    FILERID             NUMERIC(38)   NOT NULL,
    DISPLAYTYPE         VARCHAR(8)    NOT NULL,
    VALUEDATATYPE       VARCHAR(5)    NULL,
    DISPLAYVALUE        VARCHAR(2000) NULL,
    LANGUAGEINDICATOR   VARCHAR(2)    NOT NULL,
    LASTMODIFIEDDATE    DATETIME2(6)  NULL,
    CONSTRAINT [LNKFILEDISPLAYTERMS_PK_LNKFILEDISPLAYTERMS] PRIMARY KEY CLUSTERED ([FILERID] ASC, [DISPLAYTYPE] ASC, [LANGUAGEINDICATOR] ASC)
);
GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKFILEDISPLAYTERMS] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE INDEX IX_LNKFILEDISPLAYTERMS_FL ON SISWEB_OWNER_STAGING.LNKFILEDISPLAYTERMS (FILERID ASC, LANGUAGEINDICATOR ASC) 
GO