Create Table [SISWEB_OWNER_STAGING].[LNKFILEREPLACEMENTHIERARCHY] (
FILERID             NUMERIC(38)   NOT NULL,
REPLACEDBYFILERID   NUMERIC(38)   NOT NULL,
SEQNO               NUMERIC(16,0) NOT NULL,
LASTMODIFIEDDATE    DATETIME2(6)  NULL,
CONSTRAINT [LNKFILEREPLACEMENTHIERARCHY_PK_LNKFILEREPLACEMENTHIERARCHY] PRIMARY KEY CLUSTERED ([FILERID] ASC, [REPLACEDBYFILERID] ASC)
);
GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKFILEREPLACEMENTHIERARCHY] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO