Create Table [SISWEB_OWNER_STAGING].[LNKFILESEARCHCRITERIA] (
    [ID]       INT       NOT NULL,    
    [FILERID]               [NUMERIC](38)           NOT NULL,
    [INFOTYPEID]            [NUMERIC](3)            NOT NULL,
    [SEARCHRECORDTYPE]      [VARCHAR](8)            NOT NULL,
    [CHARDATA]              [NVARCHAR](1080)        NULL,
    [BEGRANGE]              [NUMERIC](38)           NULL,
    [ENDRANGE]              [NUMERIC](38)           NULL,
    [NUMDATA]               [NUMERIC](38)           NULL,
    [LASTMODIFIEDDATE]      [DATETIME2](6)          NULL,
    CONSTRAINT [PK_LNKFILESEARCHCRITERIA_ID] PRIMARY KEY CLUSTERED ([ID] ASC)
);
GO
CREATE NONCLUSTERED INDEX [IX_LNKFILESEARCHCRITERIA_FILERID]
    ON [SISWEB_OWNER_STAGING].[LNKFILESEARCHCRITERIA]([FILERID] ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKFILESEARCHCRITERIA_CBE ON SISWEB_OWNER_STAGING.LNKFILESEARCHCRITERIA (CHARDATA ASC, BEGRANGE ASC, ENDRANGE ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKFILESEARCHCRITERIA_FIS ON SISWEB_OWNER_STAGING.LNKFILESEARCHCRITERIA (FILERID ASC, INFOTYPEID ASC, SEARCHRECORDTYPE ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKFILESEARCHCRITERIA_ND ON SISWEB_OWNER_STAGING.LNKFILESEARCHCRITERIA (NUMDATA ASC);
GO
