CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIECCRSNP]
(
	[IESYSTEMCONTROLNUMBER] VARCHAR(12)     NOT NULL, 
    [SNP]                   VARCHAR(10)     NOT NULL, 
    [BEGINNINGRANGE]        NUMERIC         NOT NULL, 
    [ENDRANGE]              NUMERIC         NOT NULL, 
    [CCRFLAG]               CHAR(1)         NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL, 
    CONSTRAINT [PK_LNKIECCRSNP] PRIMARY KEY ([IESYSTEMCONTROLNUMBER] ASC, [SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC)
);
GO

CREATE NONCLUSTERED INDEX IX_LNKIECCRSNP_IESCN_CF ON SISWEB_OWNER_STAGING.LNKIECCRSNP (IESYSTEMCONTROLNUMBER ASC, CCRFLAG ASC);
GO
