CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIETITLE] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)    NOT NULL,
    [IELANGUAGEINDICATOR]   VARCHAR (2)     NOT NULL,
    [IETITLE]               NVARCHAR (3072) NOT NULL,
    [IECONTROLNUMBER]       VARCHAR (12)    NULL,
    [IERID]                 NUMERIC (16)    NULL,
    [GROUPTITLEINDICATOR]   VARCHAR (1)     NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6)   NULL,
	ENGLISHCONTROLNUMBER    VARCHAR (12)    NULL
    CONSTRAINT [CK_LIT_GROUPTITLEINDICATOR] CHECK (GROUPTITLEINDICATOR in ('Y','N')),
    CONSTRAINT [LNKIETITLE_PK_LNKIETITLE] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [IELANGUAGEINDICATOR] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKIETITLE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_LNKIETITLE_ISCN_IELI ON SISWEB_OWNER_STAGING.LNKIETITLE (IESYSTEMCONTROLNUMBER ASC, IELANGUAGEINDICATOR ASC) ;
GO

CREATE UNIQUE NONCLUSTERED INDEX UK_LNKIETITLE_IERID ON SISWEB_OWNER_STAGING.LNKIETITLE (IERID ASC)
WHERE IERID IS NOT NULL;
GO
