CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEDATE] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [DATEUPDATED]           DATETIME2 (0) NOT NULL,
    [IEPUBDATE]             DATETIME2 (0) NOT NULL,
    [LANGUAGEINDICATOR]     VARCHAR (2)   NOT NULL,
    [IERID]                 NUMERIC (16)  NULL,
    [LASTMODIFIEDDATE]      VARCHAR (50)  NULL,
    CONSTRAINT [LNKIEDATE_PK_LNKIEDATE] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [DATEUPDATED] ASC, [IEPUBDATE] ASC, [LANGUAGEINDICATOR] ASC)
);
GO

ALTER TABLE [SISWEB_OWNER_STAGING].[LNKIEDATE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_LNKIEDATE_ISCN_IPD ON SISWEB_OWNER_STAGING.LNKIEDATE (IESYSTEMCONTROLNUMBER ASC, IEPUBDATE ASC);
GO

CREATE UNIQUE NONCLUSTERED INDEX UK_LNKIEDATE_IERID ON SISWEB_OWNER_STAGING.LNKIEDATE (IERID ASC)
WHERE IERID IS NOT NULL;
GO
