CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEDATEHTML5] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [DATEUPDATED]           DATETIME2 (0) NOT NULL,
    [IEPUBDATE]             DATETIME2 (0) NOT NULL,
    [LANGUAGEINDICATOR]     VARCHAR (2)   NOT NULL,
    [IERID]                 NUMERIC (16)  NULL,
    [LASTMODIFIEDDATE]      VARCHAR (50)  NULL,
    CONSTRAINT [LNKIEDATEHTML5_PK_LNKIEDATE] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [DATEUPDATED] ASC, [IEPUBDATE] ASC, [LANGUAGEINDICATOR] ASC)
);


GO


GO

