CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEADAPTABLESNP]
(
	[IESYSTEMCONTROLNUMBER] VARCHAR(12)     NOT NULL, 
    [SNP]                   VARCHAR(10)     NOT NULL, 
    [EFFBEGINNINGRANGE]     NUMERIC         NOT NULL, 
    [EFFENDRANGE]           NUMERIC         NOT NULL, 
    [REQBEGINNINGRANGE]     NUMERIC         NOT NULL, 
    [REQENDRANGE]           NUMERIC         NOT NULL, 
    [CCRFLAG]               CHAR(1)         NOT NULL DEFAULT 'O',
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_LNKIEADAPTABLESNP] PRIMARY KEY ([IESYSTEMCONTROLNUMBER] ASC, [SNP] ASC, [EFFBEGINNINGRANGE] ASC, [EFFENDRANGE] ASC, [REQBEGINNINGRANGE] ASC, [REQENDRANGE] ASC)
);