CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIELEVEL]
  (
     [IESYSTEMCONTROLNUMBER]  [VARCHAR](12) NOT NULL,
     [LEVELSEQUENCENUMBER]    [SMALLINT] NOT NULL,
     [LEVELLANGUAGEINDICATOR] [VARCHAR](2) NOT NULL,
     [LEVELID]                [SMALLINT] NOT NULL,
     [LEVELDESCRIPTION]       [NVARCHAR](3072) NOT NULL,
     [PARENTID]               [INT] NULL,
     [LASTMODIFIEDDATE]       DATETIME2(6) NULL,
     CONSTRAINT [PK_LNKIELEVEL] PRIMARY KEY CLUSTERED ( [IESYSTEMCONTROLNUMBER]
     ASC, [LEVELSEQUENCENUMBER] ASC, [LEVELLANGUAGEINDICATOR] ASC )
  );
GO
