CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEMEDIAPART]
(
	[IESYSTEMCONTROLNUMBER] VARCHAR(12) NOT NULL, 
    [SNP] VARCHAR(10) NULL, 
    [BEGINNINGRANGE] INT NULL, 
    [ENDRANGE] INT NULL, 
    [MEDIANUMBER] VARCHAR(8) NOT NULL, 
    [PARTNUMBER] VARCHAR(20) NULL, 
    [LASTMODIFIEDDATE] DATETIME2(6) NULL
)
