CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEINFOTYPE] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [INFOTYPEID]            SMALLINT      NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [PKCI_LNKIEINFOTYPE] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [INFOTYPEID] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKIEINFOTYPE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_LNKIEINFOTYPE_ISCN ON SISWEB_OWNER_STAGING.LNKIEINFOTYPE (IESYSTEMCONTROLNUMBER ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKIEINFOTYPE_IT ON SISWEB_OWNER_STAGING.LNKIEINFOTYPE (INFOTYPEID ASC);
GO