CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEPSID](
	[MEDIANUMBER] [varchar](8) NOT NULL,
	[IESYSTEMCONTROLNUMBER] [varchar](12) NOT NULL,
	[PSID] [varchar](8) NOT NULL
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IDX_LNKIEPSID_MEDIANUMBER_IESYSTEMCONTROLNUMBER] ON [SISWEB_OWNER_STAGING].[LNKIEPSID] ([MEDIANUMBER],[IESYSTEMCONTROLNUMBER]) INCLUDE ([PSID]);
GO

