CREATE TABLE [SISWEB_OWNER_STAGING].[LNKIEORIGINALPSID] (
    [MEDIANUMBER]      VARCHAR (8)   NOT NULL,
    [IESCN]            VARCHAR (12)  NOT NULL,
    [PSID]             VARCHAR (8)   NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [LNKIEORIGINALPSID_PK_LNKIEORIGINALPSID] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESCN] ASC, [PSID] ASC)
);

