CREATE TABLE [SISWEB_OWNER_STAGING].[LNKMEDIASNP] (
    [MEDIANUMBER]      VARCHAR (8)   NOT NULL,
    [SNP]              VARCHAR (10)  NOT NULL,
    [BEGINNINGRANGE]   INT           NOT NULL,
    [ENDRANGE]         INT           NOT NULL,
    [INFOTYPEID]       SMALLINT      NOT NULL,
    [TYPEINDICATOR]    VARCHAR (1)   NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [LNKMEDIASNP_PK_LNKMEDIASNP] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC, [INFOTYPEID] ASC, [TYPEINDICATOR] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKMEDIASNP] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_SISWEB_OWNER_STAGING_LNKMEDIASNP_INFOTYPEID
ON [SISWEB_OWNER_STAGING].[LNKMEDIASNP] ([INFOTYPEID]);
GO

CREATE NONCLUSTERED INDEX  IX_SISWEB_OWNER_STAGING_LNKMEDIASNP_SNP_INFOTYPEID_BEGINNINGRANGE_ENDRANGE
ON [SISWEB_OWNER_STAGING].[LNKMEDIASNP] ([SNP],[INFOTYPEID],[BEGINNINGRANGE],[ENDRANGE]);
GO

CREATE NONCLUSTERED INDEX IX_LNKMEDIASNP_MEDIANUMBER 
ON SISWEB_OWNER_STAGING.LNKMEDIASNP (MEDIANUMBER ASC);
GO

CREATE NONCLUSTERED INDEX IX_LNKMEDIASNP_SNP_TI_ITI 
ON SISWEB_OWNER_STAGING.LNKMEDIASNP (SNP ASC, TYPEINDICATOR ASC, INFOTYPEID ASC);
GO
