CREATE TABLE [SISWEB_OWNER_STAGING].[LNKMEDIAIEMICROFICHE] (
[IERID]         NUMERIC (16) NOT NULL,
[MEDIARID]      NUMERIC (16) NOT NULL,
[MEDIANUMBER]   CHAR (8) NOT NULL,
[REVISIONNO]    NUMERIC (5) NOT NULL,
[ARTICLENUMBER] VARCHAR (3) NOT NULL,
[FICHENUMBER]   VARCHAR (3) NOT NULL,
[GRIDLOCATION]  VARCHAR (3) NOT NULL,
[FILERID]               NUMERIC(16),
CONSTRAINT [PK_LNKMEDIAIEMICROFICHE] PRIMARY KEY NONCLUSTERED ([IERID] ASC)
);
