CREATE TABLE [SISWEB_OWNER_STAGING].[LNKMEDIAARRANGEMENT] (
    [MEDIANUMBER]      VARCHAR (8)   NOT NULL,
    [ARRANGEMENTNO]    VARCHAR (20)  NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [LNKMEDIAARRANGEMENT_PK_LNKMEDIAARRANGEMENT] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [ARRANGEMENTNO] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKMEDIAARRANGEMENT] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_LNKMEDIAARRANGEMENT_AN 
ON SISWEB_OWNER_STAGING.LNKMEDIAARRANGEMENT (ARRANGEMENTNO ASC);
GO