CREATE TABLE [SISWEB_OWNER_STAGING].[LNKNPRINFO_SWAP] (
    [PARTNUMBER]               VARCHAR (20)  NOT NULL,
    [COUNTRYCODE]              VARCHAR (1)   NOT NULL,
    [ENGGCHANGELEVELNO]        VARCHAR (2)   NOT NULL,
    [PRIMARYSEQNO]             INT           NOT NULL,
    [PARTNUMBERDESCRIPTION]    VARCHAR (200) NULL,
    [NONRETURNABLEINDICATOR]   VARCHAR (1)   NULL,
    [PARTREPLACEMENTINDICATOR] VARCHAR (1)   NULL,
    [PACKAGEQUANTITY]          VARCHAR (8)   NULL,
    [WEIGHT]                   INT           NULL,
    [CANCELLEDNPRINFORMATION]  VARCHAR (20)  NULL,
    [NPRINDICATOR]             VARCHAR (20)  NULL,
    CONSTRAINT [LNKNPRINFO_SWAP_PK_LNKNPRINFO_SWAP] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC, [COUNTRYCODE] ASC, [ENGGCHANGELEVELNO] ASC, [PRIMARYSEQNO] ASC)
);
GO

CREATE NONCLUSTERED INDEX IX_LNKNPRINFO_PARTNUMBER_SWAP ON SISWEB_OWNER_STAGING.LNKNPRINFO_SWAP (PARTNUMBER ASC);
GO 

CREATE NONCLUSTERED INDEX IX_LNKNPRINFO_PSN_SWAP ON SISWEB_OWNER_STAGING.LNKNPRINFO_SWAP (PRIMARYSEQNO ASC);
GO