CREATE TABLE [SISWEB_OWNER_STAGING].[LNKNPRINFORECTYPE456_SWAP] (
    [PRIMARYSEQNO]             INT          NOT NULL,
    [RECORDTYPE]               VARCHAR (1)  NOT NULL,
    [SEQUENCENUMBER]           INT          NOT NULL,
    [COLUMNDATA]               VARCHAR (64) NULL,
    [QUANTITYRECTYPE5]         SMALLINT     NULL,
    [SERIALNUMBERSYMBOL]       VARCHAR (1)  NULL,
    [SERIALNUMBERPREFIX]       VARCHAR (4)  NULL,
    [EFFECTIVESERIALNUMBER]    VARCHAR (5)  NULL,
    [DISCONTINUEDSERIALNUMBER] VARCHAR (5)  NULL,
    [QUANTITYRECTYPE6]         SMALLINT     NULL,
    [GROUPNUMBER]              VARCHAR (10) NULL,
    [ENGINEERINGCHANGE]        VARCHAR (5)  NULL,
    [NPRINDICATOR]             VARCHAR (20) NULL,
    CONSTRAINT [LNKNPRINFORECTYPE456_SWAP_PK_LNKNPRINFORECTYPE456_SWAP] PRIMARY KEY CLUSTERED ([PRIMARYSEQNO] ASC, [RECORDTYPE] ASC, [SEQUENCENUMBER] ASC)
);
GO

CREATE NONCLUSTERED INDEX IX_LNIRT456_PSN_SWAP ON SISWEB_OWNER_STAGING.LNKNPRINFORECTYPE456_SWAP (PRIMARYSEQNO ASC);
GO
