CREATE TABLE [SISWEB_OWNER_STAGING].[LNKPARTSIESNP] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [SNP]                   VARCHAR (10)  NOT NULL,
    [BEGINNINGRANGE]        INT           NOT NULL,
    [ENDRANGE]              INT           NOT NULL,
    [SNPTYPE]               VARCHAR (6)   NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKPARTSIESNP_PK_LNKPARTSIESNP] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC, [SNPTYPE] ASC)
);
GO

ALTER TABLE [SISWEB_OWNER_STAGING].[LNKPARTSIESNP] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX [IDX_LNKPARTSIESNP_SNP_MEDIANUMBER_IESYSTEMCONTROLNUMBER] ON [SISWEB_OWNER_STAGING].[LNKPARTSIESNP] ([SNP],[MEDIANUMBER],[IESYSTEMCONTROLNUMBER]);
GO
