CREATE TABLE [SISWEB_OWNER_STAGING].[LNKPARTNAMESSOURCE]
(
	[PARTNAME]          NVARCHAR(288)   NOT NULL, 
    [LANGUAGEINDICATOR] VARCHAR(2)      NOT NULL, 
    [SPNRID]            NUMERIC(16)     NOT NULL,
    [LASTMODIFIEDDATE]  DATETIME2(6)    NULL, 
    CONSTRAINT [PK_LNKPARTNAMESSOURCE] PRIMARY KEY ([PARTNAME] ASC, [LANGUAGEINDICATOR] ASC, [SPNRID] ASC)
);
