CREATE TABLE [SISWEB_OWNER_STAGING].[LNKPARTINFORMATION] (
    [PARTNUMBER]   VARCHAR (20) NOT NULL,
    [NPRINDICATOR] VARCHAR (1)  NOT NULL,
    CONSTRAINT [LNKPARTINFORMATION_PK_LNKPARTINFORMATION] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC)
);
