CREATE TABLE [SISWEB_OWNER_STAGING].[LNKRELATEDPARTINFO] (
    [PARTNUMBER]        VARCHAR (20)  NOT NULL,
    [TYPEINDICATOR]     VARCHAR (2)   NOT NULL,
    [RELATEDPARTNUMBER] VARCHAR (20)  NOT NULL,
    [RELATEDPARTNAME]   VARCHAR (256) NULL,
    [NPRINDICATOR]      VARCHAR (1)   NULL,
    [RELATION_TYPE]     VARCHAR (50) NULL,
    [LASTMODIFIEDDATE]  DATETIME2 (6) NULL,
    CONSTRAINT [LNKRELATEDPARTINFO_PK_LNKRELATEDPARTINFO] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC, [TYPEINDICATOR] ASC, [RELATEDPARTNUMBER] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[LNKRELATEDPARTINFO] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

