CREATE TABLE [SISWEB_OWNER_STAGING].[LNKRELATEDPARTIES] (
    [IESCN]            VARCHAR (12) NOT NULL,
    [RELATEDIESCN]     VARCHAR (12) NOT NULL,
    [LASTMODIFIEDDATE] VARCHAR (50) NULL,
    CONSTRAINT [PK_LNKRELATEDPARTIES] PRIMARY KEY CLUSTERED ([IESCN] ASC, [RELATEDIESCN] ASC)
);

