CREATE TABLE [SISWEB_OWNER_STAGING].LNKSNPDETAILS
(
    SNP	VARCHAR(3) NOT NULL,
    COMPONENTTYPE	VARCHAR(50) NOT NULL,
    SALESMODELNO	VARCHAR(30) NOT NULL,
    PRODUCTNAME	VARCHAR(50) NOT NULL,
    PRODUCTCODE	VARCHAR(4) NOT NULL,
    ENGRGMODELNO	VARCHAR(8) NOT NULL,
    FIRSTSHIPDATE	DATE NOT NULL
)

GO

CREATE INDEX IDX_LNKSPDTL_SNP ON [SISWEB_OWNER_STAGING].[LNKSNPDETAILS] (SNP)
GO

CREATE INDEX IDX_LNKSPDTL_FSDATE ON [SISWEB_OWNER_STAGING].[LNKSNPDETAILS] (FIRSTSHIPDATE)
GO

CREATE NONCLUSTERED INDEX [IX_LNKSNPDETAILS_PRODUCTCODE]ON [SISWEB_OWNER_STAGING].[LNKSNPDETAILS] ([PRODUCTCODE])
INCLUDE ([SNP],[SALESMODELNO],[PRODUCTNAME],[ENGRGMODELNO])
GO