CREATE TABLE [SISWEB_OWNER_STAGING].[LNKSERIALPART](
	[SERIALNUMBER] [varchar](8) NULL,
	[FUELSPECIFICATIONNO] [varchar](8) NULL,
	[ARRANGEMENTPARTNUMBER] [varchar](20) NOT NULL,
	[ENGINEERINGMODELNO] [varchar](10) NULL,
	[SHIPDATE] [datetime2](0) NULL
) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX IX_LNKSERIALPART_SN 
ON SISWEB_OWNER_STAGING.LNKSERIALPART (SERIALNUMBER ASC);
GO