CREATE TABLE [SISWEB_OWNER_STAGING].[LNKSAFETY](
	[PRODUCTCODE] [varchar](8) NOT NULL,
	[MEDIANUMBER] [varchar](20) NOT NULL,
    LANGUAGEINDICATOR [varchar](2) NOT NULL,
    CONSTRAINT [PK_LNKSAFETY_SWAP] PRIMARY KEY NONCLUSTERED ([PRODUCTCODE] ASC,[MEDIANUMBER] ASC)
)
