CREATE TABLE [SISWEB_OWNER_STAGING].[LNKTRANSLATEDSPN](
	[PARTNAME] [varchar](200) NOT NULL,
	[LANGUAGEINDICATOR] [varchar](2) NOT NULL,
	[TRANSLATEDPARTNAME] [nvarchar](200) NOT NULL
) ON [PRIMARY]

