CREATE TABLE [SISWEB_OWNER_STAGING].[MASCCRUPDATETYPES]
(
	[UPDATETYPEINDICATOR]   CHAR(1)         NOT NULL, 
    [LANGUAGEINDICATOR]     VARCHAR(2)      NOT NULL, 
    [UPDATETYPEDESCRIPTION] NVARCHAR(225)   NOT NULL, 
    [SEQUENCENUMBER]        NUMERIC(5)      NOT NULL, 
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL, 
    CONSTRAINT [PK_MASCCRUPDATETYPES] PRIMARY KEY ([UPDATETYPEINDICATOR] ASC, [LANGUAGEINDICATOR] ASC)
);
