CREATE TABLE [SISWEB_OWNER_STAGING].[MASCCROPERATIONS]
(
	[OPERATIONRID]          NUMERIC(10)     NOT NULL ,
    [SEGMENTRID]            NUMERIC(10)     NOT NULL,
    [OPERATION]             VARCHAR(5)      NOT NULL,
    [COMPONENTCODE]         VARCHAR(4)      NOT NULL,
    [JOBCODE]               VARCHAR(3)      NOT NULL,
    [MODIFIERCODE]          VARCHAR(3)      NULL,
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_MASCCROPERATIONS] PRIMARY KEY ([OPERATIONRID] ASC)
);
GO
ALTER TABLE [SISWEB_OWNER_STAGING].[MASCCROPERATIONS] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_MASCCROPERATIONS_SRID_ORID ON SISWEB_OWNER_STAGING.MASCCROPERATIONS (SEGMENTRID ASC, OPERATIONRID ASC);
GO
