CREATE TABLE [SISWEB_OWNER_STAGING].[MASCCRSEGMENTS]
(
	[SEGMENTRID]			NUMERIC(10)		NOT NULL,
	[CCRMEDIARID]			NUMERIC(10)		NOT NULL,
	[SEGMENT]				VARCHAR(5)		NOT NULL,
	[COMPONENTCODE]			VARCHAR(4)		NOT NULL,
	[JOBCODE]				VARCHAR(3)		NOT NULL,
	[MODIFIERCODE]			VARCHAR(3)		NULL,
	[HOURS]					NUMERIC(6,1)	NOT NULL,
	[LASTMODIFIEDDATE]      DATETIME2(6)    NULL, 
	CONSTRAINT [PK_MASCCRSEGMENTS] PRIMARY KEY ([SEGMENTRID] ASC)
);
GO
ALTER TABLE [SISWEB_OWNER_STAGING].[MASCCRSEGMENTS] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX IX_MASCCRSEGMENTS_MRID_SRID ON SISWEB_OWNER_STAGING.MASCCRSEGMENTS (CCRMEDIARID ASC, SEGMENTRID ASC);
GO

