Create Table [SISWEB_OWNER_STAGING].[MASFILEPROPERTIES] ( 
	[FILERID]           [NUMERIC](38)	    NOT NULL,
	[INFOTYPEID]        [NUMERIC](3)		NOT NULL,
	[FILENAME]          [VARCHAR](100)      NULL,
	[AVAILABLEFLAG]     [VARCHAR](1)        NOT NULL,
	[MIMETYPE]          [VARCHAR](2)        NULL,
    [FILESIZE]          [INT]               NULL,
	[UPDATEDDATE]       [DATETIME2](0)      NULL,
	[CREATEDDATE]       [DATETIME2](0)      NULL,
	[LASTMODIFIEDDATE]  [DATETIME2](6)      NULL,
    CONSTRAINT [MASFILEPROPERTIES_PK_MASFILEPROPERTIES] PRIMARY KEY CLUSTERED ([FILERID] ASC)
);
GO
ALTER TABLE [SISWEB_OWNER_STAGING].[MASFILEPROPERTIES] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE INDEX IX_MASFILEPROPERTIES_FIF ON SISWEB_OWNER_STAGING.MASFILEPROPERTIES (FILERID ASC, INFOTYPEID ASC, AVAILABLEFLAG ASC) 
GO