CREATE TABLE [SISWEB_OWNER_STAGING].[MASINFOTYPE](
	[INFOTYPEID] [numeric](3, 0) NOT NULL,
	[LANGUAGEINDICATOR] [varchar](2) NOT NULL,
	[INFOTYPE] [varchar](8) NOT NULL,
	[INFORMATIONTYPEDESC] [nvarchar](720) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

