CREATE TABLE [SISWEB_OWNER_STAGING].[MASIECONTENT](
  [IESYSTEMCONTROLNUMBER] VARCHAR(12) NOT NULL, 
  [LANGUAGEINDICATOR]     VARCHAR(2)  NOT NULL, 
  [IECONTENTTYPE]         CHAR(1)     NOT NULL, 
  [IERID]                 NUMERIC(16, 0),
  CONSTRAINT [PK_MASIECONTENT_ISCN_LI] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [LANGUAGEINDICATOR] ASC),
);
GO

CREATE NONCLUSTERED INDEX UK_MASIECONTENT_IERID ON SISWEB_OWNER_STAGING.MASIECONTENT (IERID ASC);
GO
