CREATE TABLE [SISWEB_OWNER_STAGING].[MASIECONTENTHTML5] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [LANGUAGEINDICATOR]     VARCHAR (2)   NOT NULL,
    [IECONTROLNUMBER]       VARCHAR (12)  NOT NULL,
    CONSTRAINT [MASIECONTENTHTML5_PK] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [LANGUAGEINDICATOR] ASC, [IECONTROLNUMBER] ASC) WITH (FILLFACTOR = 100)
);

