CREATE TABLE [SISWEB_OWNER_STAGING].[MASMEDIAHTML5] (
    [MEDIANUMBER]             VARCHAR (8)      NOT NULL,
    [MEDIATITLE]              NVARCHAR (1536)  NOT NULL,
    [PUBLISHEDDATE]           DATETIME2 (0)    NOT NULL,
    [MEDIAUPDATEDDATE]        DATETIME2 (0)    NULL,
    [MEDIASOURCE]             VARCHAR (1)      NOT NULL,
    [REVISIONNO]              NUMERIC (38, 10) NULL,
    [SAFETYDOCUMENTINDICATOR] VARCHAR (1)      NOT NULL,
    [BASEENGLISHMEDIANUMBER]  VARCHAR (8)      NOT NULL,
    [NPRMEDIAREFERENCE]       VARCHAR (8)      NULL,
    [PIPPSPNUMBER]            VARCHAR (7)      NULL,
    [LANGUAGEINDICATOR]       VARCHAR (2)      NOT NULL,
    [MEDIARID]                NUMERIC (16)     NULL,
    [LASTMODIFIEDDATE]        DATETIME2 (6)    NULL,
    [MEDIAORIGIN]             VARCHAR (2)      NULL,
    CONSTRAINT [MASMEDIA_PK_MASMEDIAHTML5] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC) WITH (FILLFACTOR = 100)
);




GO

GO

