CREATE TABLE [SISWEB_OWNER_STAGING].[MASPRODUCTSTRUCTURE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTSTRUCTUREID] [char](8) NOT NULL,
	[LANGUAGEINDICATOR] [varchar](2) NOT NULL,
	[PARENTPRODUCTSTRUCTUREID] [char](8) NOT NULL,
	[PRODUCTSTRUCTUREDESCRIPTION] [nvarchar](192) NOT NULL,
	[PARENTAGE] [numeric](1, 0) NOT NULL,
	[MISCSPNINDICATOR] [char](1) NOT NULL
) ON [PRIMARY]

