CREATE TABLE [SISWEB_OWNER_STAGING].[MASPRODUCT](
	[PRODUCTCODE] [varchar](4) NOT NULL,
	[SEQUENCENUMBER] [numeric](3, 0) NOT NULL,
	[LANGUAGEINDICATOR] [varchar](2) NOT NULL,
	[PRODUCTTYPE] [char](1) NOT NULL,
	[PRODUCTDESCRIPTION] [nvarchar](600) NOT NULL,
	[FREQUENCY] [char](1) NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
    CONSTRAINT [MASPRODUCT_PK_MASPRODUCT] PRIMARY KEY CLUSTERED ([PRODUCTCODE] ASC, [SEQUENCENUMBER] ASC, [LANGUAGEINDICATOR] ASC)
);
GO

CREATE NONCLUSTERED INDEX IX_MASPRODUCT_PC_SN 
ON SISWEB_OWNER_STAGING.MASPRODUCT (PRODUCTCODE ASC, SEQUENCENUMBER ASC);
GO
