CREATE TABLE [SISWEB_OWNER_STAGING].[MASSMCS](
	[SMCSCOMPCODE] [char](4) NOT NULL,
	[LANGUAGEINDICATOR] [varchar](2) NOT NULL,
	[MAJORDIVISIONCODE] [char](4) NOT NULL,
	[SMCSDESCRIPTION] [nvarchar](192) NOT NULL,
	[CURRENTINDICATOR] [char](1) NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL
) ON [PRIMARY]

