CREATE TABLE [SISWEB_OWNER_STAGING].[MV_KITBOM](
	[KITPARTNUMBER] [varchar](20) NOT NULL,
	[KITPARTNAME] [varchar](200) NOT NULL,
	[COMPONENTPARTNUMBER] [varchar](20) NOT NULL,
	[COMPONENTPARTNAME] [varchar](200) NOT NULL,
	[QUANTITY] [numeric](10, 0) NOT NULL
) ON [PRIMARY]

