CREATE TABLE [SISWEB_OWNER_STAGING].[PART_SUPERSESSIONCHAIN](
	[PART_SUPERSESSIONCHAIN_ID] [int] IDENTITY(1,1) NOT NULL,
	[PARTNUMBER] [varchar](40) NOT NULL,
	[CHAIN] [varchar](4000) NOT NULL,
 	CONSTRAINT [PK_PART_SUPERSESSIONCHAIN_PARTNUMBER] PRIMARY KEY CLUSTERED ([PART_SUPERSESSIONCHAIN_ID] ASC)
  )
GO
