CREATE TABLE [SISWEB_OWNER_STAGING].[PROD_CNFGR_SN_REL] (
    [SER_NO_PFX]         VARCHAR (3)   NOT NULL,
    [XTRNL_SER_NO_BDY]   VARCHAR (17)  NOT NULL,
    [MFR_CD]             VARCHAR (4)   NOT NULL,
    [REL_SER_NO_PFX]     VARCHAR (3)   NOT NULL,
    [XTRNL_REL_SN_BDY]   VARCHAR (17)  NOT NULL,
    [REL_MFR_CD]         VARCHAR (4)   NOT NULL,
    [ARR_NO]             VARCHAR (7)   NOT NULL,
    [ARR_NO_CLS_CD]      VARCHAR (1)   NOT NULL,
    [PROD_REF_NO]        VARCHAR (10)  NOT NULL,
    [PROD_REF_NO_CLS_CD] VARCHAR (1)   NOT NULL,
    [PRODTN_DT]          DATE          NOT NULL,
    [INSTL_DT]           DATE          NOT NULL,
    [INSTL_IND]          VARCHAR (1)   NOT NULL,
    [RCD_SRC_IND]        VARCHAR (2)   NOT NULL,
    [DUP_RCD_IND]        VARCHAR (1)   NOT NULL,
    [CRTE_DT]            DATE          NOT NULL,
    [LAST_UPDT_DT]       DATE          NOT NULL,
    [LAST_UPDT_CWS_ID]   VARCHAR (30)  NOT NULL,
    [CMPNT_TYP]          VARCHAR (2)   NOT NULL,
    [CATEGORY_DESC]      VARCHAR (30)  NOT NULL,
    [CATEGORY_TYPE]      VARCHAR (30)  NOT NULL,
    [REPLACED_BY_SN]     VARCHAR (20)  NOT NULL,
    [ORIG_CCR_SN]        VARCHAR (20)  NOT NULL,
    [COMMENTS]           VARCHAR (200) NOT NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PROD_CNFGR_SN_REL_I1JIA010]
    ON [SISWEB_OWNER_STAGING].[PROD_CNFGR_SN_REL]([SER_NO_PFX] ASC, [XTRNL_SER_NO_BDY] ASC, [MFR_CD] ASC, [REL_SER_NO_PFX] ASC, [XTRNL_REL_SN_BDY] ASC, [REL_MFR_CD] ASC);

