CREATE TABLE [SISWEB_OWNER_STAGING].[PROD_CNFGR_ATT] (
    [SER_NO_PFX]        VARCHAR (3)   NOT NULL,
    [XTRNL_SER_NO_BDY]  VARCHAR (17)  NOT NULL,
    [MFR_CD]            VARCHAR (4)   NOT NULL,
    [REL_SER_NO_PFX]    VARCHAR (3)   NOT NULL,
    [XTRNL_REL_SN_BDY]  VARCHAR (17)  NOT NULL,
    [REL_MFR_CD]        VARCHAR (4)   NOT NULL,
    [ATT_TYP]           VARCHAR (2)   NOT NULL,
    [PROD_REF_NO]       VARCHAR (10)  NOT NULL,
    [ATT_TYP_2]         VARCHAR (2)   NOT NULL,
    [PROD_REF_NO_2]     VARCHAR (10)  NOT NULL,
    [ATT_TYP_3]         VARCHAR (2)   NOT NULL,
    [PROD_REF_NO_3]     VARCHAR (10)  NOT NULL,
    [PROD_REF_CLS_CD]   VARCHAR (1)   NOT NULL,
    [PROD_REF_CLS_CD_2] VARCHAR (1)   NOT NULL,
    [PROD_REF_CLS_CD_3] VARCHAR (1)   NOT NULL,
    [INSTL_DT]          DATE          NOT NULL,
    [INSTL_IND]         VARCHAR (1)   NOT NULL,
    [ENG_CHG_LVL]       VARCHAR (2)   NOT NULL,
    [RCD_SRC_IND]       VARCHAR (2)   NOT NULL,
    [CRTE_DT]           DATE          NOT NULL,
    [LAST_UPDT_DT]      DATE          NOT NULL,
    [LAST_UPDT_CWS_ID]  VARCHAR (30)  NOT NULL,
    [COMMENTS]          VARCHAR (200) NOT NULL,
    [LASTMODIFIEDDATE]  DATETIME2 (6) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PROD_CNFGR_ATT_I1JIA009]
    ON [SISWEB_OWNER_STAGING].[PROD_CNFGR_ATT]([SER_NO_PFX] ASC, [XTRNL_SER_NO_BDY] ASC, [MFR_CD] ASC, [REL_SER_NO_PFX] ASC, [XTRNL_REL_SN_BDY] ASC, [REL_MFR_CD] ASC, [ATT_TYP] ASC, [PROD_REF_NO] ASC, [ATT_TYP_2] ASC, [PROD_REF_NO_2] ASC, [ATT_TYP_3] ASC, [PROD_REF_NO_3] ASC);

