CREATE TABLE [SISWEB_OWNER_STAGING].[PROD_CNFGR_DESC] (
    [PROD_REF_NO]        VARCHAR (10)  NOT NULL,
    [PROD_REF_CLS_CD]    VARCHAR (1)   NOT NULL,
    [PROD_REF_NO_DESC_S] VARCHAR (18)  NOT NULL,
    [PROD_REF_NO_DESC_L] VARCHAR (30)  NOT NULL,
    [CRTE_DT]            DATE          NOT NULL,
    [LAST_UPDT_DT]       DATE          NOT NULL,
    [LAST_UPDT_CWS_ID]   VARCHAR (30)  NOT NULL,
    [COMMENTS]           VARCHAR (200) NOT NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [PROD_CNFGR_DESC_I1JIA011]
    ON [SISWEB_OWNER_STAGING].[PROD_CNFGR_DESC]([PROD_REF_NO] ASC);

