CREATE TABLE [SISWEB_OWNER_STAGING].[PROD_CNFGR_DLET] (
    [LAST_UPDT_DT]     DATE          NOT NULL,
    [SER_NO_PFX]       VARCHAR (3)   NOT NULL,
    [XTRNL_SER_NO_BDY] VARCHAR (17)  NOT NULL,
    [LAST_UPDT_CWS_ID] VARCHAR (30)  NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [PROD_CNFGR_DLET_PROD_CNFGR_DLET_PK] PRIMARY KEY CLUSTERED ([LAST_UPDT_DT] ASC, [SER_NO_PFX] ASC, [XTRNL_SER_NO_BDY] ASC)
);

