CREATE TABLE [SISWEB_OWNER_STAGING].[SIS2ASSHIPPEDENGINE] (
    [SERIALNUMBER]       VARCHAR (8)   NOT NULL,
    [PARTSEQUENCENUMBER] NUMERIC (10)  NOT NULL,
    [PARTNUMBER]         VARCHAR (20)  NULL,
    [PARTNAME]           VARCHAR (512) NULL,
    [QUANTITY]           VARCHAR (8)   NULL,
    [ENGGCHANGELEVELNO]  VARCHAR (4)   NULL,
    [ASSEMBLY]           VARCHAR (1)   NULL,
    [LESSINDICATOR]      VARCHAR (1)   NULL,
    [INDENTATION]        VARCHAR (1)   NULL,
    [UPDATEDATETIME]     DATETIME2 (6) NULL,
    CONSTRAINT [SIS2ASSHIPPEDENGINE_SIS2ASSHIPPEDENGINE_PK] PRIMARY KEY CLUSTERED ([SERIALNUMBER] ASC, [PARTSEQUENCENUMBER] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[SIS2ASSHIPPEDENGINE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

CREATE NONCLUSTERED INDEX [SIS2ASSHIPPEDENGINE_PARTNUMBER_NC]
    ON [SISWEB_OWNER_STAGING].[SIS2ASSHIPPEDENGINE]([SERIALNUMBER] ASC, [PARTNUMBER] ASC);
GO