CREATE TABLE [SISWEB_OWNER_STAGING].[SIS2IEBLOBLOCATIONHTML5] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [LANGUAGEINDICATOR]     VARCHAR (2)   NOT NULL,
    [MIMETYPE]              VARCHAR (50)  NOT NULL,
    [LOCATION]              VARCHAR (50)  NOT NULL,
    [UPDATEDATETIME]        DATETIME2 (6) NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [SIS2IEBLOBLOCATIONHTML5_SIS2IEBLOBLOCATIONHTML5_PK] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [LANGUAGEINDICATOR] ASC) WITH (FILLFACTOR = 100)
);




GO

GO

