CREATE TABLE [SISWEB_OWNER_STAGING].[SIS2IEBLOBLOCATION] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [LANGUAGEINDICATOR]     VARCHAR (2)   NOT NULL,
    [MIMETYPE]              VARCHAR (50)  NOT NULL,
    [LOCATION]              VARCHAR (50)  NOT NULL,
    [UPDATEDATETIME]        DATETIME2 (6) NOT NULL,
    [FILESIZEBYTE]          INT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [SIS2IEBLOBLOCATION_SIS2IEBLOBLOCATION_PK] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [LANGUAGEINDICATOR] ASC)
);


GO
ALTER TABLE [SISWEB_OWNER_STAGING].[SIS2IEBLOBLOCATION] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

