CREATE TABLE [SISWEB_OWNER_STAGING].[SIS2GRAPHICS] (
   [FILEEXTENSION]  VARCHAR(10) NOT NULL,
   [MIMETYPE]       VARCHAR(50) NOT NULL,
   [MASIMAGETYPE]   CHAR(1)     NOT NULL,
   [PRIORITY]       NUMERIC(2,0) NOT NULL,
   [ID] [INT]       IDENTITY(1,1) NOT NULL,
   CONSTRAINT [SIS2GRAPHICS_PK_SIS2GRAPHICS] PRIMARY KEY CLUSTERED ([ID] ASC)
);
GO
