CREATE TABLE [SISWEB_OWNER_STAGING].[SMCS_MDFY] (
    [SEC_BY_OWNER_CD]    VARCHAR (2)   NOT NULL,
    [SEC_BY_MGMT_AREA]   VARCHAR (6)   NOT NULL,
    [SMCS_MDFY_CD]       VARCHAR (3)   NOT NULL,
    [SMCS_ITM_TYP]       VARCHAR (1)   NOT NULL,
    [SMCS_CTGRY_CD]      VARCHAR (2)   NOT NULL,
    [REQR_NM]            VARCHAR (40)  NOT NULL,
    [ORG_NM]             VARCHAR (40)  NOT NULL,
    [WHERE_PUB_CD]       VARCHAR (1)   NOT NULL,
    [CD_ASGN_IND]        VARCHAR (1)   NOT NULL,
    [NOTE_TXT]           VARCHAR (70)  NOT NULL,
    [OBS_DT]             DATE          NOT NULL,
    [ADD_DT]             DATE          NOT NULL,
    [LAST_UPDT_ACTV_ID]  VARCHAR (1)   NOT NULL,
    [LAST_UPDT_LOGON_ID] VARCHAR (8)   NOT NULL,
    [LAST_UPDT_TS]       DATETIME2 (6) NOT NULL,
    [ENG_CD_IND]         VARCHAR (1)   NOT NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SMCS_MDFY_I1SJA028]
    ON [SISWEB_OWNER_STAGING].[SMCS_MDFY]([SEC_BY_OWNER_CD] ASC, [SEC_BY_MGMT_AREA] ASC, [SMCS_MDFY_CD] ASC);

