CREATE TABLE [SISWEB_OWNER_STAGING].[SMCS_DESC] (
    [SEC_BY_OWNER_CD]    VARCHAR (2)   NOT NULL,
    [SEC_BY_MGMT_AREA]   VARCHAR (6)   NOT NULL,
    [SMCS_ITM_TYP]       VARCHAR (1)   NOT NULL,
    [SMCS_ITM_CD]        VARCHAR (4)   NOT NULL,
    [SVC_LANG_CD]        VARCHAR (2)   NOT NULL,
    [SML_SEQ_NO]         SMALLINT      NOT NULL,
    [SMCS_DESC_TYP]      VARCHAR (1)   NOT NULL,
    [SMCS_ITM_DESC]      VARCHAR (70)  NOT NULL,
    [LAST_UPDT_ACTV_ID]  VARCHAR (1)   NOT NULL,
    [LAST_UPDT_LOGON_ID] VARCHAR (8)   NOT NULL,
    [LAST_UPDT_TS]       DATETIME2 (6) NOT NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6) NULL
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [SMCS_DESC_I1SJA026]
    ON [SISWEB_OWNER_STAGING].[SMCS_DESC]([SEC_BY_OWNER_CD] ASC, [SEC_BY_MGMT_AREA] ASC, [SMCS_ITM_TYP] ASC, [SMCS_ITM_CD] ASC, [SVC_LANG_CD] ASC, [SML_SEQ_NO] ASC);

GO
CREATE NONCLUSTERED INDEX [NCI_SMCS_DESC_SMCS_DESC_TYP]
ON [SISWEB_OWNER_STAGING].[SMCS_DESC] ([SMCS_DESC_TYP])
INCLUDE ([SMCS_ITM_TYP],[SMCS_ITM_CD],[SMCS_ITM_DESC])