CREATE TABLE [EMP_STAGING].[EMPETLJOB] (
    [EMPETLJOB_ID]  INT    IDENTITY (1, 1) NOT NULL,
    [JOBNAME]      VARCHAR (15)           NOT NULL,
    [INSTANCEID]   VARCHAR (60)           NOT NULL,
    [INPUT]         VARCHAR (120)          NOT NULL,
    [STARTTIME]    DATETIME2 (6)          NOT NULL,
    [ENDTIME]      DATETIME2 (6),
    [STATUS]        VARCHAR (10)           NOT NULL,
    [MESSAGE]       VARCHAR (512),
    CONSTRAINT [PK_EMPETLJOB] PRIMARY KEY CLUSTERED ([EMPETLJOB_ID] ASC)
);

GO
CREATE NONCLUSTERED INDEX IX_SCPART_JOBNAME_INPUT
    ON EMP_STAGING.EMPETLJOB (JOBNAME ASC, INPUT ASC);
GO