CREATE TABLE [EMP_STAGING].[EMPPRODUCTINSTANCE] (
    [EMPPRODUCTINSTANCE_ID] INT                NOT NULL IDENTITY (1, 1),
    [EMPSALESMODEL_ID]      INT                NOT NULL,
    [NUMBER]                VARCHAR (60)       NOT NULL,
    [NAME]                  VARCHAR (60)       NOT NULL,
    [ALIAS1]                VARCHAR (60),
    [ALIAS2]                VARCHAR (60),
    [ALIAS3]                VARCHAR (60),
    [ALTERNATESERIALNUMBER] VARCHAR (60),
    [NUMERICVALUE]          VARCHAR (10),
    [NUMERICVALUE2]         INT,
    [SALESORDERNUMBER]      VARCHAR (60),
    [SERVICEABLE]           BIT,
    [VERSION]               VARCHAR (13),
    [MODEL]                 VARCHAR (60),
    [SNP]                   VARCHAR (60),
    [STATE]                 VARCHAR (15),
    [LASTMODIFIEDDATE]      DATETIME2 (6),
    CONSTRAINT [PK_EMPPRODUCTINSTANCE] PRIMARY KEY CLUSTERED ([EMPPRODUCTINSTANCE_ID] ASC),
    CONSTRAINT [UQ_EMPPRODUCTINSTANCE] UNIQUE(NUMBER)
);

GO
ALTER TABLE [EMP_STAGING].[EMPPRODUCTINSTANCE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

GO
CREATE NONCLUSTERED INDEX IX_EMPPRODUCTINSTANCE_NUMBER_EMPSALESMODEL_ID_SNP
    ON EMP_STAGING.EMPPRODUCTINSTANCE (NUMBER ASC, EMPSALESMODEL_ID ASC, SNP ASC);
