CREATE TABLE [EMP_STAGING].[EXTRACTIONJOBSTATUS](
    [BusinessDate]  DATETIME2 (0)   NOT NULL,
    [PROCESS]       VARCHAR (25)    NOT NULL,
    [STATUS]        VARCHAR (12)    NOT NULL,
    [CompletedAt]   DATETIME2 (6)   NULL,
    CONSTRAINT [PK_EXTRACTIONJOBSTATUS] PRIMARY KEY ([BusinessDate] ASC, [PROCESS] ASC)
);