CREATE TABLE [EMP_STAGING].[LNKCONSISTLIST] (
    [IESYSTEMCONTROLNUMBER]   VARCHAR (12)   NOT NULL,
    [PARTSEQUENCENUMBER]      SMALLINT       NOT NULL,
    [REFERENCENO]             VARCHAR (50)   NULL,
    [GRAPHNO]                 VARCHAR (50)   NULL,
    [PARTNUMBER]              VARCHAR (40)   NOT NULL,
    [ORGCODE]                 VARCHAR (12)   NOT NULL,
    [PARTNAME]                NVARCHAR (64)  NULL,
    [PARTMODIFIER]            NVARCHAR (512) NULL,
    [QUANTITY]                VARCHAR (24)   NULL,
    [NOTE]                    VARCHAR (10)   NULL,
    [COMMENTS]                NVARCHAR (512) NULL,
    [SERVICEABILITYINDICATOR] VARCHAR (1)    NULL,
    [PARENTAGE]               SMALLINT       NULL,
    [CCRINDICATOR]            VARCHAR (1)    NULL,
    [FILTERPARTINDICATOR]     VARCHAR (1)    NULL,
    [MAINTPARTINDICATOR]      VARCHAR (1)    NULL,
    [NPRINDICATOR]            VARCHAR (1)    NULL,
    [LASTMODIFIEDDATE]        DATETIME2 (6)  NULL,
    CONSTRAINT [PK_LNKCONSISTLIST] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [PARTSEQUENCENUMBER] ASC) WITH (FILLFACTOR = 100)
);


GO

CREATE UNIQUE NONCLUSTERED INDEX [LNKCONSISTLIST_IESYSTEMCONTROLNUMBER_1540841090959371_PK]
    ON [EMP_STAGING].[LNKCONSISTLIST]([IESYSTEMCONTROLNUMBER] ASC, [PARTSEQUENCENUMBER] ASC, [LASTMODIFIEDDATE] ASC);
GO

CREATE INDEX [IX_LNKCONSISTLIST_PARTNUMBER] ON [EMP_STAGING].[LNKCONSISTLIST] ([PARTNUMBER]);
GO

CREATE INDEX [IX_LNKCONSISTLIST_PARTNAME] ON [EMP_STAGING].[LNKCONSISTLIST] ([PARTNAME]) INCLUDE ([PARTNUMBER]);

GO
ALTER TABLE [EMP_STAGING].[LNKCONSISTLIST] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO
