CREATE TABLE [EMP_STAGING].[LNKIEIMAGE] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [GRAPHICCONTROLNUMBER]  VARCHAR (60)  NOT NULL,
    [GRAPHICSEQUENCENUMBER] SMALLINT      NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKIEIMAGE_PK_LNKIEIMAGE] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [GRAPHICCONTROLNUMBER] ASC, [GRAPHICSEQUENCENUMBER] ASC) WITH (FILLFACTOR = 100)
    );

GO
CREATE NONCLUSTERED INDEX [IX_LNKIEIMAGE_GRAPHICCONTROLNUMBER]
    ON [EMP_STAGING].[LNKIEIMAGE]([GRAPHICCONTROLNUMBER] ASC);


GO
ALTER TABLE [EMP_STAGING].[LNKIEIMAGE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO