CREATE TABLE [EMP_STAGING].[LNKIEPSID] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [PSID]                  VARCHAR (8)   NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKIEPSID_PK_LNKIEPSID] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [PSID] ASC) WITH (FILLFACTOR = 100)
    );



GO
CREATE NONCLUSTERED INDEX NCX_LNKIEPSID_MEDIANUMBER ON EMP_STAGING.LNKIEPSID (MEDIANUMBER ASC) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX NCX_LNKIEPSID_PSID ON EMP_STAGING.LNKIEPSID (PSID ASC,MEDIANUMBER ASC,IESYSTEMCONTROLNUMBER ASC) ON [PRIMARY];
