CREATE TABLE [EMP_STAGING].[LNKIEPRODUCTINSTANCE] (
    [LNKIEPRODUCTINSTANCE_ID]  INT    IDENTITY    NOT NULL,
    [MEDIANUMBER]              VARCHAR (8)        NOT NULL,
    [IESYSTEMCONTROLNUMBER]    VARCHAR (12)       NOT NULL,
    [EMPPRODUCTINSTANCE_ID]    INT                NOT NULL,
    CONSTRAINT [PK_LNKIEPRODUCTINSTANCE] PRIMARY KEY CLUSTERED ([LNKIEPRODUCTINSTANCE_ID] ASC)
);

GO
CREATE NONCLUSTERED INDEX IX_LNKIEPRODUCTINSTANCE_MEDIANUMBER_IESYSTEMCONTROLNUMBER_EMPPRODUCTINSTANCE_ID
    ON EMP_STAGING.LNKIEPRODUCTINSTANCE (MEDIANUMBER ASC, IESYSTEMCONTROLNUMBER ASC, EMPPRODUCTINSTANCE_ID ASC);

GO
ALTER TABLE [EMP_STAGING].[LNKIEPRODUCTINSTANCE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO