CREATE TABLE [EMP_STAGING].[LNKIEINFOTYPE](
     [IESYSTEMCONTROLNUMBER] VARCHAR(12) NOT NULL
    ,[INFOTYPEID]            SMALLINT NOT NULL
    ,[LASTMODIFIEDDATE]      DATETIME2(6) NULL
    ,CONSTRAINT [PK_LNKIEINFOTYPE] PRIMARY KEY CLUSTERED([IESYSTEMCONTROLNUMBER] ASC,[INFOTYPEID] ASC));
GO

CREATE NONCLUSTERED INDEX [NCX_InfoTypeID] ON [EMP_STAGING].[LNKIEINFOTYPE] ([INFOTYPEID] ASC);
GO

ALTER TABLE [EMP_STAGING].[LNKIEINFOTYPE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO
