CREATE TABLE [EMP_STAGING].[LNKMEDIAIEPART] (
    [MEDIANUMBER]             VARCHAR (8)     NOT NULL,
    [IESYSTEMCONTROLNUMBER]   VARCHAR (12)    NOT NULL,
    [IEPARTNUMBER]            VARCHAR (40)    NULL,
    [ORGCODE]                 VARCHAR (12)    NULL,
    [IEPARTNAME]              NVARCHAR (128)  NULL,
    [IESEQUENCENUMBER]        INT         	  NOT NULL,
    [BASEENGCONTROLNO]        VARCHAR (12)    NOT NULL,
    [SECTIONNUMBER]           INT        	  NOT NULL,
    [IEPARTMODIFIER]          NVARCHAR (512)  NULL,
    [IECAPTION]               NVARCHAR (2048) NOT NULL,
    [IETYPE]                  VARCHAR (1)     NOT NULL,
    [SERVICEABILITYINDICATOR] VARCHAR (1)     NOT NULL,
    [IEUPDATEDATE]            DATETIME2 (0)   NOT NULL,
    [IECONTROLNUMBER]         VARCHAR (25)    NULL,
    [PART]                    VARCHAR (2)     NULL,
    [OFPARTS]                 VARCHAR (2)     NULL,
    [ARRANGEMENTINDICATOR]    VARCHAR (1)     NOT NULL,
    [CCRINDICATOR]            VARCHAR (1)     NOT NULL,
    [FILTERPARTINDICATOR]     VARCHAR (1)     NOT NULL,
    [MAINTPARTINDICATOR]      VARCHAR (1)     NOT NULL,
    [NPRINDICATOR]            VARCHAR (1)     NULL,
    [TYPECHANGEINDICATOR]     VARCHAR (1)     NULL,
    [LASTMODIFIEDDATE]        DATETIME2 (6)   NULL,
    CONSTRAINT [LNKMEDIAIEPART_PK_LNKMEDIAIEPART] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC) WITH (FILLFACTOR = 100)
);

GO
ALTER TABLE [EMP_STAGING].[LNKMEDIAIEPART] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO