CREATE TABLE [EMP_STAGING].[LNKPDFPRODUCTINSTANCE] (
    [PARTSPDF_ID]           INT    NOT NULL,
    [EMPPRODUCTINSTANCE_ID] INT    NOT NULL,
    CONSTRAINT [PK_LNKPDFPRODUCTINSTANCE] PRIMARY KEY CLUSTERED ([PARTSPDF_ID] ASC, [EMPPRODUCTINSTANCE_ID] ASC)
);

GO
CREATE NONCLUSTERED INDEX idx_LNKPDFPRODUCTINSTANCE_PARTSPDF_ID_EMPPRODUCTINSTANCE_ID ON EMP_STAGING.LNKPDFPRODUCTINSTANCE (PARTSPDF_ID ASC, EMPPRODUCTINSTANCE_ID ASC);


GO
ALTER TABLE [EMP_STAGING].[LNKPDFPRODUCTINSTANCE] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO