CREATE TABLE [EMP_STAGING].[LNKTRANSLATEDSPN] (
    [PARTNAME]           VARCHAR (200)  NOT NULL,
    [LANGUAGEINDICATOR]  VARCHAR (2)    NOT NULL,
    [TRANSLATEDPARTNAME] NVARCHAR (200) NOT NULL
    CONSTRAINT [LNKTRANSLATEDSPN_LNKTRANSLATEDSPN_PK] PRIMARY KEY CLUSTERED ([PARTNAME] ASC, [LANGUAGEINDICATOR] ASC)
);
GO
CREATE NONCLUSTERED INDEX [IX_LNKTRANSLATEDSPN_LANGUAGEINDICATOR]
ON [EMP_STAGING].[LNKTRANSLATEDSPN] ([LANGUAGEINDICATOR] ASC)