CREATE TABLE [EMP_STAGING].[SCSUPERSEDEDPART](
    [SCSUPERSEDEDPART_ID]       INT    IDENTITY (1, 1)     NOT NULL,
    [SESSIONID]                 NUMERIC (10, 0),
    [PARTNUMBER]                VARCHAR (128),
    [ORGCODE]                   VARCHAR (12),
    [RELATIONSHIPTYPE]          VARCHAR (20),
    [REPLACEMENTORGCODE]        VARCHAR (12),
    [REPLACEMENTPARTNUMBER]     VARCHAR (128),
    [DOMAINPATH]                VARCHAR (10),
    [CREATEDDATE]               DATETIME2 (7),
    [MODIFIEDDATE]              DATETIME2 (7),
    [TYPE]                      VARCHAR (128),
    [WBMSOURCEDESCRIPTION]      VARCHAR (10),
    [WBMSOURCEIDENTIFIER]       VARCHAR (10),
    [WBMLOADACTION]             VARCHAR (128)
    CONSTRAINT [PK_SCSUPERSEDEDPART] PRIMARY KEY CLUSTERED ([SCSUPERSEDEDPART_ID] ASC)
)

GO
CREATE NONCLUSTERED INDEX IX_SCSUPERSEDEDPART_PARTNUMBER_ORGCODE
    ON EMP_STAGING.SCSUPERSEDEDPART (PARTNUMBER ASC,ORGCODE ASC);
GO

GO
CREATE NONCLUSTERED INDEX IX_SCSUPERSEDEDPART_REPLACEMENTPARTNUMBER_REPLACEMENTORGCODE
    ON EMP_STAGING.SCSUPERSEDEDPART (REPLACEMENTPARTNUMBER ASC,REPLACEMENTORGCODE ASC);
GO

GO
CREATE NONCLUSTERED INDEX IX_SCSUPERSEDEDPART_RELATIONSHIPTYPE
    ON EMP_STAGING.SCSUPERSEDEDPART (RELATIONSHIPTYPE ASC);
GO


GO
ALTER TABLE [EMP_STAGING].[SCSUPERSEDEDPART] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO
