CREATE TABLE [EMP_STAGING].[SCSUPERSEDEDPARTHIST](
    [SCSUPERSEDEDPARTHIST_ID]       INT    IDENTITY (1, 1)     NOT NULL,
    ADMINISTRATIVELOCKISNULL	    NUMERIC (1, 0),
    TYPEADMINISTRATIVELOCK          VARCHAR (150),
    CLASSNAMEKEYDOMAINREF           VARCHAR (600),
    IDA3DOMAINREF                   NUMERIC,
    INHERITEDDOMAIN                 NUMERIC (1, 0),
    PARTNUMBER                      VARCHAR (600),
    PARTORGNAME                     VARCHAR (600),
    RELATIONSHIPTYPE                VARCHAR (600),
    REPLACEMENTORGNAME              VARCHAR (600),
    REPLACEMENTPARTNUMBER           VARCHAR (600),
    CREATESTAMPA2                   DATETIME2,
    MARKFORDELETEA2                 NUMERIC,
    MODIFYSTAMPA2                   DATETIME2,
    CLASSNAMEA2A2                   VARCHAR (600),
    IDA2A2                          NUMERIC,
    UPDATECOUNTA2                   NUMERIC,
    UPDATESTAMPA2                   DATETIME2,
    BRANCHIDA2TYPEDEFINITIONREFE    NUMERIC,
    IDA2TYPEDEFINITIONREFERENCE     NUMERIC
    CONSTRAINT [PK_SCSUPERSEDEDPARTHIST] PRIMARY KEY CLUSTERED ([SCSUPERSEDEDPARTHIST_ID] ASC)
)

