CREATE TABLE [EMP_STAGING].[SIS2GRAPHICLOCATION] (
    [GRAPHICCONTROLNUMBER] VARCHAR (60)  NOT NULL,
    [MIMETYPE]             VARCHAR (50)  NOT NULL,
    [LOCATION]             VARCHAR (70)  NOT NULL,
    [UPDATEDATETIME]       DATETIME2 (6) NOT NULL,
    [FILESIZEBYTE]          INT NULL,
    [LOCATIONHIGHRES]       varchar(70) NULL,
	[FILESIZEBYTEHIGHRES]   int NULL,
    [LASTMODIFIEDDATE]     DATETIME2 (6) NULL,
    CONSTRAINT [SIS2GRAPHICLOCATION_SIS2GRAPHICLOCATION_PK] PRIMARY KEY CLUSTERED ([GRAPHICCONTROLNUMBER] ASC, [MIMETYPE] ASC)
);


GO
ALTER TABLE [EMP_STAGING].[SIS2GRAPHICLOCATION] ENABLE CHANGE_TRACKING WITH (TRACK_COLUMNS_UPDATED = ON);
GO

