CREATE TABLE [EMP_STAGING].[SUPERSESSIONCHAINS] (
    [PARTNUMBER]       VARCHAR (40)    NOT NULL,
    [ORGCODE]          VARCHAR (12)    NOT NULL,
    [LASTPARTNUMBER]   VARCHAR (40)    NOT NULL,
    [LASTORGCODE]      VARCHAR (12)    NOT NULL,
    [CHAIN]            VARCHAR (4000)  NOT NULL,
    [ID]               INT             IDENTITY (1, 1) NOT NULL
    CONSTRAINT [PK_SUPERSESSIONCHAINS_] PRIMARY KEY CLUSTERED ([ID] ASC)
);

GO
CREATE NONCLUSTERED INDEX IDX_SSCHAINS_LPNO ON EMP_STAGING.SUPERSESSIONCHAINS (LASTPARTNUMBER ASC, LASTORGCODE ASC);
GO

CREATE NONCLUSTERED INDEX IDX_SSCHAINS_PNO ON EMP_STAGING.SUPERSESSIONCHAINS (PARTNUMBER ASC, ORGCODE ASC);
GO
