

CREATE   FUNCTION SISSEARCH.fn_KITIEPART(@DATE DATETIME)
	RETURNS TABLE
AS
RETURN SELECT 
	IESYSTEMCONTROLNUMBER,
	IESYSTEMCONTROLNUMBER as ID,
	'["' + string_agg(KITIEPART, '","') + '"]' as KITIEPART,
	MAX(INSERTDATE) as INSERTDATE
FROM SISSEARCH.fn_KITIEPART_ORIGIN(@DATE)
GROUP BY IESYSTEMCONTROLNUMBER