

CREATE   FUNCTION SISSEARCH.fn_KITCONSISTPART(@DATE DATETIME)
	RETURNS TABLE
AS
RETURN SELECT 
	IESYSTEMCONTROLNUMBER,
	IESYSTEMCONTROLNUMBER as ID,
	'["' + string_agg(KITCONSISTPART, '","') + '"]' as KITCONSISTPART,
	MAX(INSERTDATE) as INSERTDATE
FROM SISSEARCH.fn_KITCONSISTPART_ORIGIN(@DATE)
GROUP BY IESYSTEMCONTROLNUMBER