CREATE   FUNCTION [SISSEARCH].[fn_PRODUCTSTRUCTURE_ORIGIN](@DATE DATETIME)
	RETURNS TABLE
AS
RETURN SELECT distinct --top 1000
     c.IESYSTEMCONTROLNUMBER,
	 CASE 
		WHEN d.PRODUCTCODE not in ('EPG', 'IENG', 'MENG', 'TENG', 'ATCH', 'WKTL')
			and b.PARENTPRODUCTSTRUCTUREID in ('00000514','00000062','00000210','00000847','00001895','00000001')
		THEN '88888888_'+cast(b.PARENTPRODUCTSTRUCTUREID as varchar)+'_'+ cast(a.PSID as Varchar)
		ELSE 
			CASE	
			WHEN b.PARENTPRODUCTSTRUCTUREID <> '00000000'
			THEN cast(b.PARENTPRODUCTSTRUCTUREID as varchar)+'_'+cast(a.PSID As varchar)
			ELSE cast(a.PSID As varchar)+'_'+cast(a.PSID As varchar)
			END
	END as [PSID],
	CASE	
			WHEN b.PARENTPRODUCTSTRUCTUREID <> '00000000'
			THEN cast(b.PARENTPRODUCTSTRUCTUREID as varchar)
			ELSE cast(a.PSID As varchar)
			END as [SYSTEM],
	e.LASTMODIFIEDDATE [InsertDate]	
From [SISWEB_OWNER_SHADOW].LNKIEPSID a With(NolocK) --4.9M 
inner join [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] e  With(NolocK) --3M
	on e.MEDIANUMBER=a.MEDIANUMBER and a.IESYSTEMCONTROLNUMBER=e.IESYSTEMCONTROLNUMBER AND
		e.LASTMODIFIEDDATE > @DATE
inner join  [SISWEB_OWNER_SHADOW].[LNKPARTSIESNP] c With(NolocK) --10M
	on c.IESYSTEMCONTROLNUMBER=e.IESYSTEMCONTROLNUMBER and c.MEDIANUMBER=e.MEDIANUMBER
--inner join #InsertRecords f --Add filter to limit to changed records
-- on e.iesystemcontrolnumber=f.iesystemcontrolnumber
inner join [SISWEB_OWNER].LNKPRODUCT d With(NolocK) --7K 
	on c.SNP=d.SNP
inner join [SISWEB_OWNER].MASPRODUCTSTRUCTURE b With(NolocK) --20K 
	on a.PSID=b.PRODUCTSTRUCTUREID and b.LANGUAGEINDICATOR='E'
inner join [SISWEB_OWNER].[MASMEDIA] g With(NolocK) --90K
	on g.MEDIANUMBER=e.MEDIANUMBER and g.MEDIASOURCE in ('A', 'C')
Where c.SNPTYPE = 'P'