
CREATE   FUNCTION SISSEARCH.fn_SMCS(@DATE DATETIME)
	RETURNS TABLE
AS
RETURN SELECT
	IESYSTEMCONTROLNUMBER,
	IESYSTEMCONTROLNUMBER as ID,
	'["' + string_agg(smcs,'","') + '"]' as SMCS,
	max([InsertDate]) [InsertDate]
FROM SISSEARCH.fn_SMCS_ORIGIN(@DATE)
GROUP BY IESYSTEMCONTROLNUMBER