CREATE   FUNCTION [SISSEARCH].[fn_SMCS_ORIGIN](@DATE DATETIME)
	RETURNS TABLE
AS
RETURN SELECT DISTINCT
	a.IESYSTEMCONTROLNUMBER,
	b.SMCSCOMPCODE as smcs,
	c.LASTMODIFIEDDATE [InsertDate]
FROM [SISWEB_OWNER_SHADOW].LNKPARTSIESNP a With(Nolock) --10M
	inner join [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] c With(NolocK) --3M
	 on a.IESYSTEMCONTROLNUMBER=c.IESYSTEMCONTROLNUMBER and
		c.LASTMODIFIEDDATE > @DATE
	inner join [SISWEB_OWNER].LNKIESMCS as b With(Nolock) --5.5M
	 on a.IESYSTEMCONTROLNUMBER = b.IESYSTEMCONTROLNUMBER
	inner join [SISWEB_OWNER].[MASMEDIA]  e With(Nolock) --90K
	 on e.MEDIANUMBER=c.MEDIANUMBER
WHERE e.MEDIASOURCE in ('A', 'C') and a.SNPTYPE = 'P'