CREATE   FUNCTION [SISSEARCH].[fnSNP_ORIGIN](@DATE DATETIME)
	RETURNS TABLE
AS
RETURN SELECT DISTINCT
		a.IESYSTEMCONTROLNUMBER,
		a.SNP,
		c.LASTMODIFIEDDATE InsertDate,
		cast(a.BEGINNINGRANGE as varchar(10)) BEGINNINGRANGE,
		cast(a.ENDRANGE as varchar(10)) ENDRANGE
	FROM [SISWEB_OWNER_SHADOW].LNKPARTSIESNP a With(Nolock) --10M
	inner join [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] c With(NolocK) --3M
		on a.IESYSTEMCONTROLNUMBER =c.IESYSTEMCONTROLNUMBER  
	inner join [SISWEB_OWNER].[MASMEDIA] b With(NolocK) --90K
		on b.MEDIANUMBER = c.MEDIANUMBER
	WHERE b.MEDIASOURCE in ('A', 'C') and a.SNPTYPE = 'P'