CREATE   FUNCTION [SISSEARCH].[GetProcTimeStamp] (@SPROCNAME varchar(200), @LogType VARCHAR(200)='TimeStamp')
	RETURNS DATETIME
AS BEGIN
	DECLARE @TIMESTAMP DATETIME

	SELECT TOP 1 @TIMESTAMP=TRY_CONVERT(datetime, DataValue) 
		FROM SISSEARCH.LOG WHERE 
			NameofSproc = @SPROCNAME AND LogType = @LogType AND DataValue IS NOT NULL
		ORDER BY LogDateTime DESC
	RETURN COALESCE(@TIMESTAMP, '')
END