CREATE FUNCTION [SISSEARCH].[tvf_CONSISTPARTSORIGIN] (@DATE DATETIME)
	RETURNS @RTABLE TABLE (
    [IESYSTEMCONTROLNUMBER]   VARCHAR (12)  NOT NULL INDEX IX_IESYSTEMCONTROLNUMBER,
    [PARTNUMBER]              VARCHAR(40) NULL INDEX IX_PARTNUMBER,
    [PARTNAME]                VARCHAR(128) NULL,
    [ORGCODE]				  VARCHAR(12) NULL,
    [LASTMODIFIEDDATE]        DATETIME2(6) NULL INDEX IX_LASTMODIFIEDDATE,
	INDEX IX_IESYSTEM_PARTNUMBER_ORGCODE CLUSTERED (IESYSTEMCONTROLNUMBER, PARTNUMBER, ORGCODE)
)
AS BEGIN

INSERT INTO @RTABLE
SELECT 
	b.IESYSTEMCONTROLNUMBER,
	d.PARTNUMBER,
	d.PARTNAME,
	b.ORGCODE,
	b.LASTMODIFIEDDATE
from [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] b With(NolocK)
inner join [SISWEB_OWNER].[MASMEDIA] e with(Nolock)
	on e.MEDIANUMBER=b.MEDIANUMBER and e.[MEDIASOURCE]='A'  
inner join [SISWEB_OWNER].LNKCONSISTLIST d With(Nolock) 
	on b.IESYSTEMCONTROLNUMBER = d.IESYSTEMCONTROLNUMBER
WHERE b.LASTMODIFIEDDATE > @DATE

INSERT INTO @RTABLE
SELECT
	b.IESYSTEMCONTROLNUMBER,
	d.PARTNUMBER,
	d.PARTNAME,
	b.ORGCODE,
	b.LASTMODIFIEDDATE
from [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] b With(NolocK)
inner join [SISWEB_OWNER].[MASMEDIA] e with(Nolock)
	on e.MEDIANUMBER=b.MEDIANUMBER and e.[MEDIASOURCE] ='C'
inner join [SISWEB_OWNER].LNKCONSISTLIST d With(Nolock)
	on d.IESYSTEMCONTROLNUMBER  = b.BASEENGCONTROLNO
WHERE b.LASTMODIFIEDDATE > @DATE

RETURN 
END
GO