CREATE TABLE [sis_stage].[IELevel](
	[IELevel_ID] [Int] IDENTITY(1,1) NOT NULL,
	[IE_ID] Int NOT NULL,
	[LevelSequenceNumber] [Smallint] NOT NULL,
	[LevelID] [Smallint] NOT NULL,
	[ParentID] [INT] NULL,
 CONSTRAINT [PK_IELevel] PRIMARY KEY CLUSTERED 
(
	[IELevel_ID] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
;
