CREATE PROCEDURE EMP_STAGING.UDSP_DELETE_PDF_INFORMATION (@MediaNumber [dbo].UDTT_MEDIANUMBER READONLY)
AS
BEGIN
        SET NOCOUNT ON;

        -- delete pdf related tables

		DELETE tbl
			FROM EMP_STAGING.LNKPARTSPDFPSID tbl
			INNER JOIN EMP_STAGING.PARTSPDF li
			ON tbl.PARTSPDF_ID = li.PARTSPDF_ID
			INNER JOIN @MediaNumber input
			ON li.MEDIANUMBER = input.MEDIANUMBER

		DELETE tbl
			FROM EMP_STAGING.LNKPDFPRODUCTINSTANCE tbl
			INNER JOIN EMP_STAGING.PARTSPDF li
			ON tbl.PARTSPDF_ID = li.PARTSPDF_ID
			INNER JOIN @MediaNumber input
			ON li.MEDIANUMBER = input.MEDIANUMBER

		DELETE tbl from EMP_STAGING.PARTSPDF tbl
			INNER JOIN @MediaNumber input
			ON tbl.MEDIANUMBER = input.MEDIANUMBER

END;
GO