CREATE PROCEDURE EMP_STAGING.UDSP_MERGE_LNKTRANSLATEDSPN(@PARTNAMES [dbo].UDTT_LNKTRANSLATEDSPN_INSERT_IN READONLY)
AS BEGIN

    SET NOCOUNT ON;

	MERGE INTO [EMP_STAGING].[LNKTRANSLATEDSPN] target
	    USING @PARTNAMES source
	ON
	    source.[PARTNAME] = target.PARTNAME and target.[LANGUAGEINDICATOR]='E'
	when not matched then
        insert values (source.[PARTNAME], 'E', source.[PARTNAME]);
END