CREATE PROCEDURE EMP_STAGING.UDSP_MERGE_PDF_PRODUCTINSTANCE(@productinstance [dbo].UDTT_PDF_PRODUCTINSTANCE_INSERT_IN READONLY, @ProductFamilyNumber VARCHAR(60))
AS
BEGIN

SET NOCOUNT ON;

MERGE INTO
    [EMP_STAGING].[LNKPDFPRODUCTINSTANCE] t
USING
	(
    SELECT s.[PARTSPDF_ID], pi.[EMPPRODUCTINSTANCE_ID]
    FROM [EMP_STAGING].[EMPPRODUCTFAMILY] pf
        INNER JOIN [EMP_STAGING].[EMPSALESMODEL] sm ON sm.[EMPPRODUCTFAMILY_ID] = pf.[EMPPRODUCTFAMILY_ID] AND pf.[NUMBER] = @ProductFamilyNumber
        INNER JOIN [EMP_STAGING].[EMPPRODUCTINSTANCE] pi ON pi.[EMPSALESMODEL_ID] = sm.[EMPSALESMODEL_ID]
        inner join @productinstance s ON pi.[NUMBER] = s.[NUMBER]
        ) source
	ON
    t.[PARTSPDF_ID] = source.[PARTSPDF_ID]
        AND t.[EMPPRODUCTINSTANCE_ID] = source.[EMPPRODUCTINSTANCE_ID]
WHEN NOT MATCHED THEN
    INSERT VALUES (source.[PARTSPDF_ID], source.[EMPPRODUCTINSTANCE_ID]);

END