




create view [sis].[vw_IEImageLocation] as
select b.IESYSTEMCONTROLNUMBER, a.GRAPHICCONTROLNUMBER, a.IMAGETYPE, a.IMAGELOCATION, b.GRAPHICSEQUENCENUMBER
from SISWEB_OWNER.MASIMAGELOCATION a,
SISWEB_OWNER.LNKIEIMAGE b 
where a.GRAPHICCONTROLNUMBER = b.GRAPHICCONTROLNUMBER
