

CREATE VIEW [sis].[vw_IEMediaOrigin] AS

SELECT	mi.IESYSTEMCONTROLNUMBER,
		m.MEDIAORIGIN 
	FROM [SISWEB_OWNER].[MASMEDIA] m
	JOIN [SISWEB_OWNER].[LNKMEDIAIE] mi
		ON m.MEDIANUMBER=mi.MEDIANUMBER
	JOIN [SISWEB_OWNER].[LNKIETITLE] it 
		ON it.IESYSTEMCONTROLNUMBER=mi.IESYSTEMCONTROLNUMBER
UNION 
SELECT	mp.IESYSTEMCONTROLNUMBER,
		m.MEDIAORIGIN
	FROM [SISWEB_OWNER].[LNKMEDIAIEPART] mp 
	JOIN [SISWEB_OWNER].[MASMEDIA] m
		ON mp.MEDIANUMBER=m.MEDIANUMBER
