CREATE VIEW sis.vw_LNKMEDIAIEPART_SNP_TopLevel
AS
	SELECT PSID
		  ,isTopLevel
		  ,MEDIANUMBER
		  ,IESYSTEMCONTROLNUMBER
		  ,IEPARTNUMBER
	      ,ORGCODE
		  ,IEPARTNAME
		  ,IESEQUENCENUMBER
		  ,IEPARTMODIFIER
		  ,IECAPTION
		  ,SNP
	  FROM SISWEB_OWNER.LNKMEDIAIEPART_SNP_TOPLEVEL;
GO