
create View sis.[vw_MediaSection] as
select 
	m.SECTIONNUMBER as sectionNumber ,
	t.IETITLE as ieTitle, 
	m.IETITLESEQNUMBER ieTitleSeqNumber,
	m.IESYSTEMCONTROLNUMBER as ieSystemControlNumber, 
	d.IEPUBDATE as iePubDate, 
	t.GROUPTITLEINDICATOR as groupTitleIndicator,
	m.MEDIANUMBER,
	t.IELANGUAGEINDICATOR,
	p.SNP,
	p.BEGINNINGRANGE,
	p.ENDRANGE
from SISWEB_OWNER.LNKMEDIAIE m
inner join SISWEB_OWNER.LNKIETITLE t on t.IESYSTEMCONTROLNUMBER = m.IESYSTEMCONTROLNUMBER 
inner join SISWEB_OWNER.LNKIEDATE d on d.IESYSTEMCONTROLNUMBER = m.IESYSTEMCONTROLNUMBER and d.LANGUAGEINDICATOR = t.IELANGUAGEINDICATOR 
inner join SISWEB_OWNER.LNKIESNP p on p.IESYSTEMCONTROLNUMBER = m.IESYSTEMCONTROLNUMBER and p.MEDIANUMBER = m.MEDIANUMBER