CREATE VIEW [sis].[vw_MediaSequenceFamily]
AS
(
SELECT [Media_ID]
      ,[Media_Number]
      ,[MediaSection_ID]
      ,[Arrangement_Indicator]
      ,[CCR_Indicator]
      ,[IEPart_ID]
      ,[IE_ID]
      ,[IESystemControlNumber]
      ,[NPR_Indicator]
      ,[Serviceability_Indicator]
      ,[Sequence_Number]
      ,[TypeChange_Indicator]
      ,[MediaSequence_ID]
      ,[SerialNumberRange_ID]
      ,[Language_ID]
      ,[Media_Origin]
      ,[SerialNumberPrefix_ID]
      ,[Serial_Number_Prefix]
      ,[End_Serial_Number]
      ,[Start_Serial_Number]
  FROM [sis].[MediaSequenceFamily] 
)