





create view [sis].[vw_SerialMeta] as
select a.SERIALNUMBER, a.ARRANGEMENTPARTNUMBER, a.SHIPDATE, a.ENGINEERINGMODELNO, b.MEDIANUMBER
from SISWEB_OWNER.LNKSERIALPART a,
SISWEB_OWNER.LNKMEDIAARRANGEMENT b 
where a.ARRANGEMENTPARTNUMBER = b.ARRANGEMENTNO
