-- =============================================
-- Author:      Krishna Rudraraju
-- Create Date: 20230927
-- Description: Convert sis2go bundle query to stored procedure to improve performance Story #31281 
-- =============================================
CREATE PROCEDURE [sis].[SP_Part_Alternate_Part_Relation] (@Media_Number VARCHAR(50))
AS
BEGIN
	SET NOCOUNT ON

	DROP TABLE IF EXISTS #t1
	DROP TABLE IF EXISTS #t2
	DROP TABLE IF EXISTS #t3
	DROP TABLE IF EXISTS #t4
	DROP TABLE IF EXISTS #t5
	DROP TABLE IF EXISTS #t6
	DROP TABLE IF EXISTS #t7
	DROP TABLE IF EXISTS #t8
	DROP TABLE IF EXISTS #t9
	DROP TABLE IF EXISTS #t10
	DROP TABLE IF EXISTS #t11
	DROP TABLE IF EXISTS #t12
	DROP TABLE IF EXISTS #t13
	DROP TABLE IF EXISTS #t14
	DROP TABLE IF EXISTS #t15
	DROP TABLE IF EXISTS #t16
	DROP TABLE IF EXISTS #t17
	DROP TABLE IF EXISTS #t18
	DROP TABLE IF EXISTS #t19
	DROP TABLE IF EXISTS #t20
	DROP TABLE IF EXISTS #t21
	DROP TABLE IF EXISTS #t22
	DROP TABLE IF EXISTS #t23
	DROP TABLE IF EXISTS #t24
	DROP TABLE IF EXISTS #t25
	DROP TABLE IF EXISTS #t26
	DROP TABLE IF EXISTS #t27
	DROP TABLE IF EXISTS #t28
	DROP TABLE IF EXISTS #t29
	DROP TABLE IF EXISTS #t30
	DROP TABLE IF EXISTS #t31
	DROP TABLE IF EXISTS #t32
	DROP TABLE IF EXISTS #t33
	DROP TABLE IF EXISTS #t34
	
	
	SELECT DISTINCT
	IESYSTEMCONTROLNUMBER,SNP
	INTO #t1
	FROM SISWEB_OWNER.lnkpartsiesnp
	WHERE MEDIANUMBER=@Media_Number
	
	SELECT DISTINCT lm.IESYSTEMCONTROLNUMBER,lm.BASEENGCONTROLNO,lm.MEDIANUMBER,t1.SNP,lm.IEPARTNAME 
	INTO #t2
	FROM 
	SISWEB_OWNER.lnkmediaiepart lm
	JOIN #t1 t1
	ON lm.IESYSTEMCONTROLNUMBER=t1.IESYSTEMCONTROLNUMBER
	
	SELECT DISTINCT lp.CLASSICPARTINDICATOR,t2.IESYSTEMCONTROLNUMBER,t2.BASEENGCONTROLNO,t2.MEDIANUMBER,t2.IEPARTNAME 
	INTO #t3
	FROM SISWEB_OWNER.LNKPRODUCT lp
	JOIN #t2 t2
	ON lp.SNP=t2.SNP
	
	SELECT DISTINCT m.Source,t3.CLASSICPARTINDICATOR,t3.IESYSTEMCONTROLNUMBER,t3.BASEENGCONTROLNO,t3.IEPARTNAME 
	INTO #t5
	FROM sis.Media m
	JOIN #t3 t3
	ON m.Media_Number=t3.MEDIANUMBER
	
	
	SELECT DISTINCT lc.PARTNUMBER,t5.CLASSICPARTINDICATOR,t5.IESYSTEMCONTROLNUMBER,t5.IEPARTNAME 
	INTO #t4
	FROM #t5 t5 
	INNER JOIN SISWEB_OWNER.lnkconsistlist lc
	ON (lc.IESYSTEMCONTROLNUMBER=CASE WHEN t5.Source='C'
		THEN t5.BASEENGCONTROLNO ELSE t5.IESYSTEMCONTROLNUMBER END)
	
		
	SELECT DISTINCT lrp.RELATEDPARTNUMBER,lrp.RELATEDPARTNAME,lrp.PARTNUMBER,lrp.TYPEINDICATOR,t4.IEPARTNAME,t4.IESYSTEMCONTROLNUMBER
	INTO #t6
	FROM SISWEB_OWNER.LNKRELATEDPARTINFO lrp
	JOIN #t4 t4
	ON (lrp.PARTNUMBER=t4.PARTNUMBER)
	WHERE  lrp.TYPEINDICATOR <> 'K'
		AND lrp.TYPEINDICATOR <> 'E'
		AND lrp.TYPEINDICATOR <> CASE WHEN t4.CLASSICPARTINDICATOR = 'N' THEN 'CL' ELSE '' END
	
	SELECT DISTINCT li.PSID,t6.RELATEDPARTNUMBER,t6.RELATEDPARTNAME,t6.TYPEINDICATOR,t6.PARTNUMBER,t6.IEPARTNAME 
	INTO #t7
	FROM SISWEB_OWNER.lnkiepsid li
	JOIN #t6 t6
	ON li.IESYSTEMCONTROLNUMBER=t6.IESYSTEMCONTROLNUMBER
	
	SELECT DISTINCT mp1.PARENTPRODUCTSTRUCTUREID,t7.RELATEDPARTNUMBER,t7.RELATEDPARTNAME,t7.TYPEINDICATOR,t7.PARTNUMBER,t7.IEPARTNAME 
	INTO #t8
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp1
	JOIN #t7 t7
	ON mp1.PRODUCTSTRUCTUREID=t7.PSID
	WHERE mp1.LANGUAGEINDICATOR='E'
	
	
	SELECT DISTINCT mp2.LANGUAGEINDICATOR,t8.RELATEDPARTNUMBER,t8.RELATEDPARTNAME,t8.TYPEINDICATOR,t8.PARTNUMBER,t8.IEPARTNAME
	INTO #t9
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp2
	JOIN #t8 t8
	ON mp2.PRODUCTSTRUCTUREID=t8.PARENTPRODUCTSTRUCTUREID
	WHERE mp2.LANGUAGEINDICATOR='E'
	
	SELECT DISTINCT lts1.PARTNAME,lts1.LANGUAGEINDICATOR,t9.RELATEDPARTNUMBER,t9.RELATEDPARTNAME,t9.TYPEINDICATOR,t9.PARTNUMBER
	INTO #t10
	FROM #t9 t9
	LEFT OUTER JOIN  SISWEB_OWNER.LNKTRANSLATEDSPN  lts1 
	ON (lts1.PARTNAME=t9.IEPARTNAME 
		AND lts1.LANGUAGEINDICATOR=t9.LANGUAGEINDICATOR
		AND lts1.LANGUAGEINDICATOR=t9.LANGUAGEINDICATOR)
	
	
	SELECT DISTINCT lts2.TRANSLATEDPARTNAME,t10.RELATEDPARTNUMBER,t10.RELATEDPARTNAME,t10.TYPEINDICATOR,t10.PARTNUMBER
	INTO #t11
	FROM #t10 t10
	LEFT OUTER JOIN  SISWEB_OWNER.LNKTRANSLATEDSPN  lts2 
	ON (lts2.PARTNAME=t10.RELATEDPARTNAME
		AND lts2.LANGUAGEINDICATOR=t10.LANGUAGEINDICATOR
		AND lts2.LANGUAGEINDICATOR=t10.LANGUAGEINDICATOR)
	
	SELECT DISTINCT	IESYSTEMCONTROLNUMBER,SNP,MEDIANUMBER
	INTO #t12
	FROM SISWEB_OWNER.lnkpartsiesnp
	WHERE MEDIANUMBER=@Media_Number
	
	SELECT DISTINCT lm.IESYSTEMCONTROLNUMBER,lm.IEPARTNUMBER AS PARTNUMBER,lm.IEPARTNAME,t12.SNP
	INTO #t13
	FROM 
	SISWEB_OWNER.lnkmediaiepart lm
	JOIN #t12 t12
	ON lm.IESYSTEMCONTROLNUMBER=t12.IESYSTEMCONTROLNUMBER
	
	SELECT DISTINCT  lp.CLASSICPARTINDICATOR,t13.IESYSTEMCONTROLNUMBER,t13.PARTNUMBER
	INTO #t14
	FROM SISWEB_OWNER.LNKPRODUCT lp
	JOIN #t13 t13
	ON lp.SNP=t13.SNP
	
	
	SELECT DISTINCT lrp.RELATEDPARTNUMBER,lrp.RELATEDPARTNAME,lrp.TYPEINDICATOR,lrp.PARTNUMBER,t14.IESYSTEMCONTROLNUMBER
	INTO #t15
	FROM SISWEB_OWNER.LNKRELATEDPARTINFO lrp 
	JOIN #t14 t14 
	ON lrp.PARTNUMBER=t14.PARTNUMBER
	WHERE lrp.TYPEINDICATOR <> 'K'
		AND lrp.TYPEINDICATOR <> 'E'
		AND lrp.TYPEINDICATOR <> CASE WHEN t14.CLASSICPARTINDICATOR = 'N' THEN 'CL' ELSE '' END
	
	
	SELECT DISTINCT lip.PSID,t15.RELATEDPARTNUMBER,t15.RELATEDPARTNAME,t15.TYPEINDICATOR,t15.PARTNUMBER
	INTO #t16
	FROM SISWEB_OWNER.lnkiepsid lip 
	JOIN #t15 t15
	ON lip.IESYSTEMCONTROLNUMBER=t15.IESYSTEMCONTROLNUMBER
	
	
	SELECT DISTINCT mp1.PARENTPRODUCTSTRUCTUREID,t16.RELATEDPARTNUMBER,t16.RELATEDPARTNAME,t16.TYPEINDICATOR,t16.PARTNUMBER
	INTO #t17
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp1
	JOIN #t16 t16 
	ON mp1.PRODUCTSTRUCTUREID=t16.PSID
	
	SELECT DISTINCT mp2.LANGUAGEINDICATOR,t17.RELATEDPARTNUMBER,t17.RELATEDPARTNAME,t17.TYPEINDICATOR,t17.PARTNUMBER 
	INTO #t18
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp2
	JOIN #t17 t17
	ON mp2.PRODUCTSTRUCTUREID=t17.PARENTPRODUCTSTRUCTUREID
	WHERE mp2.LANGUAGEINDICATOR='E'
	
	SELECT DISTINCT lts.TRANSLATEDPARTNAME,t18.RELATEDPARTNUMBER,t18.RELATEDPARTNAME,t18.TYPEINDICATOR,t18.PARTNUMBER
	INTO #t19
	FROM #t18 t18
	LEFT OUTER JOIN SISWEB_OWNER.LNKTRANSLATEDSPN lts ON 
	(lts.PARTNAME=t18.RELATEDPARTNAME
		AND lts.LANGUAGEINDICATOR=t18.LANGUAGEINDICATOR
		AND lts.LANGUAGEINDICATOR=t18.LANGUAGEINDICATOR)

	/*** KITS ****/

	SELECT DISTINCT p.Part_ID,t4.IEPARTNAME,t4.IESYSTEMCONTROLNUMBER,t4.PARTNUMBER
	INTO #t21
	FROM sis.Part p
	JOIN #t4 t4
	ON (p.Part_Number=t4.PARTNUMBER)

	SELECT DISTINCT kitparent.Kit_ID, t21.IEPARTNAME,t21.IESYSTEMCONTROLNUMBER, t21.PARTNUMBER
	INTO #t22
	FROM sis.Kit_ParentPart_Relation kitparent
	JOIN #t21 t21
	ON (kitparent.ParentPart_ID = t21.Part_ID)

	
	SELECT DISTINCT kit.Number as RELATEDPARTNUMBER, kit.Name as RELATEDPARTNAME, t22.PARTNUMBER, 
	kit.Part_Type as TYPEINDICATOR, t22.IEPARTNAME,t22.IESYSTEMCONTROLNUMBER
	INTO #t23
	FROM sis.Kit kit
	JOIN #t22 t22
	ON (kit.Kit_ID = t22.Kit_ID and kit.Long_Description is not null)

	SELECT DISTINCT lip.PSID,t23.RELATEDPARTNUMBER,t23.RELATEDPARTNAME,t23.TYPEINDICATOR,t23.PARTNUMBER
	INTO #t24
	FROM SISWEB_OWNER.lnkiepsid lip 
	JOIN #t23 t23
	ON lip.IESYSTEMCONTROLNUMBER=t23.IESYSTEMCONTROLNUMBER
	
	
	SELECT DISTINCT mp1.PARENTPRODUCTSTRUCTUREID,t24.RELATEDPARTNUMBER,t24.RELATEDPARTNAME,t24.TYPEINDICATOR,t24.PARTNUMBER
	INTO #t25
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp1
	JOIN #t24 t24 
	ON mp1.PRODUCTSTRUCTUREID=t24.PSID
	
	SELECT DISTINCT mp2.LANGUAGEINDICATOR,t25.RELATEDPARTNUMBER,t25.RELATEDPARTNAME,t25.TYPEINDICATOR,t25.PARTNUMBER 
	INTO #t26
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp2
	JOIN #t25 t25
	ON mp2.PRODUCTSTRUCTUREID=t25.PARENTPRODUCTSTRUCTUREID
	WHERE mp2.LANGUAGEINDICATOR='E'
	
	SELECT DISTINCT lts.TRANSLATEDPARTNAME,t26.RELATEDPARTNUMBER,t26.RELATEDPARTNAME,t26.TYPEINDICATOR,t26.PARTNUMBER
	INTO #t27
	FROM #t26 t26
	LEFT OUTER JOIN SISWEB_OWNER.LNKTRANSLATEDSPN lts ON 
	(lts.PARTNAME=t26.RELATEDPARTNAME
		AND lts.LANGUAGEINDICATOR=t26.LANGUAGEINDICATOR
		AND lts.LANGUAGEINDICATOR=t26.LANGUAGEINDICATOR)

	/** KITS MEDIA **/
	SELECT DISTINCT p.Part_ID,t13.PARTNUMBER,t13.IESYSTEMCONTROLNUMBER,t13.IEPARTNAME
	INTO #t28
	FROM sis.Part p
	JOIN #t13 t13
	ON (p.Part_Number=t13.PARTNUMBER)

	SELECT DISTINCT kitparent.Kit_ID, t28.IEPARTNAME,t28.IESYSTEMCONTROLNUMBER, t28.PARTNUMBER
	INTO #t29
	FROM sis.Kit_ParentPart_Relation kitparent
	JOIN #t28 t28
	ON (kitparent.ParentPart_ID = t28.Part_ID)

	
	SELECT DISTINCT kit.Number as RELATEDPARTNUMBER, kit.Name as RELATEDPARTNAME, t29.PARTNUMBER, 
	kit.Part_Type as TYPEINDICATOR, t29.IEPARTNAME,t29.IESYSTEMCONTROLNUMBER
	INTO #t30
	FROM sis.Kit kit
	JOIN #t29 t29
	ON (kit.Kit_ID = t29.Kit_ID and kit.Long_Description is not null)

	SELECT DISTINCT lip.PSID,t30.RELATEDPARTNUMBER,t30.RELATEDPARTNAME,t30.TYPEINDICATOR,t30.PARTNUMBER
	INTO #t31
	FROM SISWEB_OWNER.lnkiepsid lip 
	JOIN #t30 t30
	ON lip.IESYSTEMCONTROLNUMBER=t30.IESYSTEMCONTROLNUMBER
	
	
	SELECT DISTINCT mp1.PARENTPRODUCTSTRUCTUREID,t31.RELATEDPARTNUMBER,t31.RELATEDPARTNAME,t31.TYPEINDICATOR,t31.PARTNUMBER
	INTO #t32
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp1
	JOIN #t31 t31 
	ON mp1.PRODUCTSTRUCTUREID=t31.PSID
	
	SELECT DISTINCT mp2.LANGUAGEINDICATOR,t32.RELATEDPARTNUMBER,t32.RELATEDPARTNAME,t32.TYPEINDICATOR,t32.PARTNUMBER 
	INTO #t33
	FROM SISWEB_OWNER.MASPRODUCTSTRUCTURE mp2
	JOIN #t32 t32
	ON mp2.PRODUCTSTRUCTUREID=t32.PARENTPRODUCTSTRUCTUREID
	WHERE mp2.LANGUAGEINDICATOR='E'
	
	SELECT DISTINCT lts.TRANSLATEDPARTNAME,t33.RELATEDPARTNUMBER,t33.RELATEDPARTNAME,t33.TYPEINDICATOR,t33.PARTNUMBER
	INTO #t34
	FROM #t33 t33
	LEFT OUTER JOIN SISWEB_OWNER.LNKTRANSLATEDSPN lts ON 
	(lts.PARTNAME=t33.RELATEDPARTNAME
		AND lts.LANGUAGEINDICATOR=t33.LANGUAGEINDICATOR
		AND lts.LANGUAGEINDICATOR=t33.LANGUAGEINDICATOR)
	
	SELECT DISTINCT PARTNUMBER,RELATEDPARTNUMBER,coalesce(TRANSLATEDPARTNAME,RELATEDPARTNAME) as RELATEDPARTNAME,TYPEINDICATOR
	FROM #t11
	UNION
	SELECT DISTINCT PARTNUMBER,RELATEDPARTNUMBER,coalesce(TRANSLATEDPARTNAME,RELATEDPARTNAME) as RELATEDPARTNAME,TYPEINDICATOR 
	FROM #t19
	UNION
	SELECT DISTINCT PARTNUMBER,RELATEDPARTNUMBER,coalesce(TRANSLATEDPARTNAME,RELATEDPARTNAME) as RELATEDPARTNAME,TYPEINDICATOR 
	FROM #t27
	UNION
	SELECT DISTINCT PARTNUMBER,RELATEDPARTNUMBER,coalesce(TRANSLATEDPARTNAME,RELATEDPARTNAME) as RELATEDPARTNAME,TYPEINDICATOR 
	FROM #t34
END
