-- This Script needs to be run manually on the respective DB instances

-- DECLARE @START_SEQ NUMERIC (16)
-- SET @START_SEQ = (SELECT MAX(REPAIRSTATUSRID)+1 FROM [SISWEB_OWNER].[LNKCCRREPAIRSTATUS]);

-- DECLARE @sql NVARCHAR(200)
-- SET @sql = 'CREATE SEQUENCE [SISWEB_OWNER].[CCRREPAIRSTATUSSEQUENCE] 
--  AS [INT]
--  START WITH ' + CAST(@START_SEQ AS VARCHAR(50))
--  + 'INCREMENT BY 1'

-- EXEC(@sql)