CREATE TABLE [SISWEB_OWNER_SWAP].[LNKIEPSID] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [PSID]                  VARCHAR (8)   NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKIEPSID_PK_LNKIEPSID] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [PSID] ASC)
);




GO
CREATE NONCLUSTERED INDEX [NCX_LNKIEPSID_PSID]
    ON [SISWEB_OWNER_SWAP].[LNKIEPSID]([PSID] ASC, [MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [NCX_LNKIEPSID_MEDIANUMBER]
    ON [SISWEB_OWNER_SWAP].[LNKIEPSID]([MEDIANUMBER] ASC);


GO
EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER on 2020-05-12 14:18:08 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SWAP', @level1type = N'TABLE', @level1name = N'LNKIEPSID';




GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER on 2020-05-12 14:19:02 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SWAP', @level1type = N'TABLE', @level1name = N'LNKIEPSID';


GO

CREATE NONCLUSTERED INDEX [NCX_LNKIEPSID_IESYSTEMCONTROLNUMBER] ON [SISWEB_OWNER_SWAP].[LNKIEPSID] ([IESYSTEMCONTROLNUMBER] ASC);
