CREATE TABLE [sissearch2].[Basic_ServiceIE] (
    [ID]                    VARCHAR (50)    NOT NULL,
    [IESystemControlNumber] VARCHAR (15)    NOT NULL,
    [IETitle]               NVARCHAR (4000) NULL,
    [isMedia]               BIT             NOT NULL,
    [InfoTypeID]            VARCHAR (4000)  NULL,
    [DateUpdated]           DATE            NULL,
    [InsertDate]            DATETIME        NOT NULL,
    [PubDate]               DATETIME2 (7)   NOT NULL,
    [ControlNumber]         VARCHAR (4000)  NULL,
    [GraphicControlNumber]  VARCHAR (MAX)   NULL,
    [IETitle_es-ES]         NVARCHAR (4000) NULL,
    [IETitle_zh-CN]         NVARCHAR (4000) NULL,
    [IETitle_fr-FR]         NVARCHAR (4000) NULL,
    [IETitle_it-IT]         NVARCHAR (4000) NULL,
    [IETitle_de-DE]         NVARCHAR (4000) NULL,
    [IETitle_pt-BR]         NVARCHAR (4000) NULL,
    [IETitle_id-ID]         NVARCHAR (4000) NULL,
    [IETitle_ja-JP]         NVARCHAR (4000) NULL,
    [IETitle_ru-RU]         NVARCHAR (4000) NULL,
    [DateUpdated_es-ES]     DATE            NULL,
    [DateUpdated_zh-CN]     DATE            NULL,
    [DateUpdated_fr-FR]     DATE            NULL,
    [DateUpdated_it-IT]     DATE            NULL,
    [DateUpdated_de-DE]     DATE            NULL,
    [DateUpdated_pt-BR]     DATE            NULL,
    [DateUpdated_id-ID]     DATE            NULL,
    [DateUpdated_ja-JP]     DATE            NULL,
    [DateUpdated_ru-RU]     DATE            NULL,
    [PubDate_es-ES]         DATETIME2 (7)   NULL,
    [PubDate_zh-CN]         DATETIME2 (7)   NULL,
    [PubDate_fr-FR]         DATETIME2 (7)   NULL,
    [PubDate_it-IT]         DATETIME2 (7)   NULL,
    [PubDate_de-DE]         DATETIME2 (7)   NULL,
    [PubDate_pt-BR]         DATETIME2 (7)   NULL,
    [PubDate_id-ID]         DATETIME2 (7)   NULL,
    [PubDate_ja-JP]         DATETIME2 (7)   NULL,
    [PubDate_ru-RU]         DATETIME2 (7)   NULL,
    [mediaOrigin]           VARCHAR (2)     NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
    );