CREATE TABLE [sissearch2].[Consolidated_Media](
	[ID] [varchar](50) NOT NULL,
	[BaseEngMediaNumber] [varchar](15) NULL,
	[INSERTDATE] [datetime] NULL,
	[Media_Number] [varchar](15) NULL,
	[MediaTitle_en-US] [nvarchar](1536) NULL,
	[MediaTitle_es-ES] [nvarchar](1536) NULL,
	[MediaTitle_fr-FR] [nvarchar](1536) NULL,
	[MediaTitle_pt-BR] [nvarchar](1536) NULL,
	[MediaTitle_it-IT] [nvarchar](1536) NULL,
	[MediaTitle_id-ID] [nvarchar](1536) NULL,
	[MediaTitle_zh-CN] [nvarchar](1536) NULL,
	[MediaTitle_de-DE] [nvarchar](1536) NULL,
	[MediaTitle_ja-JP] [nvarchar](1536) NULL,
	[MediaTitle_ru-RU] [nvarchar](1536) NULL,
	[isMedia] [bit] NULL,
	[Profile] [varchar](max) NULL,
	[InformationType] [varchar](max) NULL,
	[SerialNumbers] [varchar](max) NULL,
	[ProductCode] [varchar](500) NULL,
	[UpdatedDate] [datetime] NULL,
	[PubDate] [datetime2](7) NULL,
	[RestrictionCode] [varchar](max) NULL,
	[PIPPSPNumber] [varchar](7) NULL,
	[familyCode] [varchar](max) NULL,
	[familySubFamilyCode] [varchar](max) NULL,
	[familySubFamilySalesModel] [varchar](max) NULL,
	[familySubFamilySalesModelSNP] [varchar](max) NULL,
	[MediaNumber_es-ES] [varchar](15) NULL,
	[MediaNumber_zh-CN] [varchar](15) NULL,
	[MediaNumber_fr-FR] [varchar](15) NULL,
	[MediaNumber_it-IT] [varchar](15) NULL,
	[MediaNumber_de-DE] [varchar](15) NULL,
	[MediaNumber_pt-BR] [varchar](15) NULL,
	[MediaNumber_id-ID] [varchar](15) NULL,
	[MediaNumber_ja-JP] [varchar](15) NULL,
	[MediaNumber_ru-RU] [varchar](15) NULL,
	[PubDate_es-ES] [datetime2](7) NULL,
	[PubDate_zh-CN] [datetime2](7) NULL,
	[PubDate_fr-FR] [datetime2](7) NULL,
	[PubDate_it-IT] [datetime2](7) NULL,
	[PubDate_de-DE] [datetime2](7) NULL,
	[PubDate_pt-BR] [datetime2](7) NULL,
	[PubDate_id-ID] [datetime2](7) NULL,
	[PubDate_ja-JP] [datetime2](7) NULL,
	[PubDate_ru-RU] [datetime2](7) NULL,
	[UpdatedDate_es-ES] [datetime] NULL,
	[UpdatedDate_zh-CN] [datetime] NULL,
	[UpdatedDate_fr-FR] [datetime] NULL,
	[UpdatedDate_it-IT] [datetime] NULL,
	[UpdatedDate_de-DE] [datetime] NULL,
	[UpdatedDate_pt-BR] [datetime] NULL,
	[UpdatedDate_id-ID] [datetime] NULL,
	[UpdatedDate_ja-JP] [datetime] NULL,
	[UpdatedDate_ru-RU] [datetime] NULL,
	[Media_Origin] [varchar](2) NULL,
 CONSTRAINT [PK_Consolidated_Media] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)
);
GO

ALTER TABLE [sissearch2].[Consolidated_Media] ENABLE CHANGE_TRACKING WITH(TRACK_COLUMNS_UPDATED = OFF);
GO

