CREATE TABLE [sissearch2].[KitConsistParts] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [ID]                    VARCHAR (50)  NOT NULL,
    [KITCONSISTPART]        VARCHAR (MAX) NULL,
    [INSERTDATE]            DATETIME      NOT NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);