BEGIN TRANSACTION;

DECLARE @ROWCOUNT INT;
SELECT @ROWCOUNT = COUNT(*) FROM EMP_STAGING._LAST_SYNCHRONIZATION_VERSIONS;

IF @ROWCOUNT = 0
BEGIN
	PRINT 'Populating Lookup Table [EMP_STAGING].[_LAST_SYNCHRONIZATION_VERSIONS]';

	INSERT INTO EMP_STAGING._LAST_SYNCHRONIZATION_VERSIONS
	SELECT s.name + '.' + t.name AS TABLENAME
		  ,tr.min_valid_version AS LAST_SYNCHRONIZATION_VERSION
	  FROM sys.change_tracking_tables AS tr
		   INNER JOIN sys.tables AS t ON t.object_id = tr.object_id
		   INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
	  WHERE s.name = 'EMP_STAGING'
	  ORDER BY 1
			  ,2;
END;
--ROLLBACK TRANSACTION
COMMIT TRANSACTION;
GO