-- This Script needs to be run manually on the respective DB instances

-- DECLARE @START_SEQ NUMERIC (10)
--  SET @START_SEQ = (SELECT MAX(VALUE)+1 
--                FROM ( select MAX(CCRMEDIARID) AS VALUE from SISWEB_OWNER_STAGING.MASCCRMEDIA UNION
-- 					  select MAX(SEGMENTRID) AS VALUE from SISWEB_OWNER_STAGING.MASCCRSEGMENTS UNION
-- 					  select MAX(OPERATIONRID) AS VALUE from SISWEB_OWNER_STAGING.MASCCROPERATIONS UNION
-- 				  	  select MAX(UPDATERID) AS VALUE from SISWEB_OWNER_STAGING.LNKCCRUPDATES
--                      ) AS T);

--  DECLARE @sql NVARCHAR(200)
--  SET @sql = 'CREATE SEQUENCE [SISWEB_OWNER_STAGING].[CCR_RID] 
--   AS [INT]
--   START WITH ' + CAST(@START_SEQ AS VARCHAR(50))
--   + 'INCREMENT BY 1'

--  EXEC(@sql)