CREATE TABLE [SISWEB_OWNER].[LNKASSHIPPEDPRODUCT] (
    [SERIALNUMBER]     VARCHAR (8)   NOT NULL,
    [EMDPROCESSEDDATE] DATETIME2 (0) NOT NULL,
    [BUILDDATE]        DATETIME2 (0) NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [LNKASSHIPPEDPRODUCT_PK_LAP1] PRIMARY KEY CLUSTERED ([SERIALNUMBER] ASC)
);

