CREATE TABLE [SISWEB_OWNER].[LNKATTACHMENTTYPETOPSID] (
    [ATTACHMENTTYPE] VARCHAR (6) NOT NULL,
    [PSID]           VARCHAR (8) NOT NULL,
    CONSTRAINT [LNKATTACHMENTTYPETOPSID_PK_LNKATTACHMENTTYPETOPSID] PRIMARY KEY CLUSTERED ([ATTACHMENTTYPE] ASC, [PSID] ASC)
);

