CREATE TABLE [SISWEB_OWNER].[LNKCCRVIRTUALIESCN]
(
	[SNP]                   VARCHAR(10)     NOT NULL, 
    [OPERATIONRID]          NUMERIC(10)     NOT NULL, 
    [IESYSTEMCONTROLNUMBER] VARCHAR(12)     NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_LNKCCRVIRTUALIESCN] PRIMARY KEY ([SNP] ASC, [OPERATIONRID] ASC, [IESYSTEMCONTROLNUMBER] ASC)
);

GO

CREATE NONCLUSTERED INDEX [IDX_LNKCCRVIRTUALIESCN_SNP_IESYSTEMCONTROLNUMBER] ON [SISWEB_OWNER].[LNKCCRVIRTUALIESCN] ([SNP], [IESYSTEMCONTROLNUMBER]);
