CREATE TABLE [SISWEB_OWNER].[LNKCCRUPDATEPARTS]
(
	[UPDATERID]         NUMERIC(10)     NOT NULL, 
    [LANGUAGEINDICATOR] VARCHAR(2)      NOT NULL, 
    [PARTNUMBER]        VARCHAR(20)     NOT NULL, 
    [PARTNAME]          NVARCHAR(288)   NOT NULL, 
    [QUANTITY]          NUMERIC(5)      NOT NULL,
    [LASTMODIFIEDDATE]  DATETIME2(6)    NULL, 
    CONSTRAINT [PK_LNKCCRUPDATEPARTS] PRIMARY KEY ([UPDATERID] ASC, [LANGUAGEINDICATOR] ASC, [PARTNUMBER] ASC, [QUANTITY] ASC) 
);
