CREATE TABLE [SISWEB_OWNER].[LNKCONFIGURATIONTYPE]
(
	[CONFIGURATIONTYPE]     CHAR(1)         NOT NULL,
    [TEXTRID]               NUMERIC         NOT NULL,
    [SEQUENCENO]            NUMERIC         NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_LNKCONFIGURATIONTYPE] PRIMARY KEY ([CONFIGURATIONTYPE] ASC)
);
