CREATE TABLE [SISWEB_OWNER].[LNKCCRUPDATES]
(
	[UPDATERID]             NUMERIC(10)     NOT NULL, 
    [OPERATIONRID]          NUMERIC(10)     NOT NULL, 
    [UPDATETYPEINDICATOR]   CHAR(1)         NOT NULL, 
    [IESYSTEMCONTROLNUMBER] VARCHAR(12)     NOT NULL, 
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_LNKCCRUPDATES] PRIMARY KEY ([UPDATERID] ASC)
);

GO

CREATE INDEX [IX_LNKCCRUPDATES_ISCNO] ON [SISWEB_OWNER].[LNKCCRUPDATES] ([IESYSTEMCONTROLNUMBER]);

GO

CREATE INDEX [IX_LNKCCRUPDATES_OPERID] ON [SISWEB_OWNER].[LNKCCRUPDATES] ([OPERATIONRID]) INCLUDE (UPDATERID);
