Create Table [SISWEB_OWNER].[LNKFILEDISPLAYTERMS] (
    FILERID             NUMERIC(38)         NOT NULL,
    DISPLAYTYPE         VARCHAR(8)          NOT NULL,
    VALUEDATATYPE       VARCHAR(5)          NULL,
    DISPLAYVALUE        VARCHAR(2000)       NULL,
    LANGUAGEINDICATOR   VARCHAR(2)          NOT NULL,
    LASTMODIFIEDDATE    DATETIME2(6)        NULL,
    CONSTRAINT [LNKFILEDISPLAYTERMS_PK_LNKFILEDISPLAYTERMS] PRIMARY KEY CLUSTERED ([FILERID] ASC, [DISPLAYTYPE] ASC, [LANGUAGEINDICATOR] ASC)
);