Create Table [SISWEB_OWNER].[LNKFILEREFERENCE] (
    FILERID           NUMERIC(38)       NOT NULL,
    LANGUAGEINDICATOR VARCHAR(2)        NOT NULL,
    REFERENCEFILERID  NUMERIC(38)       NOT NULL,
    LASTMODIFIEDDATE  DATETIME2(6)      NULL,
    CONSTRAINT [LNKFILEREFERENCE_PK_LNKFILEREFERENCE] PRIMARY KEY CLUSTERED ([FILERID] ASC, [REFERENCEFILERID] ASC, [LANGUAGEINDICATOR] ASC)
);