Create Table [SISWEB_OWNER].[LNKFLASHAPPLICATIONCODE] (
    APPLICATIONCODE     INT             NOT NULL,
    APPLICATIONDESC     VARCHAR(48)     NOT NULL,
    LANGUAGEINDICATOR   VARCHAR(2)      NOT NULL,
    LASTMODIFIEDDATE    DATETIME2(6)    NULL,
    [ISENGINERELATED]   BIT             NOT NULL DEFAULT 0, 
    CONSTRAINT [LNKFLASHAPPLICATIONCODE_PK_LNKFLASHAPPLICATIONCODE] PRIMARY KEY CLUSTERED ([APPLICATIONCODE] ASC, [LANGUAGEINDICATOR] ASC)
);