CREATE TABLE [SISWEB_OWNER].[LNKIEEFFECTIVEDATES] (
    [PARTNUMBER]            VARCHAR (7)   NOT NULL,
    [CONTROLNUMBER]         VARCHAR (12)  NOT NULL,
    [PREFIX]                VARCHAR (3)   NOT NULL,
    [SERIALNUMBERPREFIX]    VARCHAR (3)   NOT NULL,
    [BEGINRANGE]            INT           NOT NULL,
    [ENDRANGE]              INT           NOT NULL,
    [DAYEFFECTIVE]          VARCHAR (8)   NOT NULL,
    [DAYNOTEFFECTIVE]       VARCHAR (8)   NULL,
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (0) NULL,
    CONSTRAINT [PK_LNKIEEFFECTIVEDATES] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC, [CONTROLNUMBER] ASC, [PREFIX] ASC, [SERIALNUMBERPREFIX] ASC, [BEGINRANGE] ASC, [ENDRANGE] ASC, [DAYEFFECTIVE] ASC, [IESYSTEMCONTROLNUMBER] ASC)
);






GO


