CREATE TABLE [SISWEB_OWNER].[LNKIEPSID_BASE] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [PSID]                  VARCHAR (8)   NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKIEPSID_PK_LNKIEPSID] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [PSID] ASC) WITH (FILLFACTOR = 100)
);






GO
CREATE NONCLUSTERED INDEX NCX_LNKIEPSID_MEDIANUMBER ON SISWEB_OWNER.LNKIEPSID_BASE (MEDIANUMBER ASC) ON [PRIMARY];
GO

CREATE NONCLUSTERED INDEX NCX_LNKIEPSID_PSID ON SISWEB_OWNER.LNKIEPSID_BASE (PSID ASC,MEDIANUMBER ASC,IESYSTEMCONTROLNUMBER ASC) ON [PRIMARY];
GO

GO
CREATE NONCLUSTERED INDEX [NCX_LNKIEPSID_IESYSTEMCONTROLNUMBER] ON [SISWEB_OWNER].[LNKIEPSID_BASE] ([IESYSTEMCONTROLNUMBER] ASC);

GO
EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER_SHADOW on 2020-05-12 14:19:02 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER', @level1type = N'TABLE', @level1name = N'LNKIEPSID_BASE';


GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER_SHADOW on 2020-05-13 10:51:24 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER', @level1type = N'TABLE', @level1name = N'LNKIEPSID_BASE';
