CREATE TABLE [SISWEB_OWNER].[LNKIESMCS] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [SMCSCOMPCODE]          VARCHAR (4)   NOT NULL,
    [SMCSJOBCODE]           VARCHAR (3)   NOT NULL,
    [SMCSMODCODE]           VARCHAR (3)   NOT NULL,
    [SMCSTOOLCODE]          VARCHAR (4)   NOT NULL,
    [BASEIERID]             NUMERIC (16)  NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [PK__LNKIESMC__DFC6D531FE6DF0B2] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [SMCSCOMPCODE] ASC, [SMCSJOBCODE] ASC, [SMCSMODCODE] ASC, [SMCSTOOLCODE] ASC)
);

GO
CREATE NONCLUSTERED INDEX NCX_LNKIESMC_IESYSTEMCONTROLNUMBER
ON [SISWEB_OWNER].[LNKIESMCS] ([IESYSTEMCONTROLNUMBER]);