CREATE TABLE [SISWEB_OWNER].[LNKIEDATE] (
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [DATEUPDATED]           DATETIME2 (0) NOT NULL,
    [IEPUBDATE]             DATETIME2 (0) NOT NULL,
    [LANGUAGEINDICATOR]     VARCHAR (2)   NOT NULL,
    [IERID]                 NUMERIC (16)  NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKIEDATE_PK_LNKIEDATE] PRIMARY KEY CLUSTERED ([IESYSTEMCONTROLNUMBER] ASC, [DATEUPDATED] ASC, [IEPUBDATE] ASC, [LANGUAGEINDICATOR] ASC)
);
GO

CREATE NONCLUSTERED INDEX [nci_wi_LNKIEDATE_3C42536B1173058D8BCF787C7E27926E] ON [SISWEB_OWNER].[LNKIEDATE] ([LANGUAGEINDICATOR]) WITH (ONLINE = ON)

GO

CREATE NONCLUSTERED INDEX IX_NCL_IESYSTEMCONTROLNUMBER ON [SISWEB_OWNER].[LNKIEDATE] ([IESYSTEMCONTROLNUMBER]);