CREATE TABLE [SISWEB_OWNER].[LNKIEEFFECTIVITY] (
    [MEDIANUMBER]   VARCHAR (8)  NOT NULL,
    [IESCN]         VARCHAR (12) NOT NULL,
    [TYPEINDICATOR] VARCHAR (1)  NOT NULL,
    [EFFECTIVITY]   VARCHAR (10) NOT NULL,
    CONSTRAINT [LNKIEEFFECTIVITY_PK_LNKIEEFFECTIVITY] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESCN] ASC, [TYPEINDICATOR] ASC, [EFFECTIVITY] ASC)
);