CREATE TABLE [SISWEB_OWNER].[LNKMEDIAIE] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [SECTIONNUMBER]         SMALLINT      NOT NULL,
    [IETITLESEQNUMBER]      SMALLINT      NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKMEDIAIE_PK_LNKMEDIAIE] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC)
);
GO

CREATE NONCLUSTERED INDEX IX_LNKMEDIAIE_IESYSTEMCONTROLNUMBER ON SISWEB_OWNER.LNKMEDIAIE (IESYSTEMCONTROLNUMBER) INCLUDE (SECTIONNUMBER);
GO
