CREATE TABLE [SISWEB_OWNER].[LNKMEDIAEFFECTIVITY] (
    [MEDIANUMBER]   VARCHAR (8)  NOT NULL,
    [TYPEINDICATOR] VARCHAR (1)  NOT NULL,
    [EFFECTIVITY]   VARCHAR (10) NOT NULL,
    CONSTRAINT [LNKMEDIAEFFECTIVITY_PK_LNKMEDIAEFFECTIVITY] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [TYPEINDICATOR] ASC, [EFFECTIVITY] ASC)
);