CREATE TABLE [SISWEB_OWNER].[LNKMEDIASNP] (
    [MEDIANUMBER]      VARCHAR (8)   NOT NULL,
    [SNP]              VARCHAR (10)  NOT NULL,
    [BEGINNINGRANGE]   INT           NOT NULL,
    [ENDRANGE]         INT           NOT NULL,
    [INFOTYPEID]       SMALLINT      NOT NULL,
    [TYPEINDICATOR]    VARCHAR (1)   NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [LNKMEDIASNP_PK_LNKMEDIASNP] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC, [INFOTYPEID] ASC, [TYPEINDICATOR] ASC)
);
GO

CREATE NONCLUSTERED INDEX [IX_LNKMEDIASNP_TYPEINDICATOR]
    ON [SISWEB_OWNER].[LNKMEDIASNP]([SNP] ASC, [TYPEINDICATOR] ASC);
GO

CREATE NONCLUSTERED INDEX [nci_wi_LNKMEDIASNP_6B1E943B561EFADFA150AD3D95935776]
    ON [SISWEB_OWNER].[LNKMEDIASNP]([INFOTYPEID] ASC);

