CREATE TABLE [SISWEB_OWNER].[LNKMEDIAARRANGEMENT] (
    [MEDIANUMBER]      VARCHAR (8)   NOT NULL,
    [ARRANGEMENTNO]    VARCHAR (20)  NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [LNKMEDIAARRANGEMENT_PK_LNKMEDIAARRANGEMENT] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [ARRANGEMENTNO] ASC)
);




GO
CREATE NONCLUSTERED INDEX [IX_LNKMEDIAARRANGEMENT_ARRANGEMENTNO]
    ON [SISWEB_OWNER].[LNKMEDIAARRANGEMENT]([ARRANGEMENTNO] ASC);

