CREATE TABLE [SISWEB_OWNER].[LNKNPRINFORECTYPE456] (
    [PRIMARYSEQNO]             INT          NOT NULL,
    [RECORDTYPE]               VARCHAR (1)  NOT NULL,
    [SEQUENCENUMBER]           INT          NOT NULL,
    [COLUMNDATA]               VARCHAR (64) NULL,
    [QUANTITYRECTYPE5]         SMALLINT     NULL,
    [SERIALNUMBERSYMBOL]       VARCHAR (1)  NULL,
    [SERIALNUMBERPREFIX]       VARCHAR (4)  NULL,
    [EFFECTIVESERIALNUMBER]    VARCHAR (5)  NULL,
    [DISCONTINUEDSERIALNUMBER] VARCHAR (5)  NULL,
    [QUANTITYRECTYPE6]         SMALLINT     NULL,
    [GROUPNUMBER]              VARCHAR (10) NULL,
    [ENGINEERINGCHANGE]        VARCHAR (5)  NULL,
    [NPRINDICATOR]             VARCHAR (20) NULL,
    CONSTRAINT [LNKNPRINFORECTYPE456_PK_LNKNPRINFORECTYPE456] PRIMARY KEY CLUSTERED ([PRIMARYSEQNO] ASC, [RECORDTYPE] ASC, [SEQUENCENUMBER] ASC)
);

