CREATE TABLE [SISWEB_OWNER].[LNKPDFPRODUCTINSTANCE_BASE] (
    [PARTSPDF_ID]           INT    NOT NULL,
    [EMPPRODUCTINSTANCE_ID] INT    NOT NULL,
    CONSTRAINT [PK_LNKPDFPRODUCTINSTANCE] PRIMARY KEY CLUSTERED ([PARTSPDF_ID] ASC, [EMPPRODUCTINSTANCE_ID] ASC)
);

GO
CREATE NONCLUSTERED INDEX idx_LNKPDFPRODUCTINSTANCE_PARTSPDF_ID_EMPPRODUCTINSTANCE_ID ON SISWEB_OWNER.LNKPDFPRODUCTINSTANCE_BASE (PARTSPDF_ID ASC, EMPPRODUCTINSTANCE_ID ASC);

GO
EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER_SHADOW on 2020-05-08 12:20:00 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER', @level1type = N'TABLE', @level1name = N'LNKPDFPRODUCTINSTANCE_BASE';


GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER_SHADOW on 2020-05-08 12:23:11 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER', @level1type = N'TABLE', @level1name = N'LNKPDFPRODUCTINSTANCE_BASE';
