CREATE TABLE [SISWEB_OWNER].[LNKPARTSIESNP_BASE] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [SNP]                   VARCHAR (10)  NOT NULL,
    [BEGINNINGRANGE]        INT           NOT NULL,
    [ENDRANGE]              INT           NOT NULL,
    [SNPTYPE]               VARCHAR (6)   NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKPARTSIESNP_PK_LNKPARTSIESNP] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC, [SNPTYPE] ASC) WITH (FILLFACTOR = 100)
);






GO

CREATE NONCLUSTERED INDEX NCX_LNKPARTSIESNP_SNP_BEGINNINGRANGE_ENDRANGE ON SISWEB_OWNER.LNKPARTSIESNP_BASE (SNP ASC,BEGINNINGRANGE ASC,ENDRANGE ASC) ;
GO

CREATE NONCLUSTERED INDEX [NCX_LNKPARTSIESNP_IESystemControlNumber] ON [SISWEB_OWNER].[LNKPARTSIESNP_BASE] 
( 
[IESYSTEMCONTROLNUMBER] ASC 
) 
GO


GO

EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER_SHADOW on 2020-05-14 11:56:17 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER', @level1type = N'TABLE', @level1name = N'LNKPARTSIESNP_BASE';


GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER_SHADOW on 2020-05-14 11:57:15 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER', @level1type = N'TABLE', @level1name = N'LNKPARTSIESNP_BASE';


GO
CREATE NONCLUSTERED INDEX [NCX_LNPPARTSIESNP_SNPTYPE]
    ON [SISWEB_OWNER].[LNKPARTSIESNP_BASE]([SNP] ASC, [SNPTYPE] ASC);

