CREATE TABLE [SISWEB_OWNER].[LNKRELATEDPARTINFO] (
    [PARTNUMBER]        VARCHAR (20)  NOT NULL,
    [TYPEINDICATOR]     VARCHAR (2)   NOT NULL,
    [RELATEDPARTNUMBER] VARCHAR (20)  NOT NULL,
    [RELATEDPARTNAME]   VARCHAR (256) NULL,
    [NPRINDICATOR]      VARCHAR (1)   NULL,
    [RELATION_TYPE]     VARCHAR (50) NULL,
    [LASTMODIFIEDDATE]  DATETIME2 (6) NULL,
    CONSTRAINT [LNKRELATEDPARTINFO_PK_LNKRELATEDPARTINFO] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC, [TYPEINDICATOR] ASC, [RELATEDPARTNUMBER] ASC)
);

GO
CREATE NONCLUSTERED INDEX IDX_LNKRELATEDPARTINFO_RELATEDPARTNUMBER ON 
[SISWEB_OWNER].[LNKRELATEDPARTINFO] ([RELATEDPARTNUMBER]) INCLUDE ([RELATEDPARTNAME]);

GO
CREATE NONCLUSTERED INDEX [IDX_LNKRELATEDPARTINFO_TYPEINDICATOR] ON [SISWEB_OWNER].[LNKRELATEDPARTINFO] 
([TYPEINDICATOR] ASC) INCLUDE ([RELATEDPARTNUMBER],[RELATEDPARTNAME]) WHERE (TYPEINDICATOR <>'K' AND TYPEINDICATOR <> 'E');
