CREATE TABLE [SISWEB_OWNER].[LNKRELATEDPARTIES] (
    [IESCN]            VARCHAR (12) NOT NULL,
    [RELATEDIESCN]     VARCHAR (12) NOT NULL,
    [LASTMODIFIEDDATE] VARCHAR (50) NULL,
    CONSTRAINT [PK_LNKRELATEDPARTIES] PRIMARY KEY CLUSTERED ([IESCN] ASC, [RELATEDIESCN] ASC)
);




GO
CREATE NONCLUSTERED INDEX [NCX_LNKRELATEDPARTIES_IESCN]
    ON [SISWEB_OWNER].[LNKRELATEDPARTIES]([IESCN] ASC)
    INCLUDE([RELATEDIESCN]);

