CREATE TABLE [SISWEB_OWNER].[LNKSERIALPART] (
    [SERIALNUMBER]          VARCHAR (8)   NULL,
    [FUELSPECIFICATIONNO]   VARCHAR (8)   NULL,
    [ARRANGEMENTPARTNUMBER] VARCHAR (20)  NOT NULL,
    [ENGINEERINGMODELNO]    VARCHAR (10)  NULL,
    [SHIPDATE]              DATETIME2 (0) NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL
);






GO
CREATE NONCLUSTERED INDEX [IX_LNKSERIALPART_SERIALNUMBER]
    ON [SISWEB_OWNER].[LNKSERIALPART]([SERIALNUMBER] ASC);

