CREATE TABLE [SISWEB_OWNER].[LNKTRANSLATEDSPN] (
    [PARTNAME]           VARCHAR (200)  NOT NULL,
    [LANGUAGEINDICATOR]  VARCHAR (2)    NOT NULL,
    [TRANSLATEDPARTNAME] NVARCHAR (200) NOT NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6)  NULL,
    CONSTRAINT [LNKTRANSLATEDSPN_LNKTRANSLATEDSPN_PK] PRIMARY KEY CLUSTERED ([PARTNAME] ASC, [LANGUAGEINDICATOR] ASC)
);

GO
CREATE NONCLUSTERED INDEX [IX_LNKTRANSLATEDSPN_LANGUAGEINDICATOR]
    ON [SISWEB_OWNER].[LNKTRANSLATEDSPN]([LANGUAGEINDICATOR] ASC)
    INCLUDE([TRANSLATEDPARTNAME])

GO

CREATE INDEX IX_NCL_LNKTRANSLATEDSPN_PARTNAME 
    ON [SISWEB_OWNER].[LNKTRANSLATEDSPN] (PARTNAME) 
    INCLUDE (TRANSLATEDPARTNAME,LANGUAGEINDICATOR)