CREATE TABLE [SISWEB_OWNER].[MASCCROPERATIONS]
(
	[OPERATIONRID]          NUMERIC(10)     NOT NULL ,
    [SEGMENTRID]            NUMERIC(10)     NOT NULL,
    [OPERATION]             VARCHAR(5)      NOT NULL,
    [OPERATIONNUMBER]       VARCHAR(5)      NOT NULL,
    [COMPONENTCODE]         VARCHAR(4)      NOT NULL,
    [JOBCODE]               VARCHAR(3)      NOT NULL,
    [MODIFIERCODE]          VARCHAR(3)      NULL,
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_MASCCROPERATIONS] PRIMARY KEY ([OPERATIONRID] ASC)
);

GO
CREATE INDEX [IX_MASCCROPERATIONS_SRID_ORID] ON [SISWEB_OWNER].[MASCCROPERATIONS] ([SEGMENTRID], [OPERATIONRID]) INCLUDE (OPERATION,COMPONENTCODE,JOBCODE,MODIFIERCODE);

GO
CREATE INDEX [IX_MASCCROPERATIONS_SRID_ORID_OPERATIONNUMBER] ON [SISWEB_OWNER].[MASCCROPERATIONS] ([SEGMENTRID], [OPERATIONRID]) INCLUDE (OPERATIONNUMBER,COMPONENTCODE,JOBCODE,MODIFIERCODE);
