CREATE TABLE [SISWEB_OWNER].[MASCCRSEGMENTS]
(
	[SEGMENTRID]			NUMERIC(10)		NOT NULL,
	[CCRMEDIARID]			NUMERIC(10)		NOT NULL,
	[SEGMENT]				VARCHAR(5)		NOT NULL,
	[COMPONENTCODE]			VARCHAR(4)		NOT NULL,
	[JOBCODE]				VARCHAR(3)		NOT NULL,
	[MODIFIERCODE]			VARCHAR(3)		NULL,
	[HOURS]					NUMERIC(6,1)	NOT NULL,
	[LASTMODIFIEDDATE]      DATETIME2(6)    NULL, 
	CONSTRAINT [PK_MASCCRSEGMENTS] PRIMARY KEY ([SEGMENTRID] ASC)
);

GO

CREATE INDEX [IX_MASCCRSEGMENTS_MRID_SRID] ON [SISWEB_OWNER].[MASCCRSEGMENTS] ([CCRMEDIARID], [SEGMENTRID]) INCLUDE (SEGMENT);
