CREATE TABLE [SISWEB_OWNER].[MASCCRREPAIRTYPES]
(
	[REPAIRTYPEINDICATOR]   CHAR(1)         NOT NULL, 
    [LANGUAGEINDICATOR]     VARCHAR(2)      NOT NULL, 
    [REPAIRTYPE]            NVARCHAR(400)   NOT NULL, 
    [REPAIRTYPEDESCRIPTION] NVARCHAR(400)   NOT NULL, 
    [SEQUENCENUMBER]        NUMERIC(5)      NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2(6)    NULL,
    CONSTRAINT [PK_MASCCRREPAIRTYPES] PRIMARY KEY ([REPAIRTYPEINDICATOR] ASC, [LANGUAGEINDICATOR] ASC)
);

