CREATE TABLE [SISWEB_OWNER].[MASLANGUAGE] (
    [LANGUAGEINDICATOR] VARCHAR (2)   NOT NULL,
    [LANGUAGEDESC]      NVARCHAR (50) NOT NULL,
    [USERLOCALE]        VARCHAR (10)  NOT NULL,
    [LANGUAGE_TAG]      VARCHAR (50)  NULL,
    CONSTRAINT [MASLANGUAGE_PK_MASLANGUAGE] PRIMARY KEY CLUSTERED ([LANGUAGEINDICATOR] ASC)
);

