CREATE TABLE [SISWEB_OWNER].[MASMEDIA] (
    [MEDIANUMBER]             VARCHAR (8)      NOT NULL,
    [MEDIATITLE]              NVARCHAR (1536)  NOT NULL,
    [PUBLISHEDDATE]           DATETIME2 (0)    NOT NULL,
    [MEDIAUPDATEDDATE]        DATETIME2 (0)    NULL,
    [MEDIASOURCE]             VARCHAR (1)      NOT NULL,
    [REVISIONNO]              NUMERIC (38, 10) NULL,
    [SAFETYDOCUMENTINDICATOR] VARCHAR (1)      NOT NULL,
    [BASEENGLISHMEDIANUMBER]  VARCHAR (8)      NOT NULL,
    [NPRMEDIAREFERENCE]       VARCHAR (8)      NULL,
    [PIPPSPNUMBER]            VARCHAR (7)      NULL,
    [LANGUAGEINDICATOR]       VARCHAR (2)      NOT NULL,
    [MEDIARID]                NUMERIC (16)     NULL,
    [LASTMODIFIEDDATE]        DATETIME2 (6)    NULL,
    [MEDIAORIGIN]              VARCHAR (2)      NULL,
    CONSTRAINT [MASMEDIA_PK_MASMEDIA] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC) 
);






GO
CREATE NONCLUSTERED INDEX [MASMEDIA_LANGUAGEINDICATOR]
    ON [SISWEB_OWNER].[MASMEDIA]([LANGUAGEINDICATOR] ASC, [BASEENGLISHMEDIANUMBER] ASC)
    INCLUDE([MEDIATITLE], [MEDIASOURCE]) WITH (FILLFACTOR = 100, DATA_COMPRESSION = PAGE);

GO

CREATE NONCLUSTERED INDEX [IX_NCL_MASMEDIA_MEDIAORIGIN] ON [SISWEB_OWNER].[MASMEDIA] ([MEDIAORIGIN])

GO