CREATE TABLE [SISWEB_OWNER].[MASPRODUCT_PARTIAL] (
    [ID]                 INT            NOT NULL,
    [PRODUCTCODE]        VARCHAR (4)    NOT NULL,
    [PRODUCTTYPE]        CHAR (1)       NOT NULL,
    [PRODUCTDESCRIPTION] NVARCHAR (600) NOT NULL,
    [FREQUENCY]          CHAR (1)       NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6)  NULL,
    CONSTRAINT [PK_MASPRODUCT_PARTIAL] PRIMARY KEY CLUSTERED ([ID] ASC)
);
