CREATE TABLE [SISWEB_OWNER].[MASPRODUCTSTRUCTURE] (
    [ID]                          INT            IDENTITY (1, 1) NOT NULL,
    [PRODUCTSTRUCTUREID]          CHAR (8)       NOT NULL,
    [LANGUAGEINDICATOR]           VARCHAR (2)    NOT NULL,
    [PARENTPRODUCTSTRUCTUREID]    CHAR (8)       NOT NULL,
    [PRODUCTSTRUCTUREDESCRIPTION] NVARCHAR (192) NOT NULL,
    [PARENTAGE]                   NUMERIC (1)    NOT NULL,
    [MISCSPNINDICATOR]            CHAR (1)       NOT NULL,
    [LASTMODIFIEDDATE]            DATETIME2 (6)  NULL,
    CONSTRAINT [PK_MASPRODUCTSTRUCTURE_] PRIMARY KEY CLUSTERED ([PRODUCTSTRUCTUREID] ASC, [LANGUAGEINDICATOR] ASC, [PARENTPRODUCTSTRUCTUREID] ASC)
);






GO
CREATE NONCLUSTERED INDEX [IX_MASPRODUCTSTRUCTURE_LI]
    ON [SISWEB_OWNER].[MASPRODUCTSTRUCTURE]([LANGUAGEINDICATOR] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MASPRODUCTSTRUCTURE_PSID_LI]
    ON [SISWEB_OWNER].[MASPRODUCTSTRUCTURE]([PRODUCTSTRUCTUREID] ASC, [LANGUAGEINDICATOR] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_MASPRODUCTSTRUCTURE_LANGUAGEINDICATOR]
    ON [SISWEB_OWNER].[MASPRODUCTSTRUCTURE]([LANGUAGEINDICATOR] ASC)
    INCLUDE([ID], [PRODUCTSTRUCTUREDESCRIPTION], [PARENTAGE], [MISCSPNINDICATOR]);

