CREATE TABLE [SISWEB_OWNER].[MASPRODUCT] (
    [PRODUCTCODE]        VARCHAR (4)    NOT NULL,
    [SEQUENCENUMBER]     NUMERIC (3)    NOT NULL,
    [LANGUAGEINDICATOR]  VARCHAR (2)    NOT NULL,
    [PRODUCTTYPE]        CHAR (1)       NOT NULL,
    [PRODUCTDESCRIPTION] NVARCHAR (600) NOT NULL,
    [FREQUENCY]          CHAR (1)       NULL,
    [ID]                 INT            IDENTITY (1, 1) NOT NULL,
    [LASTMODIFIEDDATE]   DATETIME2 (6)  NULL,
    CONSTRAINT [PK_MASPRODUCT_] PRIMARY KEY CLUSTERED ([ID] ASC),
    CONSTRAINT [CK_MASPRODUCT_LI_] CHECK ([LANGUAGEINDICATOR]=upper([LANGUAGEINDICATOR]))
);




GO
CREATE NONCLUSTERED INDEX [IX_MASPRODUCT_LANGUAGEINDICATOR_PRODUCTTYPE]
    ON [SISWEB_OWNER].[MASPRODUCT]([LANGUAGEINDICATOR] ASC, [PRODUCTTYPE] ASC)
    INCLUDE([PRODUCTCODE], [PRODUCTDESCRIPTION]);

