CREATE TABLE [SISWEB_OWNER].[MASREPAIRDESCRIPTIONS]
(
	[REPAIRCODE]        VARCHAR(4)      NOT NULL, 
    [REPAIRTYPE]        CHAR(1)         NOT NULL, 
    [LANGUAGEINDICATOR] VARCHAR(2)      NOT NULL, 
    [REPAIRDESCRIPTION] NVARCHAR(288)   NOT NULL, 
    [LASTMODIFIEDDATE]  DATETIME2(6)    NULL, 
    CONSTRAINT [PK_MASREPAIRDESCRIPTIONS] PRIMARY KEY CLUSTERED ([REPAIRCODE] ASC, [REPAIRTYPE] ASC, [LANGUAGEINDICATOR] ASC)
);
