CREATE TABLE [SISWEB_OWNER].[MASSMCS_Original] (
    [SMCSCOMPCODE]      VARCHAR (4)    NOT NULL,
    [LANGUAGEINDICATOR] VARCHAR (2)    NOT NULL,
    [MAJORDIVISIONCODE] VARCHAR (4)    NOT NULL,
    [SMCSDESCRIPTION]   NVARCHAR (192) NOT NULL,
    [CURRENTINDICATOR]  VARCHAR (1)    NOT NULL,
    CONSTRAINT [MASSMCS_PK_MASSMCS_SWAP] PRIMARY KEY CLUSTERED ([SMCSCOMPCODE] ASC, [LANGUAGEINDICATOR] ASC)
);

