CREATE TABLE [SISWEB_OWNER].[MASSNP] (
    [CAPTIVESERIALNUMBERPREFIX] VARCHAR (10)  NOT NULL,
    [BEGINNINGRANGE]            NUMERIC (5)   NOT NULL,
    [ENDRANGE]                  NUMERIC (5)   NOT NULL,
    [PRIMESERIALNUMBERPREFIX]   VARCHAR (10)  NOT NULL,
    [MEDIANUMBER]               CHAR (8)      NOT NULL,
    [DOCUMENTTITLE]             VARCHAR (512) NOT NULL,
    [CONFIGURATIONTYPE]         CHAR (1)      DEFAULT ('S') NOT NULL,
    [ID]                        INT           IDENTITY (1, 1) NOT NULL,
	[LASTMODIFIEDDATE]     DATETIME2 (6) NULL,
    CONSTRAINT [PK_MASSNP_] PRIMARY KEY CLUSTERED ([ID] ASC)
);


GO


CREATE NONCLUSTERED INDEX [NCX_MASSNP_PRIMESERIALNUMBERPREFIX] ON [SISWEB_OWNER].[MASSNP] ([PRIMESERIALNUMBERPREFIX] ASC) include([CAPTIVESERIALNUMBERPREFIX],[BEGINNINGRANGE]);
GO