CREATE TABLE [SISWEB_OWNER].[MASSMCS] (
    [SMCSCOMPCODE]      CHAR (4)       NOT NULL,
    [LANGUAGEINDICATOR] VARCHAR (2)    NOT NULL,
    [MAJORDIVISIONCODE] CHAR (4)       NOT NULL,
    [SMCSDESCRIPTION]   NVARCHAR (192) NOT NULL,
    [CURRENTINDICATOR]  CHAR (1)       DEFAULT ('N') NOT NULL,
    [ID]                INT            IDENTITY (1, 1) NOT NULL,
    [LASTMODIFIEDDATE]  DATETIME2 (6)  NULL,
    CONSTRAINT [PK_MASSMCS_] PRIMARY KEY CLUSTERED ([ID] ASC)
);






GO
CREATE NONCLUSTERED INDEX [IX_MASSMCS_SMCSCOMPCODE_LANGUAGEINDICATOR]
    ON [SISWEB_OWNER].[MASSMCS]([SMCSCOMPCODE] ASC, [LANGUAGEINDICATOR] ASC)
    INCLUDE([SMCSDESCRIPTION]);

