CREATE TABLE [SISWEB_OWNER].[MV_KITDATA] (
    [PARTNUMBER]       VARCHAR (20)  NOT NULL,
    [KITPARTNUMBER]    VARCHAR (20)  NOT NULL,
    [KITPARTNAME]      VARCHAR (200) NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6) NULL,
    CONSTRAINT [pk_kitpart] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC, [KITPARTNUMBER] ASC)
);



