CREATE TABLE [SISWEB_OWNER].[SIS2NPRPARTHISTORY] (
    [PARTNUMBER]       VARCHAR (20)   NOT NULL,
    [HISTORYCHAIN]     VARCHAR (4000) NOT NULL,
    [LASTMODIFIEDDATE] DATETIME2 (6)  NULL,
    CONSTRAINT [SIS2NPRPARTHISTORY_SIS2NPRPARTHISTORY_PK] PRIMARY KEY CLUSTERED ([PARTNUMBER] ASC, [HISTORYCHAIN] ASC)
);


GO
CREATE NONCLUSTERED INDEX [SIS2NPRPARTHISTORY_PARTNUMBER]
    ON [SISWEB_OWNER].[SIS2NPRPARTHISTORY]([PARTNUMBER] ASC)
    INCLUDE([HISTORYCHAIN]);

