CREATE TABLE [SISWEB_OWNER].[SIS2ASSHIPPEDENGINE] (
    [SERIALNUMBER]        VARCHAR (8)   NOT NULL,
    [PARTSEQUENCENUMBER]  NUMERIC (10)  NOT NULL,
    [PARTNUMBER]          VARCHAR (20)  NULL,
    [PARTNAME]            VARCHAR (512) NULL,
    [QUANTITY]            VARCHAR (8)   NULL,
    [ENGGCHANGELEVELNO]   VARCHAR (4)   NULL,
    [ASSEMBLY]            VARCHAR (1)   NULL,
    [LESSINDICATOR]       VARCHAR (1)   NULL,
    [INDENTATION]         VARCHAR (1)   NULL,
    [UPDATEDATETIME]      DATETIME2 (6) NULL,
    [isValidSerialNumber] BIT           NULL,
    [isValidPartNumber]   BIT           NULL,
    [ID]                  INT           NULL,
    [ParentID]            INT           NULL,
    [SNP]                 CHAR (3)      NULL,
    [SNR]                 INT           NULL,
    CONSTRAINT [SIS2ASSHIPPEDENGINE_SIS2ASSHIPPEDENGINE_PK] PRIMARY KEY CLUSTERED ([SERIALNUMBER] ASC, [PARTSEQUENCENUMBER] ASC) WITH (FILLFACTOR = 100)
);
GO

CREATE NONCLUSTERED INDEX [SIS2ASSHIPPEDENGINE_IndSerSeq_NC]
    ON [SISWEB_OWNER].[SIS2ASSHIPPEDENGINE]([SERIALNUMBER] ASC, [PARTSEQUENCENUMBER] ASC, [INDENTATION] ASC)
    INCLUDE([ID]) WITH (FILLFACTOR = 100);
GO

CREATE NONCLUSTERED INDEX [SIS2ASSHIPPEDENGINE_IsValid_NC]
    ON [SISWEB_OWNER].[SIS2ASSHIPPEDENGINE]([isValidSerialNumber] ASC, [isValidPartNumber] ASC, [ParentID] ASC)
    INCLUDE([PARTNUMBER]);
GO

CREATE NONCLUSTERED INDEX [SIS2ASSHIPPEDENGINE_PARTNUMBER_NC]
    ON [SISWEB_OWNER].[SIS2ASSHIPPEDENGINE]([SERIALNUMBER] ASC, [PARTNUMBER] ASC) WITH (FILLFACTOR = 100);
GO

CREATE NONCLUSTERED INDEX [SIS2ASSHIPPEDENGINE_PARTSEQUENCENUMBER_NC]
    ON [SISWEB_OWNER].[SIS2ASSHIPPEDENGINE]([PARTSEQUENCENUMBER] ASC, [SNR] ASC)
    INCLUDE([ID], [SNP]) WITH (FILLFACTOR = 100);
GO

