CREATE TABLE [SISWEB_OWNER].[SIS2IEEFFECTIVITY] (
    [MEDIANUMBER]           VARCHAR (8)  NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12) NOT NULL,
    [TYPEINDICATOR]         VARCHAR (1)  NOT NULL,
    [EFFECTIVITY]           VARCHAR (10) NOT NULL,
    [LASTMODIFIEDDATE]      VARCHAR (50) NULL,
    CONSTRAINT [SIS2IEEFFECTIVITY_SIS2IEEFFECTIVITY_PK] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [TYPEINDICATOR] ASC, [EFFECTIVITY] ASC)
);



 



GO
CREATE NONCLUSTERED INDEX [IX_SIS2IEEFFECTIVITY]
    ON [SISWEB_OWNER].[SIS2IEEFFECTIVITY]([EFFECTIVITY] ASC);


GO
CREATE NONCLUSTERED INDEX [IX_SIS2IEEFFECTIVITY_IESYSTEMCONTROLNUMBER]
    ON [SISWEB_OWNER].[SIS2IEEFFECTIVITY]([IESYSTEMCONTROLNUMBER] ASC);

