CREATE TABLE [KIM].[SIS_KitNumbers] (
    [KITNUMBER]      NVARCHAR (7)   NULL,
    [PARTNAME]       NVARCHAR (500) NULL,
    [DISPLAYNAME]    NVARCHAR (500) NULL,
    [PARTTYPE]       NVARCHAR (20)  NULL,
    [SERVICEABILITY] NVARCHAR (25)  NULL,
    [DRAWINGSTATUS]  NVARCHAR (25)  NULL,
    [LONGDESCRIPTION] NVARCHAR (2000) NULL,
	[CHG. LVL] [nvarchar](4) NULL,
	[VERSION] [nvarchar](2) NULL,
	[DESIGNCONTROLCODE] [nvarchar](5) NULL,
	[KITTYPE] [nvarchar](100) NULL,
	[PRIMARYCATEGORY] [nvarchar](1000) NULL,
	[SECONDARYCATEGORY] [nvarchar](128) NULL,
	[PRIMARYSUBCATEGORY] [nvarchar](128) NULL,
	[SECONDARYSUBCATEGORY] [nvarchar](128) NULL,
	[KITNOTE] [nvarchar](1000) NULL
);






GO
CREATE NONCLUSTERED INDEX [IX_SIS_KitNumbers_KITNUMBER]
    ON [KIM].[SIS_KitNumbers]([KITNUMBER] ASC)
    INCLUDE([PARTNAME]);

