CREATE TABLE [KIM].[SIS_KitParentParts] (
    [KITNUMBER]        NVARCHAR (7)  NULL,
    [PARENTPART]       NVARCHAR (7)  NULL,
    [COMPONENTSETTYPE] NVARCHAR (30) NULL
);




GO
CREATE NONCLUSTERED INDEX [IX_SIS_KitParentParts_PARENTPART]
    ON [KIM].[SIS_KitParentParts]([PARENTPART] ASC)
    INCLUDE([KITNUMBER]);

