CREATE TYPE [dbo].UDTT_PRODUCTINSTANCE_INSERT_IN AS TABLE
(
	MEDIANUMBER           varchar(8),
	IESYSTEMCONTROLNUMBER varchar(12),
	NUMBER                varchar(60)
	PRIMARY KEY NONCLUSTERED
	(
		MEDIANUMBER           ASC,
		IESYSTEMCONTROLNUMBER ASC,
		NUMBER                ASC
	)
)
GO