CREATE TYPE [dbo].UDTT_MEDIANUBERIESYSTEMCONTROLNUMBER AS TABLE
(
	MEDIANUMBER           varchar(8),
	IESYSTEMCONTROLNUMBER varchar(12)
	PRIMARY KEY NONCLUSTERED
	(
		MEDIANUMBER           ASC,
		IESYSTEMCONTROLNUMBER ASC
	)
)
GO