
/* Davide: Created 20191017 */

CREATE FUNCTION sis.tvf_TranslatedIETitles(@DESIRED_LANGUAGEINDICATOR VARCHAR(2)    = 'E'
										,@JSON                      NVARCHAR(MAX))
RETURNS @RETURN_DATASET TABLE (IESYSTEMCONTROLNUMBER VARCHAR(12) NOT NULL
							  ,IELANGUAGEINDICATOR   VARCHAR(2) NOT NULL
							  ,IETITLE               NVARCHAR(3072) NOT NULL) 
AS
BEGIN
	DECLARE @FALLBACK_LANGUAGEINDICATOR VARCHAR(2) = 'E';

	WITH IESYSTEMCONTROLNUMBERS
		 AS (SELECT IESYSTEMCONTROLNUMBER
			 FROM OPENJSON(@JSON) WITH(IESYSTEMCONTROLNUMBER VARCHAR(12) '$')),
		 FALLBACK_DATASET
		 AS (SELECT A.IESYSTEMCONTROLNUMBER,A.IELANGUAGEINDICATOR,A.IETITLE
			 FROM SISWEB_OWNER.LNKIETITLE AS A
			 WHERE A.IELANGUAGEINDICATOR = @FALLBACK_LANGUAGEINDICATOR AND 
				   A.IESYSTEMCONTROLNUMBER IN
			 (
				 SELECT I.IESYSTEMCONTROLNUMBER
				 FROM IESYSTEMCONTROLNUMBERS AS I
			 )),
		 DESIRED_DATASET
		 AS (SELECT A.IESYSTEMCONTROLNUMBER,A.IELANGUAGEINDICATOR,A.IETITLE
			 FROM SISWEB_OWNER.LNKIETITLE AS A
			 WHERE A.IELANGUAGEINDICATOR = @DESIRED_LANGUAGEINDICATOR AND 
				   A.IESYSTEMCONTROLNUMBER IN
			 (
				 SELECT I.IESYSTEMCONTROLNUMBER
				 FROM IESYSTEMCONTROLNUMBERS AS I
			 ))
		 INSERT INTO @RETURN_DATASET
				SELECT COALESCE(DD.IESYSTEMCONTROLNUMBER,FD.IESYSTEMCONTROLNUMBER) AS IESYSTEMCONTROLNUMBER,COALESCE(DD.IELANGUAGEINDICATOR,FD.IELANGUAGEINDICATOR) AS
				IELANGUAGEINDICATOR,COALESCE(DD.IETITLE,FD.IETITLE) AS IETITLE
				FROM DESIRED_DATASET AS DD
					 FULL OUTER JOIN FALLBACK_DATASET AS FD ON FD.IESYSTEMCONTROLNUMBER = DD.IESYSTEMCONTROLNUMBER;

	RETURN;
END;