
/* Davide: Created  20200813 https://sis-cat-com.visualstudio.com/sis2-ui/_workitems/edit/6694 */
/* Davide: Modified 20200917 https://dev.azure.com/sis-cat-com/devops-infra/_workitems/edit/7481/ */
/* Davide: Modified 20201023 https://dev.azure.com/sis-cat-com/sis2-ui/_workitems/edit/8160/ */

CREATE FUNCTION sis.tvf_ProductStructureOutlineCaptiveToPrime_v1_1(@LANGUAGE_CODE VARCHAR(2)    = 'en'
															   ,@JSON          NVARCHAR(MAX))
RETURNS @RETURN_DATASET TABLE
	(MEDIANUMBER              VARCHAR(8) NOT NULL
	,IESYSTEMCONTROLNUMBER    VARCHAR(12) NOT NULL
	,PARENTAGE                NUMERIC(1,0) NOT NULL
	,PARENTPRODUCTSTRUCTUREID CHAR(8) NOT NULL
	,PRODUCTSTRUCTUREID       CHAR(8) NOT NULL
	,INFOTYPEID               SMALLINT NOT NULL
	,PARTNUMBER               VARCHAR(50) NULL
    ,ORGCODE                  VARCHAR(12) NULL
	,PARTNAME                 NVARCHAR(128) NULL
	,PARTMODIFIER             NVARCHAR(512) NULL
	,PARTCAPTION              NVARCHAR(2048) NOT NULL
	,TYPECHANGEINDICATOR      CHAR(1) NULL
	,isTopLevel               BIT NULL) 
AS
	BEGIN
		DECLARE @SERIALNUMBER VARCHAR(8) = (SELECT SERIALNUMBER FROM OPENJSON(@JSON) WITH(SERIALNUMBER VARCHAR(8) '$'));
		IF EXISTS(SELECT PRIMESERIALNUMBER AS P
					FROM SISWEB_OWNER.LNKCAPTIVETOPRIME AS L
					WHERE L.PRIMESERIALNUMBER = @SERIALNUMBER)
		BEGIN
			-- serialnumbers that appear in LNKCAPTIVETOPRIME having captive(s) enter here.

			DECLARE @PRIMESERIALNUMBER VARCHAR(8) = @SERIALNUMBER;
			DECLARE @PRIMESNP CHAR(3) = SUBSTRING(@PRIMESERIALNUMBER,1,3);
			DECLARE @PRIMESNR INT = TRY_CAST(SUBSTRING(@PRIMESERIALNUMBER,4,LEN(@PRIMESERIALNUMBER)) AS INT);
			
			if (@LANGUAGE_CODE = 'ja')
				BEGIN
				WITH CAPTIVESERIALNUMBERS(CAPTIVESERIALNUMBER
										 ,CAPTIVESNP
										 ,CAPTIVESNR)
					 AS (SELECT L.CAPTIVESERIALNUMBER
							   ,SUBSTRING(L.CAPTIVESERIALNUMBER,1,3)
							   ,TRY_CAST(SUBSTRING(L.CAPTIVESERIALNUMBER,4,LEN(L.CAPTIVESERIALNUMBER)) AS INT)
						   FROM SISWEB_OWNER.LNKCAPTIVETOPRIME AS L
						   WHERE L.PRIMESERIALNUMBER = @PRIMESERIALNUMBER),
					 IESYSTEMCONTROLNUMBERS
					 AS (SELECT DISTINCT 
								A.IESYSTEMCONTROLNUMBER
						   FROM SISWEB_OWNER.LNKPARTSIESNP AS A
						   WHERE
								 A.SNP = @PRIMESNP
								 AND @PRIMESNR BETWEEN A.BEGINNINGRANGE AND A.ENDRANGE),
					 MATCHING
					 AS (SELECT DISTINCT 
								OQ.IESYSTEMCONTROLNUMBER
							   ,P.SNP
							   ,P.BEGINNINGRANGE
							   ,P.ENDRANGE
							   ,P.SNPTYPE
							   ,@PRIMESNP AS                                                          PRIMESNP
							   ,@PRIMESNR AS                                                          PRIMESNR
							   ,CASE
									WHEN
										 P.SNPTYPE = 'P'
										 AND P.SNP = @PRIMESNP THEN 1
											 ELSE 0
								END AS                                                                HAS_PRIME
							   ,CASE
									WHEN
										 P.SNP = @PRIMESNP
										 AND @PRIMESNR BETWEEN P.BEGINNINGRANGE AND P.ENDRANGE THEN 1
									   ELSE 0
								END AS                                                                MATCHES_PRIME
							   ,CASE
									WHEN EXISTS(SELECT C.CAPTIVESNP FROM CAPTIVESERIALNUMBERS AS C WHERE C.CAPTIVESNP = P.SNP) THEN 1
									   ELSE 0
								END AS                                                                HAS_CAPTIVE
							   ,(SELECT COUNT(*)
								   FROM CAPTIVESERIALNUMBERS AS C
								   WHERE
										 C.CAPTIVESNP = P.SNP
										 AND C.CAPTIVESNR BETWEEN P.BEGINNINGRANGE AND P.ENDRANGE) AS MATCHES_CAPTIVE
						   FROM IESYSTEMCONTROLNUMBERS AS OQ
								LEFT JOIN SISWEB_OWNER.LNKPARTSIESNP AS P ON OQ.IESYSTEMCONTROLNUMBER = P.IESYSTEMCONTROLNUMBER),
					 TO_BE_REMOVED
					 AS (SELECT NQ.IESYSTEMCONTROLNUMBER
						   FROM MATCHING AS NQ
						   GROUP BY NQ.IESYSTEMCONTROLNUMBER
						   HAVING
								  SUM(HAS_CAPTIVE) > 0
								  AND SUM(MATCHES_CAPTIVE) = 0)
					 INSERT INTO @RETURN_DATASET
					 SELECT DISTINCT 
							A.MEDIANUMBER
						   ,A.IESYSTEMCONTROLNUMBER
							--,M.BASEENGCONTROLNO
						   ,C.PARENTAGE
						   ,FORMAT(CAST(C.PARENTPRODUCTSTRUCTUREID AS INT),'00000000') AS PARENTPRODUCTSTRUCTUREID
						   ,FORMAT(CAST(B.PSID AS INT),'00000000') AS                     PRODUCTSTRUCTUREID
						   ,D.INFOTYPEID
						   ,F.IEPARTNUMBER AS                                             PARTNUMBER
                           ,F.ORGCODE
						   ,F.IEPARTNAME AS                                               PARTNAME
						   ,F.IEPARTMODIFIER AS                                           PARTMODIFIER
						   ,F.IECAPTION AS                                                PARTCAPTION
						   ,M.TYPECHANGEINDICATOR
						   ,F.isTopLevel
					   FROM SISWEB_OWNER.LNKPARTSIESNP AS A
							INNER JOIN SISWEB_OWNER.LNKIEPSID AS B ON
																	  A.IESYSTEMCONTROLNUMBER = B.IESYSTEMCONTROLNUMBER
																	  AND A.MEDIANUMBER = B.MEDIANUMBER
							INNER JOIN SISWEB_OWNER.LNKMEDIAIEPART AS M ON
																		   M.MEDIANUMBER = A.MEDIANUMBER
																		   AND M.IESYSTEMCONTROLNUMBER = A.IESYSTEMCONTROLNUMBER
							INNER JOIN SISWEB_OWNER.MASPRODUCTSTRUCTURE AS C ON
																				B.PSID = C.PRODUCTSTRUCTUREID
																				AND C.LANGUAGEINDICATOR = 'E'
							INNER JOIN sis.vw_LNKIEINFOTYPE_Active AS D ON A.IESYSTEMCONTROLNUMBER = D.IESYSTEMCONTROLNUMBER
							INNER JOIN sis.vw_LNKMEDIAIEPART_SNP_TopLevel AS F ON
																			  C.PRODUCTSTRUCTUREID = F.PSID
																			  AND A.MEDIANUMBER = F.MEDIANUMBER
																			  AND A.IESYSTEMCONTROLNUMBER = F.IESYSTEMCONTROLNUMBER
																			  AND A.SNP = F.SNP
					   WHERE
							 A.SNP = @PRIMESNP
							 AND @PRIMESNR BETWEEN A.BEGINNINGRANGE AND A.ENDRANGE
							 AND A.IESYSTEMCONTROLNUMBER NOT IN(SELECT TBR.IESYSTEMCONTROLNUMBER FROM TO_BE_REMOVED AS TBR);
				END
			ELSE
				BEGIN
				WITH CAPTIVESERIALNUMBERS(CAPTIVESERIALNUMBER
										 ,CAPTIVESNP
										 ,CAPTIVESNR)
					 AS (SELECT L.CAPTIVESERIALNUMBER
							   ,SUBSTRING(L.CAPTIVESERIALNUMBER,1,3)
							   ,TRY_CAST(SUBSTRING(L.CAPTIVESERIALNUMBER,4,LEN(L.CAPTIVESERIALNUMBER)) AS INT)
						   FROM SISWEB_OWNER.LNKCAPTIVETOPRIME AS L
						   WHERE L.PRIMESERIALNUMBER = @PRIMESERIALNUMBER),
					 IESYSTEMCONTROLNUMBERS
					 AS (SELECT DISTINCT 
								A.IESYSTEMCONTROLNUMBER
						   FROM SISWEB_OWNER.LNKPARTSIESNP AS A
						   WHERE
								 A.SNP = @PRIMESNP
								 AND @PRIMESNR BETWEEN A.BEGINNINGRANGE AND A.ENDRANGE),
					 MATCHING
					 AS (SELECT DISTINCT 
								OQ.IESYSTEMCONTROLNUMBER
							   ,P.SNP
							   ,P.BEGINNINGRANGE
							   ,P.ENDRANGE
							   ,P.SNPTYPE
							   ,@PRIMESNP AS                                                          PRIMESNP
							   ,@PRIMESNR AS                                                          PRIMESNR
							   ,CASE
									WHEN
										 P.SNPTYPE = 'P'
										 AND P.SNP = @PRIMESNP THEN 1
											 ELSE 0
								END AS                                                                HAS_PRIME
							   ,CASE
									WHEN
										 P.SNP = @PRIMESNP
										 AND @PRIMESNR BETWEEN P.BEGINNINGRANGE AND P.ENDRANGE THEN 1
									   ELSE 0
								END AS                                                                MATCHES_PRIME
							   ,CASE
									WHEN EXISTS(SELECT C.CAPTIVESNP FROM CAPTIVESERIALNUMBERS AS C WHERE C.CAPTIVESNP = P.SNP) THEN 1
									   ELSE 0
								END AS                                                                HAS_CAPTIVE
							   ,(SELECT COUNT(*)
								   FROM CAPTIVESERIALNUMBERS AS C
								   WHERE
										 C.CAPTIVESNP = P.SNP
										 AND C.CAPTIVESNR BETWEEN P.BEGINNINGRANGE AND P.ENDRANGE) AS MATCHES_CAPTIVE
						   FROM IESYSTEMCONTROLNUMBERS AS OQ
								LEFT JOIN SISWEB_OWNER.LNKPARTSIESNP AS P ON OQ.IESYSTEMCONTROLNUMBER = P.IESYSTEMCONTROLNUMBER),
					 TO_BE_REMOVED
					 AS (SELECT NQ.IESYSTEMCONTROLNUMBER
						   FROM MATCHING AS NQ
						   GROUP BY NQ.IESYSTEMCONTROLNUMBER
						   HAVING
								  SUM(HAS_CAPTIVE) > 0
								  AND SUM(MATCHES_CAPTIVE) = 0)
					 INSERT INTO @RETURN_DATASET
					 SELECT DISTINCT 
							A.MEDIANUMBER
						   ,A.IESYSTEMCONTROLNUMBER
							--,M.BASEENGCONTROLNO
						   ,C.PARENTAGE
						   ,FORMAT(CAST(C.PARENTPRODUCTSTRUCTUREID AS INT),'00000000') AS PARENTPRODUCTSTRUCTUREID
						   ,FORMAT(CAST(B.PSID AS INT),'00000000') AS                     PRODUCTSTRUCTUREID
						   ,D.INFOTYPEID
						   ,F.IEPARTNUMBER AS                                             PARTNUMBER
                           ,F.ORGCODE
						   ,F.IEPARTNAME AS                                               PARTNAME
						   ,F.IEPARTMODIFIER AS                                           PARTMODIFIER
						   ,F.IECAPTION AS                                                PARTCAPTION
						   ,M.TYPECHANGEINDICATOR
						   ,F.isTopLevel
					   FROM SISWEB_OWNER.LNKPARTSIESNP AS A
							INNER JOIN SISWEB_OWNER.LNKIEPSID AS B ON
																	  A.IESYSTEMCONTROLNUMBER = B.IESYSTEMCONTROLNUMBER
																	  AND A.MEDIANUMBER = B.MEDIANUMBER
							INNER JOIN SISWEB_OWNER.LNKMEDIAIEPART AS M ON
																		   M.MEDIANUMBER = A.MEDIANUMBER
																		   AND M.IESYSTEMCONTROLNUMBER = A.IESYSTEMCONTROLNUMBER
							INNER JOIN SISWEB_OWNER.MASPRODUCTSTRUCTURE AS C ON
																				B.PSID = C.PRODUCTSTRUCTUREID
																				AND C.LANGUAGEINDICATOR = 'E'
							INNER JOIN sis.vw_LNKIEINFOTYPE_Active AS D ON A.IESYSTEMCONTROLNUMBER = D.IESYSTEMCONTROLNUMBER
							INNER JOIN SISWEB_OWNER.MASMEDIA E ON E.MEDIANUMBER = A.MEDIANUMBER
							INNER JOIN sis.vw_LNKMEDIAIEPART_SNP_TopLevel AS F ON
																			  C.PRODUCTSTRUCTUREID = F.PSID
																			  AND A.MEDIANUMBER = F.MEDIANUMBER
																			  AND A.IESYSTEMCONTROLNUMBER = F.IESYSTEMCONTROLNUMBER
																			  AND A.SNP = F.SNP
					   WHERE
							 A.SNP = @PRIMESNP
							 AND @PRIMESNR BETWEEN A.BEGINNINGRANGE AND A.ENDRANGE
							 AND A.IESYSTEMCONTROLNUMBER NOT IN(SELECT TBR.IESYSTEMCONTROLNUMBER FROM TO_BE_REMOVED AS TBR)
							 AND E.MEDIAORIGIN != 'SJ';
				END

		END;
		ELSE
		BEGIN
			-- serialnumbers that do not appear in LNKCAPTIVETOPRIME having captive(s) enter here.
			-- so captive(s) plus some prime that have no captive enter here. It may be good as we spare some irrelevant joins.

			DECLARE @CAPTIVESERIALNUMBER VARCHAR(8) = @SERIALNUMBER;
			DECLARE @CAPTIVESNP CHAR(3) = SUBSTRING(@CAPTIVESERIALNUMBER,1,3);
			DECLARE @CAPTIVESNR INT = TRY_CAST(SUBSTRING(@CAPTIVESERIALNUMBER,4,LEN(@CAPTIVESERIALNUMBER)) AS INT);

			if (@LANGUAGE_CODE = 'ja')
				BEGIN
				WITH ORIGINAL_QUERY
					 AS (SELECT DISTINCT 
								A.MEDIANUMBER
							   ,A.IESYSTEMCONTROLNUMBER
							   ,C.PARENTAGE
							   ,C.PARENTPRODUCTSTRUCTUREID
							   ,C.PRODUCTSTRUCTUREID
							   ,D.INFOTYPEID
							   ,F.IEPARTNUMBER AS   PARTNUMBER
					           ,F.ORGCODE
							   ,F.IEPARTNAME AS     PARTNAME
							   ,F.IEPARTMODIFIER AS PARTMODIFIER
							   ,F.IECAPTION AS      PARTCAPTION
							   ,M.TYPECHANGEINDICATOR
							   ,F.isTopLevel
						   FROM SISWEB_OWNER.LNKPARTSIESNP AS A
								INNER JOIN SISWEB_OWNER.LNKIEPSID AS B ON
																		  A.IESYSTEMCONTROLNUMBER = B.IESYSTEMCONTROLNUMBER
																		  AND A.MEDIANUMBER = B.MEDIANUMBER
								INNER JOIN SISWEB_OWNER.LNKMEDIAIEPART AS M ON
																			   M.MEDIANUMBER = A.MEDIANUMBER
																			   AND M.IESYSTEMCONTROLNUMBER = A.IESYSTEMCONTROLNUMBER
								INNER JOIN SISWEB_OWNER.MASPRODUCTSTRUCTURE AS C ON
																					B.PSID = C.PRODUCTSTRUCTUREID
																					AND C.LANGUAGEINDICATOR = 'E'
								INNER JOIN sis.vw_LNKIEINFOTYPE_Active AS D ON A.IESYSTEMCONTROLNUMBER = D.IESYSTEMCONTROLNUMBER
								INNER JOIN sis.vw_LNKMEDIAIEPART_SNP_TopLevel AS F ON
																				  C.PRODUCTSTRUCTUREID = F.PSID
																				  AND A.MEDIANUMBER = F.MEDIANUMBER
																				  AND A.IESYSTEMCONTROLNUMBER = F.IESYSTEMCONTROLNUMBER
																				  AND A.SNP = F.SNP
						   WHERE
								 A.SNP = @CAPTIVESNP
								 AND @CAPTIVESNR BETWEEN A.BEGINNINGRANGE AND A.ENDRANGE)
					 INSERT INTO @RETURN_DATASET
					 SELECT OQ.MEDIANUMBER
						   ,OQ.IESYSTEMCONTROLNUMBER
						   ,OQ.PARENTAGE
						   ,FORMAT(CAST(OQ.PARENTPRODUCTSTRUCTUREID AS INT),'00000000') AS PARENTPRODUCTSTRUCTUREID
						   ,FORMAT(CAST(OQ.PRODUCTSTRUCTUREID AS INT),'00000000') AS       PRODUCTSTRUCTUREID
						   ,OQ.INFOTYPEID
						   ,OQ.PARTNUMBER
					       ,OQ.ORGCODE
						   ,OQ.PARTNAME
						   ,OQ.PARTMODIFIER
						   ,OQ.PARTCAPTION
						   ,OQ.TYPECHANGEINDICATOR
						   ,OQ.isTopLevel
					   FROM ORIGINAL_QUERY AS OQ;
				END
			ELSE
				BEGIN
				WITH ORIGINAL_QUERY
					 AS (SELECT DISTINCT 
								A.MEDIANUMBER
							   ,A.IESYSTEMCONTROLNUMBER
							   ,C.PARENTAGE
							   ,C.PARENTPRODUCTSTRUCTUREID
							   ,C.PRODUCTSTRUCTUREID
							   ,D.INFOTYPEID
							   ,F.IEPARTNUMBER AS   PARTNUMBER
					           ,F.ORGCODE
							   ,F.IEPARTNAME AS     PARTNAME
							   ,F.IEPARTMODIFIER AS PARTMODIFIER
							   ,F.IECAPTION AS      PARTCAPTION
							   ,M.TYPECHANGEINDICATOR
							   ,F.isTopLevel
						   FROM SISWEB_OWNER.LNKPARTSIESNP AS A
								INNER JOIN SISWEB_OWNER.LNKIEPSID AS B ON
																		  A.IESYSTEMCONTROLNUMBER = B.IESYSTEMCONTROLNUMBER
																		  AND A.MEDIANUMBER = B.MEDIANUMBER
								INNER JOIN SISWEB_OWNER.LNKMEDIAIEPART AS M ON
																			   M.MEDIANUMBER = A.MEDIANUMBER
																			   AND M.IESYSTEMCONTROLNUMBER = A.IESYSTEMCONTROLNUMBER
								INNER JOIN SISWEB_OWNER.MASPRODUCTSTRUCTURE AS C ON
																					B.PSID = C.PRODUCTSTRUCTUREID
																					AND C.LANGUAGEINDICATOR = 'E'
								INNER JOIN sis.vw_LNKIEINFOTYPE_Active AS D ON A.IESYSTEMCONTROLNUMBER = D.IESYSTEMCONTROLNUMBER
								INNER JOIN SISWEB_OWNER.MASMEDIA E ON E.MEDIANUMBER = A.MEDIANUMBER
								INNER JOIN sis.vw_LNKMEDIAIEPART_SNP_TopLevel AS F ON
																				  C.PRODUCTSTRUCTUREID = F.PSID
																				  AND A.MEDIANUMBER = F.MEDIANUMBER
																				  AND A.IESYSTEMCONTROLNUMBER = F.IESYSTEMCONTROLNUMBER
																				  AND A.SNP = F.SNP
						   WHERE
								 A.SNP = @CAPTIVESNP
								 AND @CAPTIVESNR BETWEEN A.BEGINNINGRANGE AND A.ENDRANGE
								 AND E.MEDIAORIGIN != 'SJ')

					 INSERT INTO @RETURN_DATASET
					 SELECT OQ.MEDIANUMBER
						   ,OQ.IESYSTEMCONTROLNUMBER
						   ,OQ.PARENTAGE
						   ,FORMAT(CAST(OQ.PARENTPRODUCTSTRUCTUREID AS INT),'00000000') AS PARENTPRODUCTSTRUCTUREID
						   ,FORMAT(CAST(OQ.PRODUCTSTRUCTUREID AS INT),'00000000') AS       PRODUCTSTRUCTUREID
						   ,OQ.INFOTYPEID
						   ,OQ.PARTNUMBER
						   ,OQ.ORGCODE
						   ,OQ.PARTNAME
						   ,OQ.PARTMODIFIER
						   ,OQ.PARTCAPTION
						   ,OQ.TYPECHANGEINDICATOR
						   ,OQ.isTopLevel
					   FROM ORIGINAL_QUERY AS OQ;
				END
		END;

		RETURN;
	END;