CREATE FUNCTION sis.tvf_TranslatedSmcsDescriptions(@DESIRED_LANGUAGEINDICATOR VARCHAR(2)    = 'E'
												 ,@JSON                      NVARCHAR(MAX))
RETURNS @RETURN_DATASET TABLE
	(LANGUAGEINDICATOR VARCHAR(2) NOT NULL
	,SMCSCOMPCODE      CHAR(4) NOT NULL
	,SMCSDESCRIPTION   NVARCHAR(192) NOT NULL) 
AS
	BEGIN
		DECLARE @FALLBACK_LANGUAGEINDICATOR VARCHAR(2) = 'E';

		WITH SMCSCOMPCODES
			 AS (SELECT SMCSCOMPCODE FROM OPENJSON(@JSON) WITH(SMCSCOMPCODE CHAR(4) '$')),
			 FALLBACK_DATASET
			 AS (SELECT FD.LANGUAGEINDICATOR
					   ,FD.SMCSCOMPCODE
					   ,FD.SMCSDESCRIPTION
				   FROM SISWEB_OWNER.MASSMCS AS FD
				   WHERE
						 FD.LANGUAGEINDICATOR = @FALLBACK_LANGUAGEINDICATOR
						 AND FD.SMCSCOMPCODE IN
					 (SELECT I.SMCSCOMPCODE FROM SMCSCOMPCODES AS I) ),
			 DESIRED_DATASET
			 AS (SELECT DD.LANGUAGEINDICATOR
					   ,DD.SMCSCOMPCODE
					   ,DD.SMCSDESCRIPTION
				   FROM SISWEB_OWNER.MASSMCS AS DD
				   WHERE
						 DD.LANGUAGEINDICATOR = @DESIRED_LANGUAGEINDICATOR
						 AND DD.SMCSCOMPCODE IN
					 (SELECT I.SMCSCOMPCODE FROM SMCSCOMPCODES AS I) )
			 INSERT INTO @RETURN_DATASET
			 SELECT COALESCE(DD.LANGUAGEINDICATOR,FD.LANGUAGEINDICATOR) AS LANGUAGEINDICATOR
				   ,COALESCE(DD.SMCSCOMPCODE,FD.SMCSCOMPCODE) AS           SMCSCOMPCODE
				   ,COALESCE(DD.SMCSDESCRIPTION,FD.SMCSDESCRIPTION) AS     SMCSDESCRIPTION
			   FROM DESIRED_DATASET AS DD
					FULL OUTER JOIN FALLBACK_DATASET AS FD ON FD.SMCSCOMPCODE = DD.SMCSCOMPCODE;

		RETURN;
	END;