
/* Davide: Created  20200304 https://sis-cat-com.visualstudio.com/devops-infra/_workitems/edit/5883/ */
/* Davide: Modified 20200320 https://dev.azure.com/sis-cat-com/devops-infra/_workitems/edit/5968/ */

CREATE FUNCTION sis.tvf_TranslatedIETitles_v2(@LANGUAGE_CODE VARCHAR(2)    = 'en'
											,@JSON          NVARCHAR(MAX))
RETURNS @RETURN_DATASET TABLE
	(IESYSTEMCONTROLNUMBER VARCHAR(12) NOT NULL
	,LANGUAGE_CODE         VARCHAR(2) NOT NULL
	,IETITLE               NVARCHAR(3072) NOT NULL) 
AS
	BEGIN
		DECLARE @FALLBACK_LANGUAGEID INT
			   ,@DESIRED_LANGUAGEID  INT;
		SELECT @FALLBACK_LANGUAGEID = L.Language_ID
		  FROM sis.Language AS L
		  WHERE
				L.Language_Code = 'en'
				AND L.Default_Language = 1;
		SELECT @DESIRED_LANGUAGEID = L.Language_ID
		  FROM sis.Language AS L
		  WHERE
				L.Language_Code = @LANGUAGE_CODE
				AND L.Default_Language = 1;

		WITH IESYSTEMCONTROLNUMBERS(IESYSTEMCONTROLNUMBER)
			 AS (SELECT IESYSTEMCONTROLNUMBER FROM OPENJSON(@JSON) WITH(IESYSTEMCONTROLNUMBER VARCHAR(12) '$')),
			 FALLBACK_DATASET
			 AS (SELECT IE.IESystemControlNumber AS IESYSTEMCONTROLNUMBER
					   ,L.Language_Code AS          LANGUAGE_CODE
					   ,IET.Title AS                IETITLE
				   FROM sis.IE AS IE
						JOIN sis.IE_Translation AS IET ON IET.IE_ID = IE.IE_ID
						JOIN sis.Language AS L ON L.Language_ID = IET.Language_ID
				   WHERE
						 IET.Language_ID = @FALLBACK_LANGUAGEID
						 AND IE.IESystemControlNumber IN(SELECT I.IESYSTEMCONTROLNUMBER FROM IESYSTEMCONTROLNUMBERS AS I)),
			 DESIRED_DATASET
			 AS (SELECT IE.IESystemControlNumber AS IESYSTEMCONTROLNUMBER
					   ,L.Language_Code AS          LANGUAGE_CODE
					   ,IET.Title AS                IETITLE
				   FROM sis.IE AS IE
						JOIN sis.IE_Translation AS IET ON IET.IE_ID = IE.IE_ID
						JOIN sis.Language AS L ON L.Language_ID = IET.Language_ID
				   WHERE
						 IET.Language_ID = @DESIRED_LANGUAGEID
						 AND IE.IESystemControlNumber IN(SELECT I.IESYSTEMCONTROLNUMBER FROM IESYSTEMCONTROLNUMBERS AS I))
			 INSERT INTO @RETURN_DATASET
					(IESYSTEMCONTROLNUMBER
					,LANGUAGE_CODE
					,IETITLE
					) 
			 SELECT COALESCE(DD.IESYSTEMCONTROLNUMBER,FD.IESYSTEMCONTROLNUMBER) AS IESYSTEMCONTROLNUMBER
				   ,COALESCE(DD.LANGUAGE_CODE,FD.LANGUAGE_CODE) AS                 LANGUAGE_CODE
				   ,COALESCE(DD.IETITLE,FD.IETITLE) AS                             IETITLE
			   FROM DESIRED_DATASET AS DD
					FULL OUTER JOIN FALLBACK_DATASET AS FD ON FD.IESYSTEMCONTROLNUMBER = DD.IESYSTEMCONTROLNUMBER;

		RETURN;
	END;
GO

