
/* Davide: Created 20191023 */

CREATE FUNCTION sis.tvf_TranslatedInfoTypes(@DESIRED_LANGUAGEINDICATOR VARCHAR(2)    = 'E'
										  ,@JSON                      NVARCHAR(MAX))
RETURNS @RETURN_DATASET TABLE
	(INFOTYPEID          NUMERIC(3,0) NOT NULL
	,LANGUAGEINDICATOR   VARCHAR(2) NOT NULL
	,INFORMATIONTYPEDESC NVARCHAR(720) NOT NULL) 
AS
	BEGIN
		DECLARE @FALLBACK_LANGUAGEINDICATOR VARCHAR(2) = 'E';

		WITH INFOTYPEIDS
			 AS (SELECT INFOTYPEID FROM OPENJSON(@JSON) WITH(INFOTYPEID NUMERIC(3,0) '$')),
			 FALLBACK_DATASET
			 AS (SELECT FD.INFOTYPEID
					   ,FD.LANGUAGEINDICATOR
					   ,FD.INFORMATIONTYPEDESC
				   FROM SISWEB_OWNER.MASINFOTYPE AS FD
				   WHERE
						 FD.LANGUAGEINDICATOR = @FALLBACK_LANGUAGEINDICATOR
						 AND FD.INFOTYPEID IN
					 (SELECT I.INFOTYPEID FROM INFOTYPEIDS AS I) ),
			 DESIRED_DATASET
			 AS (SELECT DD.INFOTYPEID
					   ,DD.LANGUAGEINDICATOR
					   ,DD.INFORMATIONTYPEDESC
				   FROM SISWEB_OWNER.MASINFOTYPE AS DD
				   WHERE
						 DD.LANGUAGEINDICATOR = @DESIRED_LANGUAGEINDICATOR
						 AND DD.INFOTYPEID IN
					 (SELECT I.INFOTYPEID FROM INFOTYPEIDS AS I) )
			 INSERT INTO @RETURN_DATASET
					(INFOTYPEID
					,LANGUAGEINDICATOR
					,INFORMATIONTYPEDESC
					) 
			 SELECT COALESCE(DD.INFOTYPEID,FD.INFOTYPEID) AS                   INFOTYPEID
				   ,COALESCE(DD.LANGUAGEINDICATOR,FD.LANGUAGEINDICATOR) AS     LANGUAGEINDICATOR
				   ,COALESCE(DD.INFORMATIONTYPEDESC,FD.INFORMATIONTYPEDESC) AS INFORMATIONTYPEDESC
			   FROM DESIRED_DATASET AS DD
					FULL OUTER JOIN FALLBACK_DATASET AS FD ON DD.INFOTYPEID = FD.INFOTYPEID;
		RETURN;
	END;