
CREATE   VIEW [SISSEARCH].[vw_CONSISTPARTSORIGIN] AS
SELECT 
	b.IESYSTEMCONTROLNUMBER,
	b.IESYSTEMCONTROLNUMBER as ID,
	d.PARTNUMBER,
    d.ORGCODE,
	d.PARTNAME,
    b.LASTMODIFIEDDATE INSERTDATE
from [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] b With(NolocK)--3M
inner join [SISWEB_OWNER].[MASMEDIA] e with(Nolock)
	on e.MEDIANUMBER=b.MEDIANUMBER and e.[MEDIASOURCE]='A'  --Authoring 
inner join [SISWEB_OWNER_SHADOW].LNKCONSISTLIST d With(Nolock) --56M
	on b.IESYSTEMCONTROLNUMBER = d.IESYSTEMCONTROLNUMBER
UNION SELECT
    b.IESYSTEMCONTROLNUMBER,
	b.IESYSTEMCONTROLNUMBER as id,	
	d.PARTNUMBER,
    d.ORGCODE,
	d.PARTNAME,
    b.LASTMODIFIEDDATE INSERTDATE
from [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART] b With(NolocK)--3M
inner join [SISWEB_OWNER].[MASMEDIA] e with(Nolock)
	on e.MEDIANUMBER=b.MEDIANUMBER and e.[MEDIASOURCE] ='C'  --Conversion
inner join [SISWEB_OWNER_SHADOW].LNKCONSISTLIST d With(Nolock) --56M
	on d.IESYSTEMCONTROLNUMBER  = b.BASEENGCONTROLNO