CREATE VIEW [SISSEARCH].[vw_CONSISTPARTSHISTORY]
AS  SELECT 
	x.IESYSTEMCONTROLNUMBER as IESYSTEMCONTROLNUMBER, 
	replace('["'+string_agg(h.CONSISTPARTHISTORY, '","')+'"]', '[""]', '') as CONSISTPARTHISTORY,
	replace('["'+string_agg(h.CONSISTPARTREPLACEMENT, '","')+'"]', '[""]', '') as CONSISTPARTREPLACEMENT
from [SISSEARCH].[tvf_CONSISTPARTSORIGIN]('') x
LEFT JOIN [SISSEARCH].[vw_CONSISTPARTSHISTORY_ORIGIN] h ON h.Part_Number=x.PARTNUMBER and h.Org_Code=x.ORGCODE
group by x.IESYSTEMCONTROLNUMBER
GO