


CREATE   VIEW [SISSEARCH].[vw_MASMEDIATITLE] AS
Select * FROM (
	SELECT BASEENGLISHMEDIANUMBER --Candidate key composite
			,[LANGUAGEINDICATOR] --Candidate key composite
			,MEDIATITLE
	FROM [SISWEB_OWNER].[MASMEDIA]
) p
PIVOT
(
	MAX(MEDIATITLE) 
	FOR [LANGUAGEINDICATOR] in ([8], [C], [F], [G], [L], [P], [S], [R], [J])
) pvt