CREATE TABLE [SISWEB_OWNER_SHADOW].[EMPPRODUCTINSTANCE_BASE] (
    [EMPPRODUCTINSTANCE_ID]    INT                NOT NULL,
    [EMPSALESMODEL_ID]         INT                NOT NULL,
    [NUMBER]                VARCHAR (60)       NOT NULL,
    [NAME]                  VARCHAR (60)       NOT NULL,
    [ALIAS1]                VARCHAR (60),
    [ALIAS2]                VARCHAR (60),
    [ALIAS3]                VARCHAR (60),
    [ALTERNATESERIALNUMBER] VARCHAR (60),
    [NUMERICVALUE]          VARCHAR (10),
    [NUMERICVALUE2]         INT,
    [SALESORDERNUMBER]      VARCHAR (60),
    [SERVICEABLE]           BIT,
    [VERSION]               VARCHAR (13),
    [MODEL]                 VARCHAR (60),
    [SNP]                   VARCHAR (60),
    [STATE]                 VARCHAR (15),
    [CURRENTSTATE]          VARCHAR (15),
    [LASTMODIFIEDDATE]      DATETIME2 (6),
    CONSTRAINT [PK_EMPPRODUCTINSTANCE] PRIMARY KEY CLUSTERED ([EMPPRODUCTINSTANCE_ID] ASC),
    CONSTRAINT [UQ_EMPPRODUCTINSTANCE] UNIQUE(NUMBER)
);

GO
CREATE NONCLUSTERED INDEX IX_EMPPRODUCTINSTANCE_NUMBER_EMPSALESMODEL_ID_SNP
    ON SISWEB_OWNER_SHADOW.EMPPRODUCTINSTANCE_BASE (NUMBER ASC, EMPSALESMODEL_ID ASC, SNP ASC) INCLUDE(ALIAS1, ALIAS2, ALIAS3, NUMERICVALUE2, MODEL);
GO
EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER_SWAP on 2020-05-08 12:20:00 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SHADOW', @level1type = N'TABLE', @level1name = N'EMPPRODUCTINSTANCE_BASE';

GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER_SWAP on 2020-05-08 12:23:11 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SHADOW', @level1type = N'TABLE', @level1name = N'EMPPRODUCTINSTANCE_BASE';

