CREATE TABLE [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE] (
    [MEDIANUMBER]             VARCHAR (8)     NOT NULL,
    [IESYSTEMCONTROLNUMBER]   VARCHAR (12)    NOT NULL,
    [IEPARTNUMBER]            VARCHAR (40)    NULL,
    [ORGCODE]                 VARCHAR (12)    NOT NULL default 'CAT',
    [IEPARTNAME]              NVARCHAR (128)  NULL,
    [IESEQUENCENUMBER]        INT             NOT NULL,
    [BASEENGCONTROLNO]        VARCHAR (12)    NOT NULL,
    [SECTIONNUMBER]           INT             NOT NULL,
    [IEPARTMODIFIER]          NVARCHAR (512)  NULL,
    [IECAPTION]               NVARCHAR (2048) NOT NULL,
    [IETYPE]                  VARCHAR (1)     NOT NULL,
    [SERVICEABILITYINDICATOR] VARCHAR (1)     NOT NULL,
    [IEUPDATEDATE]            DATETIME2 (0)   NOT NULL,
    [IECONTROLNUMBER]         VARCHAR (25)    NULL,
    [PART]                    VARCHAR (2)     NULL,
    [OFPARTS]                 VARCHAR (2)     NULL,
    [ARRANGEMENTINDICATOR]    VARCHAR (1)     NOT NULL,
    [CCRINDICATOR]            VARCHAR (1)     NOT NULL,
    [FILTERPARTINDICATOR]     VARCHAR (1)     NOT NULL,
    [MAINTPARTINDICATOR]      VARCHAR (1)     NOT NULL,
    [NPRINDICATOR]            VARCHAR (1)     NULL,
    [TYPECHANGEINDICATOR]     VARCHAR (1)     NULL,
    [LASTMODIFIEDDATE]        DATETIME2 (6)   NULL,
    CONSTRAINT [LNKMEDIAIEPART_PK_LNKMEDIAIEPART] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC)
);












GO
CREATE NONCLUSTERED INDEX [NCX_LNKMEDIAIEPART_MEDIANUMBER_IESYSTEMCONTROLNUMBER]
    ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE]([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC)
    INCLUDE([BASEENGCONTROLNO], [IECAPTION], [IECONTROLNUMBER], [IEPARTMODIFIER], [IEPARTNAME], [IEPARTNUMBER], [IEUPDATEDATE], [NPRINDICATOR], [SERVICEABILITYINDICATOR]) WITH (STATISTICS_NORECOMPUTE = ON);




GO
CREATE NONCLUSTERED INDEX [nci_wi_LNKMEDIAIEPART_3446532BC9C8752464101ABF3EDEB829]
    ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE]([IESYSTEMCONTROLNUMBER] ASC)
    INCLUDE([LASTMODIFIEDDATE]) WITH (STATISTICS_NORECOMPUTE = ON);




GO
CREATE NONCLUSTERED INDEX [nci_wi_LNKMEDIAIEPART_0B05903EC8551352A1E9D33FDBBBA441]
    ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE]([IEPARTNUMBER] ASC)
    INCLUDE([BASEENGCONTROLNO], [OFPARTS], [PART], [ARRANGEMENTINDICATOR],[IETYPE]) WITH (STATISTICS_NORECOMPUTE = ON);




GO
CREATE NONCLUSTERED INDEX [nci_wi_LNKMEDIAIEPART_03CDCAB6C76A9197EDB51C1CDEFD7297]
    ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE]([LASTMODIFIEDDATE] ASC) WITH (STATISTICS_NORECOMPUTE = ON);

GO
CREATE INDEX [IX_LNKCONSISTLIST_PARTNUMBER_ORGCODE]
ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE] ([IEPARTNUMBER],[ORGCODE])


GO
EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER_SWAP on 2021-01-28 14:13:08 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SHADOW', @level1type = N'TABLE', @level1name = N'LNKMEDIAIEPART_BASE';








GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER_SWAP on 2021-01-28 14:13:14 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SHADOW', @level1type = N'TABLE', @level1name = N'LNKMEDIAIEPART';








GO
CREATE NONCLUSTERED INDEX [IX_LNKMEDIAIEPART_MEDIANUMBER_SECTIONNUMBER]
    ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE]([MEDIANUMBER] ASC, [SECTIONNUMBER] ASC)
    INCLUDE([IESYSTEMCONTROLNUMBER], [BASEENGCONTROLNO], [IESEQUENCENUMBER], [IEPARTMODIFIER], [IECAPTION]);

GO
CREATE NONCLUSTERED INDEX IDX_LNKMEDIAIEPART_ARRANGEMENTINDICATOR_IESYSTEMCONTROLNUMBER ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE] ([ARRANGEMENTINDICATOR],[IESYSTEMCONTROLNUMBER]) INCLUDE(IEPARTNUMBER);

GO
CREATE NONCLUSTERED INDEX [IX_NCL_LNKMEDIAIEPART_ORGCODE] ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE] ([ORGCODE])
GO

CREATE NONCLUSTERED INDEX [IX_NCL_IEPARTNUM_IEPARTNAME_IESCN_ORGCODE] ON [SISWEB_OWNER_SHADOW].[LNKMEDIAIEPART_BASE] ([IEPARTNUMBER],[IEPARTNAME],[IESYSTEMCONTROLNUMBER],[ORGCODE])

GO
