CREATE TABLE [SISWEB_OWNER_SHADOW].[LNKPARTSIESNP_BASE] (
    [MEDIANUMBER]           VARCHAR (8)   NOT NULL,
    [IESYSTEMCONTROLNUMBER] VARCHAR (12)  NOT NULL,
    [SNP]                   VARCHAR (10)  NOT NULL,
    [BEGINNINGRANGE]        INT           NOT NULL,
    [ENDRANGE]              INT           NOT NULL,
    [SNPTYPE]               VARCHAR (6)   NOT NULL,
    [LASTMODIFIEDDATE]      DATETIME2 (6) NULL,
    CONSTRAINT [LNKPARTSIESNP_PK_LNKPARTSIESNP] PRIMARY KEY CLUSTERED ([MEDIANUMBER] ASC, [IESYSTEMCONTROLNUMBER] ASC, [SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC, [SNPTYPE] ASC)
);


GO
CREATE NONCLUSTERED INDEX [NCX_LNKPARTSIESNP_IESystemControlNumber]
    ON [SISWEB_OWNER_SHADOW].[LNKPARTSIESNP_BASE]([IESYSTEMCONTROLNUMBER] ASC);


GO
CREATE NONCLUSTERED INDEX [NCX_LNKPARTSIESNP_SNP_BEGINNINGRANGE_ENDRANGE]
    ON [SISWEB_OWNER_SHADOW].[LNKPARTSIESNP_BASE]([SNP] ASC, [BEGINNINGRANGE] ASC, [ENDRANGE] ASC);


GO
CREATE NONCLUSTERED INDEX NCX_LNKPARTSIESNP_SNP_SNPTYPE ON [SISWEB_OWNER_SHADOW].[LNKPARTSIESNP_BASE] ([SNP],[SNPTYPE])

GO
EXECUTE sp_addextendedproperty @name = N'Previous Rotation', @value = N'From SISWEB_OWNER_SWAP on 2020-05-13 12:45:57 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SHADOW', @level1type = N'TABLE', @level1name = N'LNKPARTSIESNP_BASE';


GO
EXECUTE sp_addextendedproperty @name = N'Last Rotation', @value = N'From SISWEB_OWNER_SWAP on 2020-05-13 12:46:39 +00:00', @level0type = N'SCHEMA', @level0name = N'SISWEB_OWNER_SHADOW', @level1type = N'TABLE', @level1name = N'LNKPARTSIESNP_BASE';

