CREATE SCHEMA [SISWEB_OWNER_STAGING]
    AUTHORIZATION [dbo];



GO

GRANT SELECT,EXECUTE ON SCHEMA ::SISWEB_OWNER_STAGING TO [sisautomation];
GO

GRANT SELECT,UPDATE,INSERT,DELETE ON SCHEMA ::SISWEB_OWNER TO [sisattunity];
GO